# Generated by cppally: do not edit by hand

scalar_init <- function(ptype) {
  .Call(`_cppallytest_scalar_init`, ptype)
}

as_int64 <- function(x) {
  .Call(`_cppallytest_as_int64`, x)
}

as_r_size_t <- function(x) {
  .Call(`_cppallytest_as_r_size_t`, x)
}

cpp_length <- function(vec) {
  .Call(`_cppallytest_cpp_length`, vec)
}

add_half <- function(x) {
  .Call(`_cppallytest_add_half`, x)
}

symbol_to_string <- function(x) {
  .Call(`_cppallytest_symbol_to_string`, x)
}

new_factor <- function(x) {
  .Call(`_cppallytest_new_factor`, x)
}

factor_codes <- function(x) {
  .Call(`_cppallytest_factor_codes`, x)
}

cpp_lengths <- function(x) {
  .Call(`_cppallytest_cpp_lengths`, x)
}

cpp_lengths2 <- function(x) {
  .Call(`_cppallytest_cpp_lengths2`, x)
}

double_to_int <- function(x) {
  .Call(`_cppallytest_double_to_int`, x)
}

to_int_vec <- function(x) {
  .Call(`_cppallytest_to_int_vec`, x)
}

coercions <- function() {
  .Call(`_cppallytest_coercions`)
}

cpp_na_count <- function(x) {
  .Call(`_cppallytest_cpp_na_count`, x)
}

C_na_count <- function(x) {
  .Call(`_cppallytest_C_na_count`, x)
}

cpp_fast_na_count <- function(x) {
  .Call(`_cppallytest_cpp_fast_na_count`, x)
}

cpp_fast_na_count_v2 <- function(x) {
  .Call(`_cppallytest_cpp_fast_na_count_v2`, x)
}

cpp_set_threads <- function(n) {
  invisible(.Call(`_cppallytest_cpp_set_threads`, n))
}

cpp_get_threads <- function() {
  .Call(`_cppallytest_cpp_get_threads`)
}

cpp_get_max_threads <- function() {
  .Call(`_cppallytest_cpp_get_max_threads`)
}

cpp_typeof <- function(x) {
  .Call(`_cppallytest_cpp_typeof`, x)
}

test_identity2 <- function(x) {
  .Call(`_cppallytest_test_identity2`, x)
}

test_str1 <- function(x) {
  .Call(`_cppallytest_test_str1`, x)
}

test_str2 <- function(x) {
  .Call(`_cppallytest_test_str2`, x)
}

test_as_date <- function(x) {
  .Call(`_cppallytest_test_as_date`, x)
}

test_construct_date <- function(x) {
  .Call(`_cppallytest_test_construct_date`, x)
}

test_as_date2 <- function(x) {
  .Call(`_cppallytest_test_as_date2`, x)
}

test_null <- function() {
  .Call(`_cppallytest_test_null`)
}

test_sym <- function(x) {
  .Call(`_cppallytest_test_sym`, x)
}

test_sexp2 <- function(x) {
  .Call(`_cppallytest_test_sexp2`, x)
}

test_sexp3 <- function(x) {
  .Call(`_cppallytest_test_sexp3`, x)
}

test_coerce1 <- function(x) {
  .Call(`_cppallytest_test_coerce1`, x)
}

test_dates1 <- function(x) {
  .Call(`_cppallytest_test_dates1`, x)
}

test_tz <- function(x) {
  .Call(`_cppallytest_test_tz`, x)
}

test_lengths <- function(x) {
  .Call(`_cppallytest_test_lengths`, x)
}

test_lgl <- function() {
  .Call(`_cppallytest_test_lgl`)
}

test_deduced_type <- function(x) {
  .Call(`_cppallytest_test_deduced_type`, x)
}

test_multiple_deduction <- function(x, y) {
  .Call(`_cppallytest_test_multiple_deduction`, x, y)
}

test_deduced_vec_type <- function(x) {
  .Call(`_cppallytest_test_deduced_vec_type`, x)
}

test_deduced_scalar_type <- function(x) {
  .Call(`_cppallytest_test_deduced_scalar_type`, x)
}

test_deduced_scalar_type2 <- function(x) {
  .Call(`_cppallytest_test_deduced_scalar_type2`, x)
}

test_identity <- function(x) {
  .Call(`_cppallytest_test_identity`, x)
}

test_template_null <- function(x) {
  .Call(`_cppallytest_test_template_null`, x)
}

test_scalar <- function(x, y) {
  .Call(`_cppallytest_test_scalar`, x, y)
}

test_scalar2 <- function(x, y) {
  .Call(`_cppallytest_test_scalar2`, x, y)
}

test_scalar3 <- function(x, y) {
  .Call(`_cppallytest_test_scalar3`, x, y)
}

test_rval_identity <- function(x) {
  .Call(`_cppallytest_test_rval_identity`, x)
}

scalar1 <- function(x) {
  .Call(`_cppallytest_scalar1`, x)
}

scalar2 <- function(x) {
  .Call(`_cppallytest_scalar2`, x)
}

vector1 <- function(x) {
  .Call(`_cppallytest_vector1`, x)
}

vector2 <- function(x) {
  .Call(`_cppallytest_vector2`, x)
}

scalar3 <- function(x, y) {
  .Call(`_cppallytest_scalar3`, x, y)
}

scalar4 <- function(x, y) {
  .Call(`_cppallytest_scalar4`, x, y)
}

test_sexp <- function(x) {
  .Call(`_cppallytest_test_sexp`, x)
}

test_sexp4 <- function(x) {
  .Call(`_cppallytest_test_sexp4`, x)
}

scalar_vec1 <- function(a, b) {
  .Call(`_cppallytest_scalar_vec1`, a, b)
}

scalar_vec2 <- function(a, b) {
  .Call(`_cppallytest_scalar_vec2`, a, b)
}

scalar_vec3 <- function(z, x, y, a) {
  .Call(`_cppallytest_scalar_vec3`, z, x, y, a)
}

test_mix2 <- function(a, b, c, d, e, f, g) {
  .Call(`_cppallytest_test_mix2`, a, b, c, d, e, f, g)
}

test_str3 <- function(x) {
  .Call(`_cppallytest_test_str3`, x)
}

test_str4 <- function(x) {
  .Call(`_cppallytest_test_str4`, x)
}

test_specialisation <- function(x) {
  .Call(`_cppallytest_test_specialisation`, x)
}

test_coerce <- function(x, ptype) {
  .Call(`_cppallytest_test_coerce`, x, ptype)
}

test_list_to_scalars <- function(x) {
  .Call(`_cppallytest_test_list_to_scalars`, x)
}

test_combine2 <- function(x, y) {
  .Call(`_cppallytest_test_combine2`, x, y)
}

test_dates2 <- function(x) {
  .Call(`_cppallytest_test_dates2`, x)
}

test_unique <- function(x) {
  .Call(`_cppallytest_test_unique`, x)
}

test_seqs <- function(size, from, by) {
  .Call(`_cppallytest_test_seqs`, size, from, by)
}

test_group_id <- function(x, order) {
  .Call(`_cppallytest_test_group_id`, x, order)
}

test_group_counts <- function(x, order) {
  .Call(`_cppallytest_test_group_counts`, x, order)
}

test_match <- function(x, y) {
  .Call(`_cppallytest_test_match`, x, y)
}

test_factor2 <- function(x) {
  .Call(`_cppallytest_test_factor2`, x)
}

test_n_unique <- function(x) {
  .Call(`_cppallytest_test_n_unique`, x)
}

test_copy <- function(x) {
  .Call(`_cppallytest_test_copy`, x)
}

test_identical <- function(x, y) {
  .Call(`_cppallytest_test_identical`, x, y)
}

test_multiline_template_add <- function(x, y) {
  .Call(`_cppallytest_test_multiline_template_add`, x, y)
}

test_multiline_template_add2 <- function(x, y) {
  .Call(`_cppallytest_test_multiline_template_add2`, x, y)
}

test_attrs <- function(x) {
  .Call(`_cppallytest_test_attrs`, x)
}

test_df <- function(cols) {
  .Call(`_cppallytest_test_df`, cols)
}

test_as_sym <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_sym`, a, b, c, d, e, f)
}

test_as_int <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_int`, a, b, c, d, e, f)
}

test_as_dbl <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_dbl`, a, b, c, d, e, f)
}

test_as_str <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_str`, a, b, c, d, e, f)
}

test_factor1 <- function(x) {
  .Call(`_cppallytest_test_factor1`, x)
}

test_factor3 <- function(x) {
  .Call(`_cppallytest_test_factor3`, x)
}

test_nas <- function(x) {
  .Call(`_cppallytest_test_nas`, x)
}

test_na_types <- function() {
  .Call(`_cppallytest_test_na_types`)
}

bench_protect_insert_release_cppally <- function(n) {
  .Call(`_cppallytest_bench_protect_insert_release_cppally`, n)
}

bench_protect_copy_cppally <- function(n) {
  .Call(`_cppallytest_bench_protect_copy_cppally`, n)
}

test_order <- function(x, preserve_ties) {
  .Call(`_cppallytest_test_order`, x, preserve_ties)
}

test_sort <- function(x, preserve_ties) {
  .Call(`_cppallytest_test_sort`, x, preserve_ties)
}

test_range <- function(x, na_rm) {
  .Call(`_cppallytest_test_range`, x, na_rm)
}

test_sum <- function(x, na_rm) {
  .Call(`_cppallytest_test_sum`, x, na_rm)
}

test_mean <- function(x, na_rm) {
  .Call(`_cppallytest_test_mean`, x, na_rm)
}

test_var <- function(x, na_rm) {
  .Call(`_cppallytest_test_var`, x, na_rm)
}

test_subset <- function(x, i, invert) {
  .Call(`_cppallytest_test_subset`, x, i, invert)
}

test_fill <- function(x, where, with) {
  .Call(`_cppallytest_test_fill`, x, where, with)
}

test_counts <- function(x, y) {
  .Call(`_cppallytest_test_counts`, x, y)
}

test_remove <- function(x, y) {
  .Call(`_cppallytest_test_remove`, x, y)
}

test_find <- function(x, y) {
  .Call(`_cppallytest_test_find`, x, y)
}

test_replace <- function(x, y, z) {
  .Call(`_cppallytest_test_replace`, x, y, z)
}

test_valgrind <- function() {
  invisible(.Call(`_cppallytest_test_valgrind`))
}
