# Generated by cppally: do not edit by hand

cpp_set_threads <- function(n) {
  invisible(.Call(`_cppallytest_cpp_set_threads`, n))
}

cpp_get_threads <- function() {
  .Call(`_cppallytest_cpp_get_threads`)
}

cpp_get_max_threads <- function() {
  .Call(`_cppallytest_cpp_get_max_threads`)
}

cpp_typeof <- function(x) {
  .Call(`_cppallytest_cpp_typeof`, x)
}

test_str1 <- function(x) {
  .Call(`_cppallytest_test_str1`, x)
}

test_str2 <- function(x) {
  .Call(`_cppallytest_test_str2`, x)
}

test_null <- function() {
  .Call(`_cppallytest_test_null`)
}

test_sym <- function(x) {
  .Call(`_cppallytest_test_sym`, x)
}

test_sexp2 <- function(x) {
  .Call(`_cppallytest_test_sexp2`, x)
}

test_sexp3 <- function(x) {
  .Call(`_cppallytest_test_sexp3`, x)
}

test_coerce1 <- function(x) {
  .Call(`_cppallytest_test_coerce1`, x)
}

test_deduced_type <- function(x) {
  .Call(`_cppallytest_test_deduced_type`, x)
}

test_multiple_deduction <- function(x, y) {
  .Call(`_cppallytest_test_multiple_deduction`, x, y)
}

test_deduced_vec_type <- function(x) {
  .Call(`_cppallytest_test_deduced_vec_type`, x)
}

test_deduced_scalar_type <- function(x) {
  .Call(`_cppallytest_test_deduced_scalar_type`, x)
}

test_deduced_scalar_type2 <- function(x) {
  .Call(`_cppallytest_test_deduced_scalar_type2`, x)
}

test_identity <- function(x) {
  .Call(`_cppallytest_test_identity`, x)
}

test_template_null <- function(x) {
  .Call(`_cppallytest_test_template_null`, x)
}

test_scalar <- function(x, y) {
  .Call(`_cppallytest_test_scalar`, x, y)
}

test_rval_identity <- function(x) {
  .Call(`_cppallytest_test_rval_identity`, x)
}

scalar1 <- function(x) {
  .Call(`_cppallytest_scalar1`, x)
}

scalar2 <- function(x) {
  .Call(`_cppallytest_scalar2`, x)
}

vector1 <- function(x) {
  .Call(`_cppallytest_vector1`, x)
}

vector2 <- function(x) {
  .Call(`_cppallytest_vector2`, x)
}

scalar3 <- function(x, y) {
  .Call(`_cppallytest_scalar3`, x, y)
}

scalar4 <- function(x, y) {
  .Call(`_cppallytest_scalar4`, x, y)
}

test_sexp <- function(x) {
  .Call(`_cppallytest_test_sexp`, x)
}

test_sexp4 <- function(x) {
  .Call(`_cppallytest_test_sexp4`, x)
}

scalar_vec1 <- function(a, b) {
  .Call(`_cppallytest_scalar_vec1`, a, b)
}

scalar_vec2 <- function(a, b) {
  .Call(`_cppallytest_scalar_vec2`, a, b)
}

scalar_vec3 <- function(z, x, y, a) {
  .Call(`_cppallytest_scalar_vec3`, z, x, y, a)
}

test_mix2 <- function(a, b, c, d, e, f, g) {
  .Call(`_cppallytest_test_mix2`, a, b, c, d, e, f, g)
}

test_str3 <- function(x) {
  .Call(`_cppallytest_test_str3`, x)
}

test_str4 <- function(x) {
  .Call(`_cppallytest_test_str4`, x)
}

test_specialisation <- function(x) {
  .Call(`_cppallytest_test_specialisation`, x)
}

test_coerce <- function(x, ptype) {
  .Call(`_cppallytest_test_coerce`, x, ptype)
}

test_list_to_scalars <- function(x) {
  .Call(`_cppallytest_test_list_to_scalars`, x)
}

test_combine2 <- function(x, y) {
  .Call(`_cppallytest_test_combine2`, x, y)
}

test_dates2 <- function(x) {
  .Call(`_cppallytest_test_dates2`, x)
}

test_unique <- function(x) {
  .Call(`_cppallytest_test_unique`, x)
}

test_group_id <- function(x, order) {
  .Call(`_cppallytest_test_group_id`, x, order)
}

test_group_counts <- function(x, order) {
  .Call(`_cppallytest_test_group_counts`, x, order)
}

test_match <- function(x, y) {
  .Call(`_cppallytest_test_match`, x, y)
}

test_factor2 <- function(x) {
  .Call(`_cppallytest_test_factor2`, x)
}

test_n_unique <- function(x) {
  .Call(`_cppallytest_test_n_unique`, x)
}

test_copy <- function(x) {
  .Call(`_cppallytest_test_copy`, x)
}

test_identical <- function(x, y) {
  .Call(`_cppallytest_test_identical`, x, y)
}

test_multiline_template_add <- function(x, y) {
  .Call(`_cppallytest_test_multiline_template_add`, x, y)
}

test_multiline_template_add2 <- function(x, y) {
  .Call(`_cppallytest_test_multiline_template_add2`, x, y)
}

test_arithmetic <- function() {
  invisible(.Call(`_cppallytest_test_arithmetic`))
}

test_overflow <- function() {
  invisible(.Call(`_cppallytest_test_overflow`))
}

test_arithmetic_edge_cases <- function() {
  invisible(.Call(`_cppallytest_test_arithmetic_edge_cases`))
}

test_attrs <- function(x) {
  .Call(`_cppallytest_test_attrs`, x)
}

test_df <- function(cols) {
  .Call(`_cppallytest_test_df`, cols)
}

test_as_sym <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_sym`, a, b, c, d, e, f)
}

test_as_int <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_int`, a, b, c, d, e, f)
}

test_as_dbl <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_dbl`, a, b, c, d, e, f)
}

test_as_str <- function(a, b, c, d, e, f) {
  .Call(`_cppallytest_test_as_str`, a, b, c, d, e, f)
}

test_to_int <- function() {
  invisible(.Call(`_cppallytest_test_to_int`))
}

test_to_int64 <- function() {
  invisible(.Call(`_cppallytest_test_to_int64`))
}

test_to_double <- function() {
  invisible(.Call(`_cppallytest_test_to_double`))
}

test_to_uint <- function() {
  invisible(.Call(`_cppallytest_test_to_uint`))
}

test_to_r_size_t <- function() {
  invisible(.Call(`_cppallytest_test_to_r_size_t`))
}

test_to_bool <- function() {
  invisible(.Call(`_cppallytest_test_to_bool`))
}

test_to_r_int <- function() {
  invisible(.Call(`_cppallytest_test_to_r_int`))
}

test_to_r_int64 <- function() {
  invisible(.Call(`_cppallytest_test_to_r_int64`))
}

test_to_r_dbl <- function() {
  invisible(.Call(`_cppallytest_test_to_r_dbl`))
}

test_to_r_lgl <- function() {
  invisible(.Call(`_cppallytest_test_to_r_lgl`))
}

test_coerce_edge <- function() {
  invisible(.Call(`_cppallytest_test_coerce_edge`))
}

test_coerce_int64_to_int_overflow <- function() {
  invisible(.Call(`_cppallytest_test_coerce_int64_to_int_overflow`))
}

test_coerce_dbl_to_int_overflow <- function() {
  invisible(.Call(`_cppallytest_test_coerce_dbl_to_int_overflow`))
}

test_coerce_pos_inf_to_int <- function() {
  invisible(.Call(`_cppallytest_test_coerce_pos_inf_to_int`))
}

test_coerce_neg_inf_to_int <- function() {
  invisible(.Call(`_cppallytest_test_coerce_neg_inf_to_int`))
}

test_coerce_dbl_to_int64_overflow <- function() {
  invisible(.Call(`_cppallytest_test_coerce_dbl_to_int64_overflow`))
}

test_coerce_int_min_to_int <- function() {
  invisible(.Call(`_cppallytest_test_coerce_int_min_to_int`))
}

test_coerce_int64_min_to_int64 <- function() {
  invisible(.Call(`_cppallytest_test_coerce_int64_min_to_int64`))
}

test_date_accessors <- function() {
  invisible(.Call(`_cppallytest_test_date_accessors`))
}

test_date_add <- function() {
  invisible(.Call(`_cppallytest_test_date_add`))
}

test_date_rounding <- function() {
  invisible(.Call(`_cppallytest_test_date_rounding`))
}

test_datetime_accessors <- function() {
  invisible(.Call(`_cppallytest_test_datetime_accessors`))
}

test_date_conversions <- function() {
  invisible(.Call(`_cppallytest_test_date_conversions`))
}

test_datetime_add <- function() {
  invisible(.Call(`_cppallytest_test_datetime_add`))
}

test_datetime_rounding <- function() {
  invisible(.Call(`_cppallytest_test_datetime_rounding`))
}

test_date_edge_cases <- function() {
  invisible(.Call(`_cppallytest_test_date_edge_cases`))
}

test_factor1 <- function(x) {
  .Call(`_cppallytest_test_factor1`, x)
}

test_factor3 <- function(x) {
  .Call(`_cppallytest_test_factor3`, x)
}

reduce_sum <- function(x, na_rm) {
  .Call(`_cppallytest_reduce_sum`, x, na_rm)
}

reduce_max <- function(x, na_rm) {
  .Call(`_cppallytest_reduce_max`, x, na_rm)
}

reduce_cumulative_sum <- function(x, na_rm) {
  .Call(`_cppallytest_reduce_cumulative_sum`, x, na_rm)
}

reduce_gcd <- function(x) {
  .Call(`_cppallytest_reduce_gcd`, x)
}

pmap2_add <- function(x, y) {
  .Call(`_cppallytest_pmap2_add`, x, y)
}

pmap_add <- function(x) {
  .Call(`_cppallytest_pmap_add`, x)
}

test_names_inplace_mutation <- function() {
  .Call(`_cppallytest_test_names_inplace_mutation`)
}

test_names_stale_invalidation <- function() {
  .Call(`_cppallytest_test_names_stale_invalidation`)
}

test_names_set_attr_invalidation <- function() {
  .Call(`_cppallytest_test_names_set_attr_invalidation`)
}

test_names_growing <- function() {
  .Call(`_cppallytest_test_names_growing`)
}

test_names_sweep <- function() {
  .Call(`_cppallytest_test_names_sweep`)
}

test_names_shallow_copy_isolation <- function() {
  .Call(`_cppallytest_test_names_shallow_copy_isolation`)
}

test_names_empty <- function() {
  .Call(`_cppallytest_test_names_empty`)
}

test_names_roundtrip_after_grow <- function() {
  .Call(`_cppallytest_test_names_roundtrip_after_grow`)
}

vec_is_na <- function(x) {
  .Call(`_cppallytest_vec_is_na`, x)
}

test_nas <- function(x) {
  .Call(`_cppallytest_test_nas`, x)
}

test_na_types <- function() {
  .Call(`_cppallytest_test_na_types`)
}

test_protect_count_tracking <- function() {
  .Call(`_cppallytest_test_protect_count_tracking`)
}

test_protect_slot_reuse <- function() {
  .Call(`_cppallytest_test_protect_slot_reuse`)
}

test_protect_chunk_growth <- function() {
  .Call(`_cppallytest_test_protect_chunk_growth`)
}

test_protect_burst_reserve <- function() {
  .Call(`_cppallytest_test_protect_burst_reserve`)
}

test_rng_raw_hex <- function(seed, n) {
  .Call(`_cppallytest_test_rng_raw_hex`, seed, n)
}

test_rng_lemire_huge <- function(seed, n) {
  .Call(`_cppallytest_test_rng_lemire_huge`, seed, n)
}

test_rng_bounded_small <- function(seed, range, n) {
  .Call(`_cppallytest_test_rng_bounded_small`, seed, range, n)
}

test_rng_index <- function(seed, a, b, n) {
  .Call(`_cppallytest_test_rng_index`, seed, a, b, n)
}

test_rng_index_extremes <- function(seed) {
  .Call(`_cppallytest_test_rng_index_extremes`, seed)
}

test_rng_unif <- function(seed, a, b, n) {
  .Call(`_cppallytest_test_rng_unif`, seed, a, b, n)
}

test_rng_from_r <- function(n) {
  .Call(`_cppallytest_test_rng_from_r`, n)
}

test_rng_seed_from_r <- function() {
  .Call(`_cppallytest_test_rng_seed_from_r`)
}

test_rng_error_inside_with_rng <- function() {
  .Call(`_cppallytest_test_rng_error_inside_with_rng`)
}

test_by_value <- function(x) {
  .Call(`_cppallytest_test_by_value`, x)
}

test_by_lvalue_ref <- function(x) {
  .Call(`_cppallytest_test_by_lvalue_ref`, x)
}

test_by_rvalue_ref <- function(x) {
  .Call(`_cppallytest_test_by_rvalue_ref`, x)
}

test_by_const_lvalue_ref <- function(x) {
  .Call(`_cppallytest_test_by_const_lvalue_ref`, x)
}

test_temp_by_value <- function(x) {
  .Call(`_cppallytest_test_temp_by_value`, x)
}

test_temp_by_lvalue_ref <- function(x) {
  .Call(`_cppallytest_test_temp_by_lvalue_ref`, x)
}

test_temp_by_rvalue_ref <- function(x) {
  .Call(`_cppallytest_test_temp_by_rvalue_ref`, x)
}

test_temp_by_const_lvalue_ref <- function(x) {
  .Call(`_cppallytest_test_temp_by_const_lvalue_ref`, x)
}

test_rep_len <- function(x, n) {
  .Call(`_cppallytest_test_rep_len`, x, n)
}

test_rep <- function(x, times) {
  .Call(`_cppallytest_test_rep`, x, times)
}

test_rep_each <- function(x, each) {
  .Call(`_cppallytest_test_rep_each`, x, each)
}

test_replace_at <- function(x, where, with) {
  .Call(`_cppallytest_test_replace_at`, x, where, with)
}

test_order <- function(x, preserve_ties) {
  .Call(`_cppallytest_test_order`, x, preserve_ties)
}

test_sort <- function(x, preserve_ties) {
  .Call(`_cppallytest_test_sort`, x, preserve_ties)
}

test_range <- function(x, na_rm) {
  .Call(`_cppallytest_test_range`, x, na_rm)
}

test_sum <- function(x, na_rm) {
  .Call(`_cppallytest_test_sum`, x, na_rm)
}

test_mean <- function(x, na_rm) {
  .Call(`_cppallytest_test_mean`, x, na_rm)
}

test_var <- function(x, na_rm) {
  .Call(`_cppallytest_test_var`, x, na_rm)
}

test_subset <- function(x, i, invert) {
  .Call(`_cppallytest_test_subset`, x, i, invert)
}

test_find <- function(x, y) {
  .Call(`_cppallytest_test_find`, x, y)
}

test_valgrind <- function() {
  invisible(.Call(`_cppallytest_test_valgrind`))
}
