
---
title: "Getting started with cppally"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with cppally}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


To get started we will briefly show how to register a C++ function to R and go through the main scalar types that cppally offers.

## Setup 

## Registering R functions

To make a C++ function available to R we use the `[[cpp::register]]` tag.

``` cpp
#include <cppally.hpp>
using namespace cppally;

[[cpp::register]]
void hello_world(){
  print("Hello World!");
}
```

After tagging our functions we want to make them available to R. To do that we have a few routes.

### Registering C++ functions outside of a package context

After writing our hello world program in foo.cpp we can use `cpp_source()` to compile and register the function to R.

```r
cpp_source(file = "src/foo.cpp")
```

Now the function is available in R

``` r
> hello_world()
Hello World!
```

### Registering C++ functions inside a cppally-linked package

Since cppally is header-only, we can include the headers directly into our own package. 

### General steps to using cppally in a package

1. Create package (if you haven't already done so) using `usethis::create_tidy_package()`
2. Run `cppally::use_cppally()`
3. Run `cppally::load_all()`

This will automatically add the necessary package content needed to start working with cppally. For continuous development, use `cppally::load_all()` to compile and register cppally tagged functions, including our hello world function.


```r
hello_world()
Hello World!
```

**Note:** We aim to integrate cppally registration into the `devtools` framework for ease-of-use.

## C++ types

cppally offers a rich set of R types in C++ that are NA-aware. This means that common arithmetic and logical operations will account for `NA` in a similar fashion to R.

### r_lgl

cppally's scalar version of `logical`, `r_lgl` can represent true, false or NA.

``` cpp
r_lgl r_true
r_lgl r_false
r_lgl r_na

// Alternatively

r_lgl true_value(true);
r_lgl false_value(false);
r_lgl na<r_lgl>();
```

Logical operators work just like in R

``` cpp
#include <cppally.hpp>
using namespace cppally;

void lgl_ops(){
  r_true || r_false // true
  r_true && r_false // false
  r_na || r_true    // true
  r_na && r_true    // NA
  r_na && r_false   // false
  r_na || r_na      // NA
  r_na && r_na      // NA
}
```

**Using `r_lgl`** in if-statements

For type-safety reasons `r_lgl` cannot be implicitly converted to `bool` except in if-statements. When an `r_lgl` is cast to a `bool`, the value is checked to be `NA` and throws an error if it is. `NA` values must be handled separately just like in R.

``` cpp
#include <cppally.hpp>
using namespace cppally;

r_lgl condition = r_true;

void lgls(){

  // true is printed
  
  if (condition){
    print("true");
  } else {
    print("false");
  }
  
  r_lgl condition = r_na;
  
  // DONT DO THIS - an error is thrown!
  if (condition){
    print("true");
  } else {
    print("false");
  }
  
  // DO THIS instead
  if (is_na(condition)){
    print("na")
  } else if (condition){
    print("true");
  } else {
    print("false");
  }
  
  // Or alternatively without accounting for NA
  if (condition.is_true()){ // identical to R `isTRUE`
    print("true");
  } else {
    print("not true");
  }

}
```

All cppally scalar types are implemented as structs that contain the underlying C/C++ types as well as other member functions.

| cppally type    | Description                 | Implicitly converts to           |
| :------------ | --------------------------- | :------------------------------- |
| `r_lgl`       | Scalar logical              | `bool` **only** in if-statements |
| `r_int`       | Scalar integer              | `int`                            |
| `r_int64`     | Scalar 64-bit integer       | `int64_t`                        |
| `r_dbl`       | Scalar double               | `double`                         |
| `r_str`       | Scalar string               | `SEXP`                           |
| `r_cplx`      | Scalar double complex       | `std::complex<double>`           |
| `r_raw`       | Scalar raw                  | `unsigned char`                  |
| `r_sym`       | Symbol                      | `SEXP`                           |
| `r_date` [^1] | Scalar date                 | `double`                         |
| `r_psxct`     | Scalar date-time            | `double`                         |
| `r_sexp`      | Generic R object (SEXP)[^2] | `SEXP`                           |

[^1]: Unlike `r_str` which is composite and holds an `r_sexp` member, `r_date` and `r_psxct` instead inherit directly from `r_dbl`. This means that they can implicitly convert to `r_dbl`

[^2]: `r_sexp` represents a generic R object which can include cppally vectors. We will explain how to disambiguate `r_sexp` later which is most useful when working with lists and data frames

`NA` values can be accessed via the template function `na<T>`

### C++ NA values and their R C API equivalents

| Type                     | Value                 | R C API Value  | constexpr?[^3] |
| ------------------------ | --------------------- | -------------- | -------------- |
| `r_lgl`                  | `na<r_lgl>()`/`r_na`  | `NA_LOGICAL`   | Yes            |
| `r_int`                  | `na<r_int>()`         | `NA_INTEGER`   | Yes            |
| `r_int64`                | `na<r_int64>()`       | Not applicable | Yes            |
| `r_dbl`                  | `na<r_dbl>()`         | `NA_REAL`      | Yes            |
| `r_str`                  | `na<r_str>()`         | `NA_STRING`    | No             |
| `r_cplx`                 | `na<r_cplx>()`        | Not applicable | Yes            |
| `r_sym`                  | Not applicable        | Not applicable | No             |
| `r_sexp`[^4]<br><br><br> | `na<r_sexp>`/`r_null` | `R_NilValue`   | No             |

[^3]: In C++ constexpr is used as a keyword to declare that it's possible to evaluate values at compile-time, meaning they are known before any code is run by the user. Since `r_na` internally is the largest possible `int` which does not change and is known a priori, it is therefore a compile-time constant.
[^4]: Having an `NA` sentinel for `r_sexp` is very useful when writing templates involving vectors. For this reason the `NA` sentinel is `r_null`. This doesn't mean `is_na(r_null)` is true, and is intentionally not true because it is not a scalar and therefore cannot be `NA`.  As `r_null` represents the absence of a tangible R object, it can be thought of as a zero-length object and since all `NA` values are represented as length-1 vectors (in R), `is_na(r_null)` should not return true.

### Accessing the underlying types and values

While it is generally recommended not to access the underlying objects, you can do so with `unwrap()` which returns the underlying C/C++ value. For example, `unwrap(r_int(5))` will return an `int` of value `5`. 

To access the underlying type, use `unwrap_t<>` which always aligns with `unwrap()`

The main reason for wanting to access underlying values would likely be optimisation and so `unwrap()` and `unwrap_t` allow this to be done consistently.

Example usage

```cpp
#include <cppally.hpp>
using namespace cppally;

using primitive_t = unwrap_t<r_int>;
r_int x{10};
primitive_t y = unwrap(x);
return x + y; // answer = 20
```


## Vectors

cppally vectors are templated and can be thought of as containers of the scalar elements we talked about previously like `r_int`, `r_dbl`, etc.

We can create vectors like so

``` cpp
#include <cppally.hpp>
using namespace cppally;

// Integer vector of size n
r_vec<r_int> new_integer_vector(int n){
  r_vec<r_int> int_vctr(n);
  return int_vctr;
}

// Usage
r_vec<r_int> new_filled_integer_vector(int n, r_int fill_value){
  r_vec<r_int> out(n, fill_value); // Fills all values with fill_value
  return out;
}

// You can also use fill() instead
r_vec<r_int> new_filled_integer_vector2(int n, r_int fill_value){
  r_vec<r_int> out(n);
  out.fill(0, r_int(n), fill_value); // Fill n-elements from 0 with fill_value
  return out;
}
```

## inline vectors

To create inline vectors, use `make_vec<>`

``` cpp
#include <cppally.hpp>
using namespace cppally;

r_vec<r_dbl> foo(){
  return make_vec<r_dbl>(1, 1.5, 2, na<r_dbl>());
}
```

We can add names on the fly with `arg()`

``` cpp
#include <cppally.hpp>
using namespace cppally;

r_vec<r_dbl> bar(){
  return make_vec<r_dbl>(
    arg("first") = 1, 
    arg("second") = 1.5, 
    arg("third") = 2, 
    arg("last") = na<r_dbl>()
  );
}
```

In R a list is a generic vector, so cppally defines lists as `r_vec<r_sexp>`, a vector of the generic type `r_sexp`.

``` cpp
#include <cppally.hpp>
using namespace cppally;

r_vec<r_sexp> cpp_list(){
  return make_vec<r_sexp>(1, 2, 3); // list(1, 2, 3)
}
```

Here is how to create a list of all cppally vectors of length 0

``` cpp
#include <cppally.hpp>
using namespace cppally;

r_vec<r_sexp> all_vectors(){
  return make_vec<r_sexp>(
    arg("logical") = r_vec<r_lgl>(),
    arg("integer") = r_vec<r_int>(),
    arg("integer64") = r_vec<r_int64>(), // Requires bit64
    arg("double") = r_vec<r_dbl>(),
    arg("character") = r_vec<r_str>(),
    arg("character") = r_vec<r_str_view>(),
    arg("raw") = r_vec<r_raw>(),
    arg("date") = r_vec<r_date>(),
    arg("date-time") = r_vec<r_psxct>(),
    arg("list") = r_vec<r_sexp>()
  );
}
```

## Concepts

One of the most powerful features of C++20 are concepts. These allow users to write human-readable templates and constraints. For example r_math.h uses the `RMathType` concept for custom math functions to ensure that only types that support math (like `r_dbl`) are allowed as arguments to those functions. This promotes type-safety and signals to the user what types are allowed.

Let's look at an example in r_math.h

``` cpp
template <RMathType T>
inline constexpr T abs(T x){
  return is_na(x) ? x : T{internal::cpp_abs(unwrap(x))};
}
```

The top-line `template <RMathType T>` declares a template that encapsulates `T`, an `RMathType`.
The input is `x` is of type `T`, an `RMathType` and the return value is also `T`

`T{}` is then used to construct the `RMathType` object from the absolute result.

For info, the `RMathType` concept contains the following types:
`r_lgl`, `r_int`, `r_int64` and `r_dbl`

For a list of all cppally concepts, please see the **Annex**

## Coercion

To coerce from one scalar to another we can use `as<T>`

``` cpp
#include <cppally.hpp>
using namespace cppally;

[[cpp::register]]
r_int double_to_int(r_dbl x){
  return as<r_int>(x);
}
```

```r
double_to_int(pi)
[1] 3
double_to_int(NA_real_)
[1] NA
```

We can also coerce from one vector type to another

``` cpp
#include <cppally.hpp>
using namespace cppally;

// Coerces NA correctly
[[cpp::register]]
r_vec<r_int> to_int_vec(r_vec<r_dbl> x){
  return as<r_vec<r_int>>(x);
}
```

```r
> to_int_vec(c(0, 1.5, NA))
[1]  0  1 NA
```

Since `as<T>` is extremely flexible, we can also coerce from a scalar to a vector or vice versa

``` cpp
#include <cppally.hpp>
using namespace cppally;

[[cpp::register]]
r_vec<r_sexp> coercions(){
  r_dbl a(4.2);
  r_vec<r_dbl> b = make_vec<r_dbl>(2.5); // Vector containing 2.5
  return make_vec<r_sexp>(
    as<r_vec<r_int>>(a),
    as<r_int>(a),
    as<r_int>(b),
    as<r_dbl>(b)
  );
}
```

```r
> coercions()
[[1]]
[1] 4

[[2]]
[1] 4

[[3]]
[1] 2

[[4]]
[1] 2.5
```
## Strings

cppally provides the useful string type `r_str`

We can create R strings easily

``` cpp
r_str hello_str("hello");
```

To get a C or C++ string, use the members `c_str()` and `cpp_str()` respectively

``` cpp
hello_str.c_str() // C-style string
hello_str.cpp_str() // C++ style string
```

## Symbols

Symbols are assumed to always be protected and so don't have the same overhead issues that `r_str` has. We can easily create symbols using the `const char*` constructor

``` cpp
r_sym hello_sym("hello");
```

### Lists

`r_sexp` is generally interpreted as an "element of a list" since lists are defined as `r_vec<r_sexp>`, a vector that holds generic `r_sexp` elements. We can use `visit_vector` to disambiguate the type, i.e. from an `r_sexp` to an `r_vec<r_int>` in the case that the element is an integer vector. This must be used in a C++ lambda context.

**Example:** using `visit_vector()` to calculate list lengths

``` cpp
#include <cppally.hpp>
using namespace cppally;

[[cpp::register]]

r_vec<r_int> cpp_lengths(const r_vec<r_sexp>& x){
  r_size_t n = x.length();
  r_vec<r_int> out(n); // Initialise lengths vector
    for (r_size_t i = 0; i < n; ++i){
       visit_vector(x.view(i), [&](const auto& vec) {
         out.set(i, as<r_int>(vec.length()));
    });
    }
  return out;
}
```

**visit_sexp**

This allows one to visit more types than just vectors, including factors, symbols and (soon to implemented) data frames. When an object's type can't be deduced into a distinct type, `r_sexp` is returned. 

**Example:** Using `visit_sexp()` to calculate list lengths

```cpp
#include <cppally.hpp>
using namespace cppally;

[[cpp::register]]
r_vec<r_int> cpp_lengths2(const r_vec<r_sexp>& x){
    r_size_t n = x.length();
    r_vec<r_int> out(n); // Initialise lengths vector
      for (r_size_t i = 0; i < n; ++i){
         visit_sexp(x.view(i), [&](const auto& vec) {
         using vec_t = decltype(vec);
         if constexpr (!RVector<vec_t>){
             abort("Input must be an RVector");
         } else {
             out.set(i, as<r_int>(vec.length()));
         }
      });
      }
    return out;
}
```

## Factors

We can create a factor via `r_factors()`

```cpp
#include <cppally.hpp>
using namespace cppally;

[[cpp::register]]
r_factors new_factor(r_vec<r_str> x){
	return r_factors(x);
}
```

```r
 new_factor(letters)
 a b c d e f g h i j k l m n o p q r s t u v w x y z
Levels: a b c d e f g h i j k l m n o p q r s t u v w x y z
```

In cppally, like R, factors are not vectors and therefore do not satisfy the RVector concept. To access the underlying integer codes vector, use the public `codes()` member function

```cpp
#include <cppally.hpp>
using namespace cppally;

static_assert(!RVector<r_factors>);

[[cpp::register]]
r_vec<r_int> factor_codes(r_factors x){
	return x.codes();
}
```

```r
letter_fct <- new_factor(letters)

letter_fct |> 
    factor_codes()
1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
```


## Attributes

Attributes can be manipulated via functions defined in the attr namespace.

- `get_attrs()` - Returns a list of attributes (possibly `r_vec<r_sexp>(r_null)`)
- `set_attrs()` - Sets attributes to ones specified. Note: replaces any current attributes
- `clear_attrs()` - Removes all attributes
- `set_attr()` - Set a single attribute
- `get_attr()` - Get a single attribute
- `inherits1()` - Does object inherit class?
- `inherits_any()` - Does object inherit at least one of the specified classes?
- `inherits_all()` - Does object inherit all of the specified classes?
- `modify_attrs()` - Modifies current attributes but doesn't remove any existing ones

## Sugar functions

cppally also offers many useful and high-performance common functions in cppally/sugar

- `n_unique()` - Fast number of unique values. Faster than `unique(x).length()` as it doesn't need to allocate a unique vector

- `unique()` - Like R's `unique()` but with a `sort` argument to return sorted unique values

- `identical()` - A very fast identical function that works for scalars and vectors. Use this for exact equality of any scalar or vector.

- `match()` - Like R's match, but also faster

- `sequences()` - Like `sequence()` but it returns a list of sequences and also works with doubles. 

- `order()` - Like base R's order but it internally uses a hybrid approach of ska sort, count sorting, quick sort, etc.

- `make_groups()` - An advanced function that returns a struct containing group IDs and number of groups (i.e number of unique group IDs). The `groups` struct contains the following members:
	- r_vec<r_int> ids - The cached group IDs
	- int n_groups - Number of unique groups
	- bool ordered - Do the group IDs specify a sorting order, or are they by order-of-first-appearance?
	- bool sorted - Are the group IDs sorted? (This can also be true for order-of-first-appearance IDs)
	- r_vec<r_int> start() - Returns an r_vec<r_int>(n_groups) vector of start locations of each unique group, signifying the location in the data at which each group initially appeared
	- r_vec<r_int> counts() - Returns an r_vec<r_int>(n_groups) vector of frequency counts of each unique group
	- r_vec<r_int> order() - Returns an r_vec<r_int>(ids.length()) order vector. This is a 0-indexed permutation vector that can be used to return sorted group IDs

- `recycle()` - Recycles supplied vectors to common length

- `r_vec<T>::subset()` - Fast subsetting of vectors

**Scalar math functions**

There are a rich suite of math functions. Some examples include `min()`, `max()`, `round()`, `log()`, `floor()`, `ceiling()` and more.

**Stats sugar functions**

Some statistical summary functions that are all very highly optimised for speed
- `sum()` - Sum of values
- `range()` - Min and max range of values
- `abs()` - Computes absolute values (there is also a scalar version)
- `var()` and `sd()` - Variance and standard deviation
- `gcd()` - Greatest common divisor
- `lcm()` - Lowest common multiple


## templates

### Registering templates

To register a C++ template to R, one must declare the `[[cpp::register]]` target after the template declaration. Also worth noting that templates must be defined in header files instead of cpp files.

``` cpp
#pragma once

#include <cppally.hpp>
using namespace cppally;

template <RStringType T>
[[cpp::register]]
void my_print(T x){
  print(x.c_str());
}
```

### Explicit instantiation from R

While most templates can be registered to R, explicit instantiation (from R) is impossible. 

```cpp
template <RScalar T>
[[cpp::register]]
T scalar_init(){
	return T();
}
```

In C++ you would call this template like so

```cpp
scalar_init<r_int>();
```

In R we naturally can't do this so one alternative is to define a prototype argument to allow argument deduction from that

```cpp
template <typename T>
[[cpp::register]]
T scalar_init(T ptype){
	return T();
}
```

And then in R

```r
lapply(iris, scalar_init)

$Sepal.Length
numeric(0)

$Sepal.Width
numeric(0)

$Petal.Length
numeric(0)

$Petal.Width
numeric(0)

$Species
factor()
Levels:
```

Generally speaking most templates won't need explicit instantiation and we can rely on automatic deduction

```cpp
template <RVector T>
[[cpp::register]]
int cpp_length(T vec){
	return vec.length();
}
```

```r
cpp_length(letters)
[1] 26
```

`RVector` is a concept that includes all R atomic vectors (including 64-bit integer) and lists. As it was specified as the template argument type, if we supply an argument that doesn't satisfy RVector (i.e isn't a vector), then cppally's R dispatch code will catch this and return an error.

```r
cpp_length(iris$Species)

Error: No matching template instantiation found for input types
```

For non-template functions the input type must be specified

```cpp
[[cpp::register]]
r_dbl add_half(r_dbl x){
  return x + 0.5;
}
```

```r
add_half(1.5) # Double
[1] 2
```

We can even supply an integer (`r_int`) because the integer is coerced to a double (`r_dbl`) internally via `as<r_dbl>`

```r
add_half(1L) # Integer works too
[1] 1.5
```

The internal generated code looks like this in src/cppally.cpp

```cpp

// readme.h
r_dbl add_half(r_dbl x);
extern "C" SEXP _cppally_add_half(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(add_half(as<r_dbl>(x)));
  END_CPPALLY
}
```

Notice the `as<r_dbl>(x)`, this is the line that coerces our integer to a double correctly

What happens if we supply an input that can't be coerced to an `r_dbl`?

```cpp
add_half("A")

Error: Implicit NA coercion detected from r_str to r_dbl, please ensure data can be coerced without complete loss of information
```

Thankfully due to the way cppally is strict about completely lossy coercions, an informative error is thrown.

### Symbols in R-registered templates

`r_sym` is unsupported in templates when it's part of a template argument but is supported when the argument is explicitly an `r_sym`.

```cpp
[[cpp::register]]
r_str symbol_to_string(r_sym x){
	return as<r_str>(x);
}
```

```r
hello_world_symbol <- as.symbol("hello world!")
hello_world_symbol
`hello world!`
symbol_to_string(hello_world_symbol)
[1] "hello world!"
```
### Annex

### All core cppally concepts

- RIntegerType - Includes `r_lgl`, `r_int`, `r_int64`

- RMathType - Includes `r_lgl`, `r_int`, `r_int64` and `r_dbl`

- RStringType - Includes `r_str` and `r_str_view`

- RScalar - Includes all cppally specific scalar types

- RVal - Includes anything a cppally vector (`r_vec<>`) can contain: RScalar +`r_sexp`

- RVector - Includes `r_vec<T>` where `T` is an RVal
- RTimeType - Includes `r_date` and `r_psxct`
- RNumericType - Numeric types, including RMathType and RTimeType
- RSortableType - Includes RNumericType and RStringType (strings can also be sorted)
- RAtomicVector - A vector that contains RScalar elements
- CppallyType - Any R type defined by R, including RVal, RVector, RFactor, RDataFrame, RSymbol
- CppType - Anything that is not an CppallyType
- CastableToRScalar - Anything that can be constructed or cast into an RScalar (which also includes RScalar)
- CastableToRVal (**questioning**) - Anything that can be constructed or cast into an RVal. This is more complicated as it includes vectors, factors and data frames which can be cast to `r_sexp`

Other useful type traits

- `unwrap_t` - Returns the underlying unwrapped type
- `as_r_scalar_t` - Returns the equivalent RScalar type
- `as_r_val_t` - Returns the equivalent RVal type
- `common_r_t` - Returns the common RVal type between 2 types. Generally this is a hierarchy where the common type is the type that both values can be coerced to without complete loss of information
