// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <R_ext/Visibility.h>
#include "readme.h"
#include "test.h"
#include "test_nas.h"
#include "test_sort.h"
#include "test_stats.h"
#include "test_subset.h"

using namespace cppally;
using internal::cpp_to_sexp;
using internal::dispatch_template_impl;

// readme.h
extern "C" SEXP _cppallytest_scalar_init(SEXP ptype) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP ptype_internal) -> decltype(cpp_to_sexp(::scalar_init(as<T>(ptype_internal)))) {
        return cpp_to_sexp(::scalar_init(as<T>(ptype_internal)));
    },
    ptype
  );
  END_CPPALLY
}
// readme.h
r_int64 as_int64(r_int x);
extern "C" SEXP _cppallytest_as_int64(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::as_int64(as<r_int>(x)));
  END_CPPALLY
}
// readme.h
r_size_t as_r_size_t(r_int x);
extern "C" SEXP _cppallytest_as_r_size_t(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::as_r_size_t(as<r_int>(x)));
  END_CPPALLY
}
// readme.h
extern "C" SEXP _cppallytest_cpp_length(SEXP vec) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP vec_internal) -> decltype(cpp_to_sexp(::cpp_length(as<T>(vec_internal)))) {
        return cpp_to_sexp(::cpp_length(as<T>(vec_internal)));
    },
    vec
  );
  END_CPPALLY
}
// readme.h
r_dbl add_half(r_dbl x);
extern "C" SEXP _cppallytest_add_half(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::add_half(as<r_dbl>(x)));
  END_CPPALLY
}
// readme.h
r_str symbol_to_string(r_sym x);
extern "C" SEXP _cppallytest_symbol_to_string(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::symbol_to_string(as<r_sym>(x)));
  END_CPPALLY
}
// readme.h
r_factors new_factor(r_vec<r_str> x);
extern "C" SEXP _cppallytest_new_factor(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::new_factor(as<r_vec<r_str>>(x)));
  END_CPPALLY
}
// readme.h
r_vec<r_int> factor_codes(r_factors x);
extern "C" SEXP _cppallytest_factor_codes(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::factor_codes(as<r_factors>(x)));
  END_CPPALLY
}
// readme.h
r_vec<r_int> cpp_lengths(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_cpp_lengths(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_lengths(as<const r_vec<r_sexp>&>(x)));
  END_CPPALLY
}
// readme.h
r_vec<r_int> cpp_lengths2(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_cpp_lengths2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_lengths2(as<const r_vec<r_sexp>&>(x)));
  END_CPPALLY
}
// readme.h
r_int double_to_int(r_dbl x);
extern "C" SEXP _cppallytest_double_to_int(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::double_to_int(as<r_dbl>(x)));
  END_CPPALLY
}
// readme.h
r_vec<r_int> to_int_vec(r_vec<r_dbl> x);
extern "C" SEXP _cppallytest_to_int_vec(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::to_int_vec(as<r_vec<r_dbl>>(x)));
  END_CPPALLY
}
// readme.h
r_vec<r_sexp> coercions();
extern "C" SEXP _cppallytest_coercions() {
  BEGIN_CPPALLY
  return cpp_to_sexp(::coercions());
  END_CPPALLY
}
// readme.h
int cpp_na_count(r_vec<r_str> x);
extern "C" SEXP _cppallytest_cpp_na_count(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_na_count(as<r_vec<r_str>>(x)));
  END_CPPALLY
}
// readme.h
int C_na_count(SEXP x);
extern "C" SEXP _cppallytest_C_na_count(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::C_na_count(as<SEXP>(x)));
  END_CPPALLY
}
// readme.h
int cpp_fast_na_count(r_vec<r_str_view> x);
extern "C" SEXP _cppallytest_cpp_fast_na_count(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_fast_na_count(as<r_vec<r_str_view>>(x)));
  END_CPPALLY
}
// readme.h
int cpp_fast_na_count_v2(r_vec<r_str> x);
extern "C" SEXP _cppallytest_cpp_fast_na_count_v2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_fast_na_count_v2(as<r_vec<r_str>>(x)));
  END_CPPALLY
}
// test.cpp
void cpp_set_threads(int n);
extern "C" SEXP _cppallytest_cpp_set_threads(SEXP n) {
  BEGIN_CPPALLY
  ::cpp_set_threads(as<int>(n));
  return R_NilValue;
  END_CPPALLY
}
// test.cpp
r_int cpp_get_threads();
extern "C" SEXP _cppallytest_cpp_get_threads() {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_get_threads());
  END_CPPALLY
}
// test.cpp
r_int cpp_get_max_threads();
extern "C" SEXP _cppallytest_cpp_get_max_threads() {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_get_max_threads());
  END_CPPALLY
}
// test.cpp
r_str cpp_typeof(SEXP x);
extern "C" SEXP _cppallytest_cpp_typeof(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::cpp_typeof(as<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
SEXP test_identity2(SEXP x);
extern "C" SEXP _cppallytest_test_identity2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_identity2(as<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_str> test_str1(r_str x);
extern "C" SEXP _cppallytest_test_str1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_str1(as<r_str>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_str_view> test_str2(r_str_view x);
extern "C" SEXP _cppallytest_test_str2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_str2(as<r_str_view>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_as_date(SEXP x);
extern "C" SEXP _cppallytest_test_as_date(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_as_date(as<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_construct_date(SEXP x);
extern "C" SEXP _cppallytest_test_construct_date(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_construct_date(as<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_as_date2(r_vec<r_date> x);
extern "C" SEXP _cppallytest_test_as_date2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_as_date2(as<r_vec<r_date>>(x)));
  END_CPPALLY
}
// test.cpp
r_sexp test_null();
extern "C" SEXP _cppallytest_test_null() {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_null());
  END_CPPALLY
}
// test.cpp
r_sym test_sym(r_sym x);
extern "C" SEXP _cppallytest_test_sym(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_sym(as<r_sym>(x)));
  END_CPPALLY
}
// test.cpp
r_sexp test_sexp2(r_sexp x);
extern "C" SEXP _cppallytest_test_sexp2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_sexp2(as<r_sexp>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_sexp> test_sexp3(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_test_sexp3(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_sexp3(as<r_vec<r_sexp>>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_int> test_coerce1(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_test_coerce1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_coerce1(as<const r_vec<r_sexp>&>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_dates1(r_vec<r_date> x);
extern "C" SEXP _cppallytest_test_dates1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_dates1(as<r_vec<r_date>>(x)));
  END_CPPALLY
}
// test.cpp
r_str test_tz(r_vec<r_psxct> x);
extern "C" SEXP _cppallytest_test_tz(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_tz(as<r_vec<r_psxct>>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_int> test_lengths(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_test_lengths(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_lengths(as<const r_vec<r_sexp>&>(x)));
  END_CPPALLY
}
// test.cpp
r_lgl test_lgl();
extern "C" SEXP _cppallytest_test_lgl() {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_lgl());
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_deduced_type(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_deduced_type(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiple_deduction(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_multiple_deduction(as<T>(x_internal), as<T>(y_internal)))) {
        return cpp_to_sexp(::test_multiple_deduction(as<T>(x_internal), as<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_vec_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_deduced_vec_type(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_deduced_vec_type(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_scalar_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_deduced_scalar_type(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_deduced_scalar_type(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_scalar_type2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_deduced_scalar_type2(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_deduced_scalar_type2(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_identity(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_identity(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_identity(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_template_null(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_template_null(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_template_null(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_scalar(as<int>(x_internal), as<T>(y_internal)))) {
        return cpp_to_sexp(::test_scalar(as<int>(x_internal), as<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_scalar2(as<r_int>(x_internal), as<T>(y_internal)))) {
        return cpp_to_sexp(::test_scalar2(as<r_int>(x_internal), as<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar3(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_scalar3(as<r_int>(x_internal), as<T>(y_internal)))) {
        return cpp_to_sexp(::test_scalar3(as<r_int>(x_internal), as<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_rval_identity(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_rval_identity(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_rval_identity(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar1(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::scalar1(as<T>(x_internal)))) {
        return cpp_to_sexp(::scalar1(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::scalar2(as<T>(x_internal)))) {
        return cpp_to_sexp(::scalar2(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_vector1(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::vector1(as<r_vec<T>>(x_internal)))) {
        return cpp_to_sexp(::vector1(as<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_vector2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::vector2(as<T>(x_internal)))) {
        return cpp_to_sexp(::vector2(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar3(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::scalar3(as<T>(x_internal), as<T>(y_internal)))) {
        return cpp_to_sexp(::scalar3(as<T>(x_internal), as<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar4(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::scalar4(as<T>(x_internal), as<U>(y_internal)))) {
        return cpp_to_sexp(::scalar4(as<T>(x_internal), as<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_sexp(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_sexp(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_sexp(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_sexp4(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_sexp4(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_sexp4(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec1(SEXP a, SEXP b) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_sexp(::scalar_vec1(as<r_vec<T>>(a_internal), as<T>(b_internal)))) {
        return cpp_to_sexp(::scalar_vec1(as<r_vec<T>>(a_internal), as<T>(b_internal)));
    },
    a, b
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec2(SEXP a, SEXP b) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_sexp(::scalar_vec2(as<r_vec<T>>(a_internal), as<U>(b_internal)))) {
        return cpp_to_sexp(::scalar_vec2(as<r_vec<T>>(a_internal), as<U>(b_internal)));
    },
    a, b
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec3(SEXP z, SEXP x, SEXP y, SEXP a) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 4, std::array<int, 4>{0, 0, 1, 1}>(
    []<typename T, typename U>(SEXP z_internal, SEXP x_internal, SEXP y_internal, SEXP a_internal) -> decltype(cpp_to_sexp(::scalar_vec3(as<r_vec<T>>(z_internal), as<T>(x_internal), as<U>(y_internal), as<r_vec<U>>(a_internal)))) {
        return cpp_to_sexp(::scalar_vec3(as<r_vec<T>>(z_internal), as<T>(x_internal), as<U>(y_internal), as<r_vec<U>>(a_internal)));
    },
    z, x, y, a
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_mix2(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f, SEXP g) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 7, std::array<int, 7>{0, -1, 0, -1, 0, 0, 1}>(
    []<typename T, typename V>(SEXP a_internal, SEXP b_internal, SEXP c_internal, SEXP d_internal, SEXP e_internal, SEXP f_internal, SEXP g_internal) -> decltype(cpp_to_sexp(::test_mix2(as<r_vec<T>>(a_internal), as<double>(b_internal), as<T>(c_internal), as<int>(d_internal), as<T>(e_internal), as<T>(f_internal), as<V>(g_internal)))) {
        return cpp_to_sexp(::test_mix2(as<r_vec<T>>(a_internal), as<double>(b_internal), as<T>(c_internal), as<int>(d_internal), as<T>(e_internal), as<T>(f_internal), as<V>(g_internal)));
    },
    a, b, c, d, e, f, g
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_str3(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_str3(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_str3(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_str4(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_str4(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_str4(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_specialisation(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_specialisation(as<r_vec<T>>(x_internal)))) {
        return cpp_to_sexp(::test_specialisation(as<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_coerce(SEXP x, SEXP ptype) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP ptype_internal) -> decltype(cpp_to_sexp(::test_coerce(as<r_vec<T>>(x_internal), as<U>(ptype_internal)))) {
        return cpp_to_sexp(::test_coerce(as<r_vec<T>>(x_internal), as<U>(ptype_internal)));
    },
    x, ptype
  );
  END_CPPALLY
}
// test.h
SEXP test_list_to_scalars(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_test_list_to_scalars(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_list_to_scalars(as<r_vec<r_sexp>>(x)));
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_combine2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_combine2(as<T>(x_internal), as<T>(y_internal)))) {
        return cpp_to_sexp(::test_combine2(as<T>(x_internal), as<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_dates2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_dates2(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_dates2(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_unique(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_unique(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_unique(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_seqs(SEXP size, SEXP from, SEXP by) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{-1, 0, 1}>(
    []<typename U, typename V>(SEXP size_internal, SEXP from_internal, SEXP by_internal) -> decltype(cpp_to_sexp(::test_seqs(as<r_vec<r_int>>(size_internal), as<r_vec<U>>(from_internal), as<r_vec<V>>(by_internal)))) {
        return cpp_to_sexp(::test_seqs(as<r_vec<r_int>>(size_internal), as<r_vec<U>>(from_internal), as<r_vec<V>>(by_internal)));
    },
    size, from, by
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_group_id(SEXP x, SEXP order) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_sexp(::test_group_id(as<T>(x_internal), as<bool>(order_internal)))) {
        return cpp_to_sexp(::test_group_id(as<T>(x_internal), as<bool>(order_internal)));
    },
    x, order
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_group_counts(SEXP x, SEXP order) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_sexp(::test_group_counts(as<T>(x_internal), as<bool>(order_internal)))) {
        return cpp_to_sexp(::test_group_counts(as<T>(x_internal), as<bool>(order_internal)));
    },
    x, order
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_match(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_match(as<r_vec<T>>(x_internal), as<r_vec<T>>(y_internal)))) {
        return cpp_to_sexp(::test_match(as<r_vec<T>>(x_internal), as<r_vec<T>>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_factor2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_factor2(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_factor2(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_n_unique(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_n_unique(as<T>(x_internal)))) {
        return cpp_to_sexp(::test_n_unique(as<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
SEXP test_copy(SEXP x);
extern "C" SEXP _cppallytest_test_copy(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_copy(as<SEXP>(x)));
  END_CPPALLY
}
// test.h
bool test_identical(SEXP x, SEXP y);
extern "C" SEXP _cppallytest_test_identical(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_identical(as<SEXP>(x), as<SEXP>(y)));
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiline_template_add(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_multiline_template_add(as<T>(x_internal), as<U>(y_internal)))) {
        return cpp_to_sexp(::test_multiline_template_add(as<T>(x_internal), as<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiline_template_add2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_multiline_template_add2(as<T>(x_internal), as<U>(y_internal)))) {
        return cpp_to_sexp(::test_multiline_template_add2(as<T>(x_internal), as<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_attrs.cpp
r_vec<r_sexp> test_attrs(SEXP x);
extern "C" SEXP _cppallytest_test_attrs(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_attrs(as<SEXP>(x)));
  END_CPPALLY
}
// test_attrs.cpp
r_vec<r_sexp> test_df(r_vec<r_sexp> cols);
extern "C" SEXP _cppallytest_test_df(SEXP cols) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_df(as<r_vec<r_sexp>>(cols)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_sym(SEXP a, r_str b, r_dbl c, r_sym d, r_vec<r_str> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_sym(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_as_sym(as<SEXP>(a), as<r_str>(b), as<r_dbl>(c), as<r_sym>(d), as<r_vec<r_str>>(e), as<r_vec<r_dbl>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_int(SEXP a, r_str b, r_dbl c, r_sym d, r_vec<r_str> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_int(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_as_int(as<SEXP>(a), as<r_str>(b), as<r_dbl>(c), as<r_sym>(d), as<r_vec<r_str>>(e), as<r_vec<r_dbl>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_dbl(SEXP a, r_str b, r_int c, r_sym d, r_vec<r_str> e, r_vec<r_int> f);
extern "C" SEXP _cppallytest_test_as_dbl(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_as_dbl(as<SEXP>(a), as<r_str>(b), as<r_int>(c), as<r_sym>(d), as<r_vec<r_str>>(e), as<r_vec<r_int>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_str(SEXP a, r_int b, r_dbl c, r_sym d, r_vec<r_int> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_str(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_as_str(as<SEXP>(a), as<r_int>(b), as<r_dbl>(c), as<r_sym>(d), as<r_vec<r_int>>(e), as<r_vec<r_dbl>>(f)));
  END_CPPALLY
}
// test_factor.cpp
r_vec<r_sexp> test_factor1(r_factors x);
extern "C" SEXP _cppallytest_test_factor1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_factor1(as<r_factors>(x)));
  END_CPPALLY
}
// test_factor.cpp
r_dbl test_factor3(r_factors x);
extern "C" SEXP _cppallytest_test_factor3(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_factor3(as<r_factors>(x)));
  END_CPPALLY
}
// test_nas.h
extern "C" SEXP _cppallytest_test_nas(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(::test_nas(as<T const&>(x_internal)))) {
        return cpp_to_sexp(::test_nas(as<T const&>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_nas.h
inline r_vec<r_sexp> test_na_types();
extern "C" SEXP _cppallytest_test_na_types() {
  BEGIN_CPPALLY
  return cpp_to_sexp(::test_na_types());
  END_CPPALLY
}
// test_protect.cpp
double bench_protect_insert_release_cppally(int n);
extern "C" SEXP _cppallytest_bench_protect_insert_release_cppally(SEXP n) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::bench_protect_insert_release_cppally(as<int>(n)));
  END_CPPALLY
}
// test_protect.cpp
double bench_protect_copy_cppally(int n);
extern "C" SEXP _cppallytest_bench_protect_copy_cppally(SEXP n) {
  BEGIN_CPPALLY
  return cpp_to_sexp(::bench_protect_copy_cppally(as<int>(n)));
  END_CPPALLY
}
// test_sort.h
extern "C" SEXP _cppallytest_test_order(SEXP x, SEXP preserve_ties) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_sexp(::test_order(as<T>(x_internal), as<bool>(preserve_ties_internal)))) {
        return cpp_to_sexp(::test_order(as<T>(x_internal), as<bool>(preserve_ties_internal)));
    },
    x, preserve_ties
  );
  END_CPPALLY
}
// test_sort.h
extern "C" SEXP _cppallytest_test_sort(SEXP x, SEXP preserve_ties) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_sexp(::test_sort(as<T>(x_internal), as<bool>(preserve_ties_internal)))) {
        return cpp_to_sexp(::test_sort(as<T>(x_internal), as<bool>(preserve_ties_internal)));
    },
    x, preserve_ties
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_range(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(::test_range(as<T>(x_internal), as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(::test_range(as<T>(x_internal), as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(::test_sum(as<r_vec<T>>(x_internal), as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(::test_sum(as<r_vec<T>>(x_internal), as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_mean(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(::test_mean(as<r_vec<T>>(x_internal), as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(::test_mean(as<r_vec<T>>(x_internal), as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_var(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(::test_var(as<r_vec<T>>(x_internal), as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(::test_var(as<r_vec<T>>(x_internal), as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_subset(SEXP x, SEXP i, SEXP invert) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, -1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP i_internal, SEXP invert_internal) -> decltype(cpp_to_sexp(::test_subset(as<T>(x_internal), as<r_vec<U>>(i_internal), as<bool>(invert_internal)))) {
        return cpp_to_sexp(::test_subset(as<T>(x_internal), as<r_vec<U>>(i_internal), as<bool>(invert_internal)));
    },
    x, i, invert
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_fill(SEXP x, SEXP where, SEXP with) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, -1, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP where_internal, SEXP with_internal) -> decltype(cpp_to_sexp(::test_fill(as<r_vec<T>>(x_internal), as<r_vec<r_int>>(where_internal), as<r_vec<U>>(with_internal)))) {
        return cpp_to_sexp(::test_fill(as<r_vec<T>>(x_internal), as<r_vec<r_int>>(where_internal), as<r_vec<U>>(with_internal)));
    },
    x, where, with
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_counts(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_counts(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal)))) {
        return cpp_to_sexp(::test_counts(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_remove(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_remove(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal)))) {
        return cpp_to_sexp(::test_remove(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_find(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(::test_find(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal)))) {
        return cpp_to_sexp(::test_find(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_replace(SEXP x, SEXP y, SEXP z) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal, SEXP z_internal) -> decltype(cpp_to_sexp(::test_replace(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal), as<r_vec<U>>(z_internal)))) {
        return cpp_to_sexp(::test_replace(as<r_vec<T>>(x_internal), as<r_vec<U>>(y_internal), as<r_vec<U>>(z_internal)));
    },
    x, y, z
  );
  END_CPPALLY
}
// test_valgrind.cpp
void test_valgrind();
extern "C" SEXP _cppallytest_test_valgrind() {
  BEGIN_CPPALLY
  ::test_valgrind();
  return R_NilValue;
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cppallytest_C_na_count",                           (DL_FUNC) &_cppallytest_C_na_count,                           1},
    {"_cppallytest_add_half",                             (DL_FUNC) &_cppallytest_add_half,                             1},
    {"_cppallytest_as_int64",                             (DL_FUNC) &_cppallytest_as_int64,                             1},
    {"_cppallytest_as_r_size_t",                          (DL_FUNC) &_cppallytest_as_r_size_t,                          1},
    {"_cppallytest_bench_protect_copy_cppally",           (DL_FUNC) &_cppallytest_bench_protect_copy_cppally,           1},
    {"_cppallytest_bench_protect_insert_release_cppally", (DL_FUNC) &_cppallytest_bench_protect_insert_release_cppally, 1},
    {"_cppallytest_coercions",                            (DL_FUNC) &_cppallytest_coercions,                            0},
    {"_cppallytest_cpp_fast_na_count",                    (DL_FUNC) &_cppallytest_cpp_fast_na_count,                    1},
    {"_cppallytest_cpp_fast_na_count_v2",                 (DL_FUNC) &_cppallytest_cpp_fast_na_count_v2,                 1},
    {"_cppallytest_cpp_get_max_threads",                  (DL_FUNC) &_cppallytest_cpp_get_max_threads,                  0},
    {"_cppallytest_cpp_get_threads",                      (DL_FUNC) &_cppallytest_cpp_get_threads,                      0},
    {"_cppallytest_cpp_length",                           (DL_FUNC) &_cppallytest_cpp_length,                           1},
    {"_cppallytest_cpp_lengths",                          (DL_FUNC) &_cppallytest_cpp_lengths,                          1},
    {"_cppallytest_cpp_lengths2",                         (DL_FUNC) &_cppallytest_cpp_lengths2,                         1},
    {"_cppallytest_cpp_na_count",                         (DL_FUNC) &_cppallytest_cpp_na_count,                         1},
    {"_cppallytest_cpp_set_threads",                      (DL_FUNC) &_cppallytest_cpp_set_threads,                      1},
    {"_cppallytest_cpp_typeof",                           (DL_FUNC) &_cppallytest_cpp_typeof,                           1},
    {"_cppallytest_double_to_int",                        (DL_FUNC) &_cppallytest_double_to_int,                        1},
    {"_cppallytest_factor_codes",                         (DL_FUNC) &_cppallytest_factor_codes,                         1},
    {"_cppallytest_new_factor",                           (DL_FUNC) &_cppallytest_new_factor,                           1},
    {"_cppallytest_scalar1",                              (DL_FUNC) &_cppallytest_scalar1,                              1},
    {"_cppallytest_scalar2",                              (DL_FUNC) &_cppallytest_scalar2,                              1},
    {"_cppallytest_scalar3",                              (DL_FUNC) &_cppallytest_scalar3,                              2},
    {"_cppallytest_scalar4",                              (DL_FUNC) &_cppallytest_scalar4,                              2},
    {"_cppallytest_scalar_init",                          (DL_FUNC) &_cppallytest_scalar_init,                          1},
    {"_cppallytest_scalar_vec1",                          (DL_FUNC) &_cppallytest_scalar_vec1,                          2},
    {"_cppallytest_scalar_vec2",                          (DL_FUNC) &_cppallytest_scalar_vec2,                          2},
    {"_cppallytest_scalar_vec3",                          (DL_FUNC) &_cppallytest_scalar_vec3,                          4},
    {"_cppallytest_symbol_to_string",                     (DL_FUNC) &_cppallytest_symbol_to_string,                     1},
    {"_cppallytest_test_as_date",                         (DL_FUNC) &_cppallytest_test_as_date,                         1},
    {"_cppallytest_test_as_date2",                        (DL_FUNC) &_cppallytest_test_as_date2,                        1},
    {"_cppallytest_test_as_dbl",                          (DL_FUNC) &_cppallytest_test_as_dbl,                          6},
    {"_cppallytest_test_as_int",                          (DL_FUNC) &_cppallytest_test_as_int,                          6},
    {"_cppallytest_test_as_str",                          (DL_FUNC) &_cppallytest_test_as_str,                          6},
    {"_cppallytest_test_as_sym",                          (DL_FUNC) &_cppallytest_test_as_sym,                          6},
    {"_cppallytest_test_attrs",                           (DL_FUNC) &_cppallytest_test_attrs,                           1},
    {"_cppallytest_test_coerce",                          (DL_FUNC) &_cppallytest_test_coerce,                          2},
    {"_cppallytest_test_coerce1",                         (DL_FUNC) &_cppallytest_test_coerce1,                         1},
    {"_cppallytest_test_combine2",                        (DL_FUNC) &_cppallytest_test_combine2,                        2},
    {"_cppallytest_test_construct_date",                  (DL_FUNC) &_cppallytest_test_construct_date,                  1},
    {"_cppallytest_test_copy",                            (DL_FUNC) &_cppallytest_test_copy,                            1},
    {"_cppallytest_test_counts",                          (DL_FUNC) &_cppallytest_test_counts,                          2},
    {"_cppallytest_test_dates1",                          (DL_FUNC) &_cppallytest_test_dates1,                          1},
    {"_cppallytest_test_dates2",                          (DL_FUNC) &_cppallytest_test_dates2,                          1},
    {"_cppallytest_test_deduced_scalar_type",             (DL_FUNC) &_cppallytest_test_deduced_scalar_type,             1},
    {"_cppallytest_test_deduced_scalar_type2",            (DL_FUNC) &_cppallytest_test_deduced_scalar_type2,            1},
    {"_cppallytest_test_deduced_type",                    (DL_FUNC) &_cppallytest_test_deduced_type,                    1},
    {"_cppallytest_test_deduced_vec_type",                (DL_FUNC) &_cppallytest_test_deduced_vec_type,                1},
    {"_cppallytest_test_df",                              (DL_FUNC) &_cppallytest_test_df,                              1},
    {"_cppallytest_test_factor1",                         (DL_FUNC) &_cppallytest_test_factor1,                         1},
    {"_cppallytest_test_factor2",                         (DL_FUNC) &_cppallytest_test_factor2,                         1},
    {"_cppallytest_test_factor3",                         (DL_FUNC) &_cppallytest_test_factor3,                         1},
    {"_cppallytest_test_fill",                            (DL_FUNC) &_cppallytest_test_fill,                            3},
    {"_cppallytest_test_find",                            (DL_FUNC) &_cppallytest_test_find,                            2},
    {"_cppallytest_test_group_counts",                    (DL_FUNC) &_cppallytest_test_group_counts,                    2},
    {"_cppallytest_test_group_id",                        (DL_FUNC) &_cppallytest_test_group_id,                        2},
    {"_cppallytest_test_identical",                       (DL_FUNC) &_cppallytest_test_identical,                       2},
    {"_cppallytest_test_identity",                        (DL_FUNC) &_cppallytest_test_identity,                        1},
    {"_cppallytest_test_identity2",                       (DL_FUNC) &_cppallytest_test_identity2,                       1},
    {"_cppallytest_test_lengths",                         (DL_FUNC) &_cppallytest_test_lengths,                         1},
    {"_cppallytest_test_lgl",                             (DL_FUNC) &_cppallytest_test_lgl,                             0},
    {"_cppallytest_test_list_to_scalars",                 (DL_FUNC) &_cppallytest_test_list_to_scalars,                 1},
    {"_cppallytest_test_match",                           (DL_FUNC) &_cppallytest_test_match,                           2},
    {"_cppallytest_test_mean",                            (DL_FUNC) &_cppallytest_test_mean,                            2},
    {"_cppallytest_test_mix2",                            (DL_FUNC) &_cppallytest_test_mix2,                            7},
    {"_cppallytest_test_multiline_template_add",          (DL_FUNC) &_cppallytest_test_multiline_template_add,          2},
    {"_cppallytest_test_multiline_template_add2",         (DL_FUNC) &_cppallytest_test_multiline_template_add2,         2},
    {"_cppallytest_test_multiple_deduction",              (DL_FUNC) &_cppallytest_test_multiple_deduction,              2},
    {"_cppallytest_test_n_unique",                        (DL_FUNC) &_cppallytest_test_n_unique,                        1},
    {"_cppallytest_test_na_types",                        (DL_FUNC) &_cppallytest_test_na_types,                        0},
    {"_cppallytest_test_nas",                             (DL_FUNC) &_cppallytest_test_nas,                             1},
    {"_cppallytest_test_null",                            (DL_FUNC) &_cppallytest_test_null,                            0},
    {"_cppallytest_test_order",                           (DL_FUNC) &_cppallytest_test_order,                           2},
    {"_cppallytest_test_range",                           (DL_FUNC) &_cppallytest_test_range,                           2},
    {"_cppallytest_test_remove",                          (DL_FUNC) &_cppallytest_test_remove,                          2},
    {"_cppallytest_test_replace",                         (DL_FUNC) &_cppallytest_test_replace,                         3},
    {"_cppallytest_test_rval_identity",                   (DL_FUNC) &_cppallytest_test_rval_identity,                   1},
    {"_cppallytest_test_scalar",                          (DL_FUNC) &_cppallytest_test_scalar,                          2},
    {"_cppallytest_test_scalar2",                         (DL_FUNC) &_cppallytest_test_scalar2,                         2},
    {"_cppallytest_test_scalar3",                         (DL_FUNC) &_cppallytest_test_scalar3,                         2},
    {"_cppallytest_test_seqs",                            (DL_FUNC) &_cppallytest_test_seqs,                            3},
    {"_cppallytest_test_sexp",                            (DL_FUNC) &_cppallytest_test_sexp,                            1},
    {"_cppallytest_test_sexp2",                           (DL_FUNC) &_cppallytest_test_sexp2,                           1},
    {"_cppallytest_test_sexp3",                           (DL_FUNC) &_cppallytest_test_sexp3,                           1},
    {"_cppallytest_test_sexp4",                           (DL_FUNC) &_cppallytest_test_sexp4,                           1},
    {"_cppallytest_test_sort",                            (DL_FUNC) &_cppallytest_test_sort,                            2},
    {"_cppallytest_test_specialisation",                  (DL_FUNC) &_cppallytest_test_specialisation,                  1},
    {"_cppallytest_test_str1",                            (DL_FUNC) &_cppallytest_test_str1,                            1},
    {"_cppallytest_test_str2",                            (DL_FUNC) &_cppallytest_test_str2,                            1},
    {"_cppallytest_test_str3",                            (DL_FUNC) &_cppallytest_test_str3,                            1},
    {"_cppallytest_test_str4",                            (DL_FUNC) &_cppallytest_test_str4,                            1},
    {"_cppallytest_test_subset",                          (DL_FUNC) &_cppallytest_test_subset,                          3},
    {"_cppallytest_test_sum",                             (DL_FUNC) &_cppallytest_test_sum,                             2},
    {"_cppallytest_test_sym",                             (DL_FUNC) &_cppallytest_test_sym,                             1},
    {"_cppallytest_test_template_null",                   (DL_FUNC) &_cppallytest_test_template_null,                   1},
    {"_cppallytest_test_tz",                              (DL_FUNC) &_cppallytest_test_tz,                              1},
    {"_cppallytest_test_unique",                          (DL_FUNC) &_cppallytest_test_unique,                          1},
    {"_cppallytest_test_valgrind",                        (DL_FUNC) &_cppallytest_test_valgrind,                        0},
    {"_cppallytest_test_var",                             (DL_FUNC) &_cppallytest_test_var,                             2},
    {"_cppallytest_to_int_vec",                           (DL_FUNC) &_cppallytest_to_int_vec,                           1},
    {"_cppallytest_vector1",                              (DL_FUNC) &_cppallytest_vector1,                              1},
    {"_cppallytest_vector2",                              (DL_FUNC) &_cppallytest_vector2,                              1},
    {NULL, NULL, 0}
};
}


void foo(DllInfo* dll);
void bar(DllInfo* dll);

extern "C" attribute_visible void R_init_cppallytest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  foo(dll);
  bar(dll);
  R_forceSymbols(dll, TRUE);
}
