// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>
#include "test.h"
#include "test_functionals.h"
#include "test_nas.h"
#include "test_refs.h"
#include "test_rep.h"
#include "test_replace_at.h"
#include "test_sort.h"
#include "test_stats.h"
#include "test_subset.h"

using namespace cppally;
using internal::cpp_to_r;
using internal::r_to_cpp;
using internal::dispatch_template_impl;

// test.cpp
void cpp_set_threads(int n);
extern "C" SEXP _cppallytest_cpp_set_threads(SEXP n) {
  BEGIN_CPPALLY
  ::cpp_set_threads(r_to_cpp<int>(n));
  return R_NilValue;
  END_CPPALLY
}
// test.cpp
r_int cpp_get_threads();
extern "C" SEXP _cppallytest_cpp_get_threads() {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_get_threads());
  END_CPPALLY
}
// test.cpp
r_int cpp_get_max_threads();
extern "C" SEXP _cppallytest_cpp_get_max_threads() {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_get_max_threads());
  END_CPPALLY
}
// test.cpp
r_str cpp_typeof(SEXP x);
extern "C" SEXP _cppallytest_cpp_typeof(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_typeof(r_to_cpp<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
SEXP test_identity2(SEXP x);
extern "C" SEXP _cppallytest_test_identity2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_identity2(r_to_cpp<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_str> test_str1(r_str x);
extern "C" SEXP _cppallytest_test_str1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_str1(r_to_cpp<r_str>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_str_view> test_str2(r_str_view x);
extern "C" SEXP _cppallytest_test_str2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_str2(r_to_cpp<r_str_view>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_as_date(SEXP x);
extern "C" SEXP _cppallytest_test_as_date(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_as_date(r_to_cpp<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_construct_date(SEXP x);
extern "C" SEXP _cppallytest_test_construct_date(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_construct_date(r_to_cpp<SEXP>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_as_date2(r_vec<r_date> x);
extern "C" SEXP _cppallytest_test_as_date2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_as_date2(r_to_cpp<r_vec<r_date>>(x)));
  END_CPPALLY
}
// test.cpp
r_sexp test_null();
extern "C" SEXP _cppallytest_test_null() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_null());
  END_CPPALLY
}
// test.cpp
r_sym test_sym(r_sym x);
extern "C" SEXP _cppallytest_test_sym(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_sym(r_to_cpp<r_sym>(x)));
  END_CPPALLY
}
// test.cpp
r_sexp test_sexp2(r_sexp x);
extern "C" SEXP _cppallytest_test_sexp2(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_sexp2(r_to_cpp<r_sexp>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_sexp> test_sexp3(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_test_sexp3(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_sexp3(r_to_cpp<r_vec<r_sexp>>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_int> test_coerce1(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_test_coerce1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_coerce1(r_to_cpp<const r_vec<r_sexp>&>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_dates1(r_vec<r_date> x);
extern "C" SEXP _cppallytest_test_dates1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_dates1(r_to_cpp<r_vec<r_date>>(x)));
  END_CPPALLY
}
// test.cpp
r_str test_tz(r_vec<r_psxct> x);
extern "C" SEXP _cppallytest_test_tz(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_tz(r_to_cpp<r_vec<r_psxct>>(x)));
  END_CPPALLY
}
// test.cpp
r_vec<r_int> test_lengths(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_test_lengths(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_lengths(r_to_cpp<const r_vec<r_sexp>&>(x)));
  END_CPPALLY
}
// test.cpp
r_lgl test_lgl();
extern "C" SEXP _cppallytest_test_lgl() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_lgl());
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_type(std::declval<T>()))) {
        return cpp_to_r(::test_deduced_type(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiple_deduction(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_multiple_deduction(std::declval<T>(), std::declval<T>()))) {
        return cpp_to_r(::test_multiple_deduction(r_to_cpp<T>(x_internal), r_to_cpp<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_vec_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_vec_type(std::declval<T>()))) {
        return cpp_to_r(::test_deduced_vec_type(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_scalar_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_scalar_type(std::declval<T>()))) {
        return cpp_to_r(::test_deduced_scalar_type(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_scalar_type2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_scalar_type2(std::declval<T>()))) {
        return cpp_to_r(::test_deduced_scalar_type2(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_identity(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_identity(std::declval<T>()))) {
        return cpp_to_r(::test_identity(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_template_null(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_template_null(std::declval<T>()))) {
        return cpp_to_r(::test_template_null(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_scalar(std::declval<int>(), std::declval<T>()))) {
        return cpp_to_r(::test_scalar(r_to_cpp<int>(x_internal), r_to_cpp<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_scalar2(std::declval<r_int>(), std::declval<T>()))) {
        return cpp_to_r(::test_scalar2(r_to_cpp<r_int>(x_internal), r_to_cpp<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar3(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_scalar3(std::declval<r_int>(), std::declval<T>()))) {
        return cpp_to_r(::test_scalar3(r_to_cpp<r_int>(x_internal), r_to_cpp<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_rval_identity(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_rval_identity(std::declval<T>()))) {
        return cpp_to_r(::test_rval_identity(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar1(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::scalar1(std::declval<T>()))) {
        return cpp_to_r(::scalar1(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::scalar2(std::declval<T>()))) {
        return cpp_to_r(::scalar2(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_vector1(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::vector1(std::declval<r_vec<T>>()))) {
        return cpp_to_r(::vector1(r_to_cpp<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_vector2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::vector2(std::declval<T>()))) {
        return cpp_to_r(::vector2(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar3(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::scalar3(std::declval<T>(), std::declval<T>()))) {
        return cpp_to_r(::scalar3(r_to_cpp<T>(x_internal), r_to_cpp<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar4(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::scalar4(std::declval<T>(), std::declval<U>()))) {
        return cpp_to_r(::scalar4(r_to_cpp<T>(x_internal), r_to_cpp<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_sexp(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_sexp(std::declval<T>()))) {
        return cpp_to_r(::test_sexp(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_sexp4(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_sexp4(std::declval<T>()))) {
        return cpp_to_r(::test_sexp4(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec1(SEXP a, SEXP b) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_r(::scalar_vec1(std::declval<r_vec<T>>(), std::declval<T>()))) {
        return cpp_to_r(::scalar_vec1(r_to_cpp<r_vec<T>>(a_internal), r_to_cpp<T>(b_internal)));
    },
    a, b
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec2(SEXP a, SEXP b) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_r(::scalar_vec2(std::declval<r_vec<T>>(), std::declval<U>()))) {
        return cpp_to_r(::scalar_vec2(r_to_cpp<r_vec<T>>(a_internal), r_to_cpp<U>(b_internal)));
    },
    a, b
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec3(SEXP z, SEXP x, SEXP y, SEXP a) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 4, std::array<int, 4>{0, 0, 1, 1}>(
    []<typename T, typename U>(SEXP z_internal, SEXP x_internal, SEXP y_internal, SEXP a_internal) -> decltype(cpp_to_r(::scalar_vec3(std::declval<r_vec<T>>(), std::declval<T>(), std::declval<U>(), std::declval<r_vec<U>>()))) {
        return cpp_to_r(::scalar_vec3(r_to_cpp<r_vec<T>>(z_internal), r_to_cpp<T>(x_internal), r_to_cpp<U>(y_internal), r_to_cpp<r_vec<U>>(a_internal)));
    },
    z, x, y, a
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_mix2(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f, SEXP g) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 7, std::array<int, 7>{0, -1, 0, -1, 0, 0, 1}>(
    []<typename T, typename V>(SEXP a_internal, SEXP b_internal, SEXP c_internal, SEXP d_internal, SEXP e_internal, SEXP f_internal, SEXP g_internal) -> decltype(cpp_to_r(::test_mix2(std::declval<r_vec<T>>(), std::declval<double>(), std::declval<T>(), std::declval<int>(), std::declval<T>(), std::declval<T>(), std::declval<V>()))) {
        return cpp_to_r(::test_mix2(r_to_cpp<r_vec<T>>(a_internal), r_to_cpp<double>(b_internal), r_to_cpp<T>(c_internal), r_to_cpp<int>(d_internal), r_to_cpp<T>(e_internal), r_to_cpp<T>(f_internal), r_to_cpp<V>(g_internal)));
    },
    a, b, c, d, e, f, g
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_str3(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_str3(std::declval<T>()))) {
        return cpp_to_r(::test_str3(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_str4(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_str4(std::declval<T>()))) {
        return cpp_to_r(::test_str4(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_specialisation(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_specialisation(std::declval<r_vec<T>>()))) {
        return cpp_to_r(::test_specialisation(r_to_cpp<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_coerce(SEXP x, SEXP ptype) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP ptype_internal) -> decltype(cpp_to_r(::test_coerce(std::declval<r_vec<T>>(), std::declval<U>()))) {
        return cpp_to_r(::test_coerce(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<U>(ptype_internal)));
    },
    x, ptype
  );
  END_CPPALLY
}
// test.h
SEXP test_list_to_scalars(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_test_list_to_scalars(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_list_to_scalars(r_to_cpp<r_vec<r_sexp>>(x)));
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_combine2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_combine2(std::declval<T>(), std::declval<T>()))) {
        return cpp_to_r(::test_combine2(r_to_cpp<T>(x_internal), r_to_cpp<T>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_dates2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_dates2(std::declval<T>()))) {
        return cpp_to_r(::test_dates2(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_unique(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_unique(std::declval<T>()))) {
        return cpp_to_r(::test_unique(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_group_id(SEXP x, SEXP order) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_r(::test_group_id(std::declval<T>(), std::declval<bool>()))) {
        return cpp_to_r(::test_group_id(r_to_cpp<T>(x_internal), r_to_cpp<bool>(order_internal)));
    },
    x, order
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_group_counts(SEXP x, SEXP order) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_r(::test_group_counts(std::declval<T>(), std::declval<bool>()))) {
        return cpp_to_r(::test_group_counts(r_to_cpp<T>(x_internal), r_to_cpp<bool>(order_internal)));
    },
    x, order
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_match(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_match(std::declval<r_vec<T>>(), std::declval<r_vec<T>>()))) {
        return cpp_to_r(::test_match(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<r_vec<T>>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_factor2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_factor2(std::declval<T>()))) {
        return cpp_to_r(::test_factor2(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_n_unique(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_n_unique(std::declval<T>()))) {
        return cpp_to_r(::test_n_unique(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test.h
SEXP test_copy(SEXP x);
extern "C" SEXP _cppallytest_test_copy(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_copy(r_to_cpp<SEXP>(x)));
  END_CPPALLY
}
// test.h
bool test_identical(SEXP x, SEXP y);
extern "C" SEXP _cppallytest_test_identical(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_identical(r_to_cpp<SEXP>(x), r_to_cpp<SEXP>(y)));
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiline_template_add(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_multiline_template_add(std::declval<T>(), std::declval<U>()))) {
        return cpp_to_r(::test_multiline_template_add(r_to_cpp<T>(x_internal), r_to_cpp<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiline_template_add2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_multiline_template_add2(std::declval<T>(), std::declval<U>()))) {
        return cpp_to_r(::test_multiline_template_add2(r_to_cpp<T>(x_internal), r_to_cpp<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_arithmetic.cpp
void test_arithmetic();
extern "C" SEXP _cppallytest_test_arithmetic() {
  BEGIN_CPPALLY
  ::test_arithmetic();
  return R_NilValue;
  END_CPPALLY
}
// test_arithmetic.cpp
void test_overflow();
extern "C" SEXP _cppallytest_test_overflow() {
  BEGIN_CPPALLY
  ::test_overflow();
  return R_NilValue;
  END_CPPALLY
}
// test_arithmetic.cpp
void test_arithmetic_edge_cases();
extern "C" SEXP _cppallytest_test_arithmetic_edge_cases() {
  BEGIN_CPPALLY
  ::test_arithmetic_edge_cases();
  return R_NilValue;
  END_CPPALLY
}
// test_attrs.cpp
r_vec<r_sexp> test_attrs(SEXP x);
extern "C" SEXP _cppallytest_test_attrs(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_attrs(r_to_cpp<SEXP>(x)));
  END_CPPALLY
}
// test_attrs.cpp
r_vec<r_sexp> test_df(r_vec<r_sexp> cols);
extern "C" SEXP _cppallytest_test_df(SEXP cols) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_df(r_to_cpp<r_vec<r_sexp>>(cols)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_sym(SEXP a, r_str b, r_dbl c, r_sym d, r_vec<r_str> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_sym(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_as_sym(r_to_cpp<SEXP>(a), r_to_cpp<r_str>(b), r_to_cpp<r_dbl>(c), r_to_cpp<r_sym>(d), r_to_cpp<r_vec<r_str>>(e), r_to_cpp<r_vec<r_dbl>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_int(SEXP a, r_str b, r_dbl c, r_sym d, r_vec<r_str> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_int(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_as_int(r_to_cpp<SEXP>(a), r_to_cpp<r_str>(b), r_to_cpp<r_dbl>(c), r_to_cpp<r_sym>(d), r_to_cpp<r_vec<r_str>>(e), r_to_cpp<r_vec<r_dbl>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_dbl(SEXP a, r_str b, r_int c, r_sym d, r_vec<r_str> e, r_vec<r_int> f);
extern "C" SEXP _cppallytest_test_as_dbl(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_as_dbl(r_to_cpp<SEXP>(a), r_to_cpp<r_str>(b), r_to_cpp<r_int>(c), r_to_cpp<r_sym>(d), r_to_cpp<r_vec<r_str>>(e), r_to_cpp<r_vec<r_int>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_str(SEXP a, r_int b, r_dbl c, r_sym d, r_vec<r_int> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_str(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_as_str(r_to_cpp<SEXP>(a), r_to_cpp<r_int>(b), r_to_cpp<r_dbl>(c), r_to_cpp<r_sym>(d), r_to_cpp<r_vec<r_int>>(e), r_to_cpp<r_vec<r_dbl>>(f)));
  END_CPPALLY
}
// test_coerce.cpp
void test_to_int();
extern "C" SEXP _cppallytest_test_to_int() {
  BEGIN_CPPALLY
  ::test_to_int();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_int64();
extern "C" SEXP _cppallytest_test_to_int64() {
  BEGIN_CPPALLY
  ::test_to_int64();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_double();
extern "C" SEXP _cppallytest_test_to_double() {
  BEGIN_CPPALLY
  ::test_to_double();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_uint();
extern "C" SEXP _cppallytest_test_to_uint() {
  BEGIN_CPPALLY
  ::test_to_uint();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_r_size_t();
extern "C" SEXP _cppallytest_test_to_r_size_t() {
  BEGIN_CPPALLY
  ::test_to_r_size_t();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_bool();
extern "C" SEXP _cppallytest_test_to_bool() {
  BEGIN_CPPALLY
  ::test_to_bool();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_r_int();
extern "C" SEXP _cppallytest_test_to_r_int() {
  BEGIN_CPPALLY
  ::test_to_r_int();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_r_int64();
extern "C" SEXP _cppallytest_test_to_r_int64() {
  BEGIN_CPPALLY
  ::test_to_r_int64();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_r_dbl();
extern "C" SEXP _cppallytest_test_to_r_dbl() {
  BEGIN_CPPALLY
  ::test_to_r_dbl();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_to_r_lgl();
extern "C" SEXP _cppallytest_test_to_r_lgl() {
  BEGIN_CPPALLY
  ::test_to_r_lgl();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_edge();
extern "C" SEXP _cppallytest_test_coerce_edge() {
  BEGIN_CPPALLY
  ::test_coerce_edge();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_int64_to_int_overflow();
extern "C" SEXP _cppallytest_test_coerce_int64_to_int_overflow() {
  BEGIN_CPPALLY
  ::test_coerce_int64_to_int_overflow();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_dbl_to_int_overflow();
extern "C" SEXP _cppallytest_test_coerce_dbl_to_int_overflow() {
  BEGIN_CPPALLY
  ::test_coerce_dbl_to_int_overflow();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_pos_inf_to_int();
extern "C" SEXP _cppallytest_test_coerce_pos_inf_to_int() {
  BEGIN_CPPALLY
  ::test_coerce_pos_inf_to_int();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_neg_inf_to_int();
extern "C" SEXP _cppallytest_test_coerce_neg_inf_to_int() {
  BEGIN_CPPALLY
  ::test_coerce_neg_inf_to_int();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_dbl_to_int64_overflow();
extern "C" SEXP _cppallytest_test_coerce_dbl_to_int64_overflow() {
  BEGIN_CPPALLY
  ::test_coerce_dbl_to_int64_overflow();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_int_min_to_int();
extern "C" SEXP _cppallytest_test_coerce_int_min_to_int() {
  BEGIN_CPPALLY
  ::test_coerce_int_min_to_int();
  return R_NilValue;
  END_CPPALLY
}
// test_coerce.cpp
void test_coerce_int64_min_to_int64();
extern "C" SEXP _cppallytest_test_coerce_int64_min_to_int64() {
  BEGIN_CPPALLY
  ::test_coerce_int64_min_to_int64();
  return R_NilValue;
  END_CPPALLY
}
// test_factor.cpp
r_vec<r_sexp> test_factor1(r_factors x);
extern "C" SEXP _cppallytest_test_factor1(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_factor1(r_to_cpp<r_factors>(x)));
  END_CPPALLY
}
// test_factor.cpp
r_dbl test_factor3(r_factors x);
extern "C" SEXP _cppallytest_test_factor3(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_factor3(r_to_cpp<r_factors>(x)));
  END_CPPALLY
}
// test_functionals.h
extern "C" SEXP _cppallytest_reduce_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::reduce_sum(std::declval<r_vec<T>>(), std::declval<bool>()))) {
        return cpp_to_r(::reduce_sum(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_functionals.h
extern "C" SEXP _cppallytest_reduce_max(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::reduce_max(std::declval<r_vec<T>>(), std::declval<bool>()))) {
        return cpp_to_r(::reduce_max(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_functionals.h
extern "C" SEXP _cppallytest_reduce_cumulative_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::reduce_cumulative_sum(std::declval<r_vec<T>>(), std::declval<bool>()))) {
        return cpp_to_r(::reduce_cumulative_sum(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_functionals.h
extern "C" SEXP _cppallytest_reduce_gcd(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::reduce_gcd(std::declval<r_vec<T>>()))) {
        return cpp_to_r(::reduce_gcd(r_to_cpp<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_functionals.h
extern "C" SEXP _cppallytest_pmap2_add(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::pmap2_add(std::declval<r_vec<T>>(), std::declval<r_vec<U>>()))) {
        return cpp_to_r(::pmap2_add(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_functionals.h
r_sexp pmap_add(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_pmap_add(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::pmap_add(r_to_cpp<r_vec<r_sexp>>(x)));
  END_CPPALLY
}
// test_names.cpp
r_vec<r_str_view> test_names_inplace_mutation();
extern "C" SEXP _cppallytest_test_names_inplace_mutation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_inplace_mutation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_stale_invalidation();
extern "C" SEXP _cppallytest_test_names_stale_invalidation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_stale_invalidation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_set_attr_invalidation();
extern "C" SEXP _cppallytest_test_names_set_attr_invalidation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_set_attr_invalidation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_growing();
extern "C" SEXP _cppallytest_test_names_growing() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_growing());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_sweep();
extern "C" SEXP _cppallytest_test_names_sweep() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_sweep());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_shallow_copy_isolation();
extern "C" SEXP _cppallytest_test_names_shallow_copy_isolation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_shallow_copy_isolation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_empty();
extern "C" SEXP _cppallytest_test_names_empty() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_empty());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_roundtrip_after_grow();
extern "C" SEXP _cppallytest_test_names_roundtrip_after_grow() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_roundtrip_after_grow());
  END_CPPALLY
}
// test_nas.h
extern "C" SEXP _cppallytest_vec_is_na(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::vec_is_na(std::declval<const T&>()))) {
        return cpp_to_r(::vec_is_na(r_to_cpp<const T&>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_nas.h
extern "C" SEXP _cppallytest_test_nas(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_nas(std::declval<T const&>()))) {
        auto x_arg = r_to_cpp<T const&>(x_internal);
        return cpp_to_r(::test_nas(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test_nas.h
inline r_vec<r_sexp> test_na_types();
extern "C" SEXP _cppallytest_test_na_types() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_na_types());
  END_CPPALLY
}
// test_protect.cpp
r_lgl test_protect_count_tracking();
extern "C" SEXP _cppallytest_test_protect_count_tracking() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_protect_count_tracking());
  END_CPPALLY
}
// test_protect.cpp
r_lgl test_protect_slot_reuse();
extern "C" SEXP _cppallytest_test_protect_slot_reuse() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_protect_slot_reuse());
  END_CPPALLY
}
// test_protect.cpp
r_lgl test_protect_chunk_growth();
extern "C" SEXP _cppallytest_test_protect_chunk_growth() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_protect_chunk_growth());
  END_CPPALLY
}
// test_protect.cpp
r_lgl test_protect_burst_reserve();
extern "C" SEXP _cppallytest_test_protect_burst_reserve() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_protect_burst_reserve());
  END_CPPALLY
}
// test_refs.h
SEXP test_by_value(r_vec<r_dbl> x);
extern "C" SEXP _cppallytest_test_by_value(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_by_value(r_to_cpp<r_vec<r_dbl>>(x)));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_lvalue_ref(r_vec<r_dbl>& x);
extern "C" SEXP _cppallytest_test_by_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = r_to_cpp<r_vec<r_dbl>&>(x);
  return cpp_to_r(::test_by_lvalue_ref(x_arg));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_rvalue_ref(r_vec<r_dbl>&& x);
extern "C" SEXP _cppallytest_test_by_rvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_by_rvalue_ref(r_to_cpp<r_vec<r_dbl>&&>(x)));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_const_lvalue_ref(const r_vec<r_dbl>& x);
extern "C" SEXP _cppallytest_test_by_const_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_by_const_lvalue_ref(r_to_cpp<const r_vec<r_dbl>&>(x)));
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_value(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_value(std::declval<T>()))) {
        return cpp_to_r(::test_temp_by_value(r_to_cpp<T>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_lvalue_ref(std::declval<T&>()))) {
        auto x_arg = r_to_cpp<T&>(x_internal);
        return cpp_to_r(::test_temp_by_lvalue_ref(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_rvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_rvalue_ref(std::declval<T&&>()))) {
        return cpp_to_r(::test_temp_by_rvalue_ref(r_to_cpp<T&&>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_const_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_const_lvalue_ref(std::declval<const T&>()))) {
        return cpp_to_r(::test_temp_by_const_lvalue_ref(r_to_cpp<const T&>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_rep.h
extern "C" SEXP _cppallytest_test_rep_len(SEXP x, SEXP n) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP n_internal) -> decltype(cpp_to_r(::test_rep_len(std::declval<T>(), std::declval<int>()))) {
        return cpp_to_r(::test_rep_len(r_to_cpp<T>(x_internal), r_to_cpp<int>(n_internal)));
    },
    x, n
  );
  END_CPPALLY
}
// test_rep.h
extern "C" SEXP _cppallytest_test_rep(SEXP x, SEXP times) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP times_internal) -> decltype(cpp_to_r(::test_rep(std::declval<T>(), std::declval<r_vec<r_int>>()))) {
        return cpp_to_r(::test_rep(r_to_cpp<T>(x_internal), r_to_cpp<r_vec<r_int>>(times_internal)));
    },
    x, times
  );
  END_CPPALLY
}
// test_rep.h
extern "C" SEXP _cppallytest_test_rep_each(SEXP x, SEXP each) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP each_internal) -> decltype(cpp_to_r(::test_rep_each(std::declval<T>(), std::declval<r_vec<r_int>>()))) {
        return cpp_to_r(::test_rep_each(r_to_cpp<T>(x_internal), r_to_cpp<r_vec<r_int>>(each_internal)));
    },
    x, each
  );
  END_CPPALLY
}
// test_replace_at.h
extern "C" SEXP _cppallytest_test_replace_at(SEXP x, SEXP where, SEXP with) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, 0}>(
    []<typename T, typename U>(SEXP x_internal, SEXP where_internal, SEXP with_internal) -> decltype(cpp_to_r(::test_replace_at(std::declval<T>(), std::declval<r_vec<U>>(), std::declval<T>()))) {
        return cpp_to_r(::test_replace_at(r_to_cpp<T>(x_internal), r_to_cpp<r_vec<U>>(where_internal), r_to_cpp<T>(with_internal)));
    },
    x, where, with
  );
  END_CPPALLY
}
// test_sort.h
extern "C" SEXP _cppallytest_test_order(SEXP x, SEXP preserve_ties) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_r(::test_order(std::declval<T>(), std::declval<bool>()))) {
        return cpp_to_r(::test_order(r_to_cpp<T>(x_internal), r_to_cpp<bool>(preserve_ties_internal)));
    },
    x, preserve_ties
  );
  END_CPPALLY
}
// test_sort.h
extern "C" SEXP _cppallytest_test_sort(SEXP x, SEXP preserve_ties) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_r(::test_sort(std::declval<T>(), std::declval<bool>()))) {
        return cpp_to_r(::test_sort(r_to_cpp<T>(x_internal), r_to_cpp<bool>(preserve_ties_internal)));
    },
    x, preserve_ties
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_range(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_range(std::declval<T>(), std::declval<bool>()))) {
        return cpp_to_r(::test_range(r_to_cpp<T>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_sum(std::declval<r_vec<T>>(), std::declval<bool>()))) {
        return cpp_to_r(::test_sum(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_mean(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_mean(std::declval<r_vec<T>>(), std::declval<bool>()))) {
        return cpp_to_r(::test_mean(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_var(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_var(std::declval<r_vec<T>>(), std::declval<bool>()))) {
        return cpp_to_r(::test_var(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_subset(SEXP x, SEXP i, SEXP invert) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, -1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP i_internal, SEXP invert_internal) -> decltype(cpp_to_r(::test_subset(std::declval<T>(), std::declval<r_vec<U>>(), std::declval<bool>()))) {
        return cpp_to_r(::test_subset(r_to_cpp<T>(x_internal), r_to_cpp<r_vec<U>>(i_internal), r_to_cpp<bool>(invert_internal)));
    },
    x, i, invert
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_find(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_find(std::declval<r_vec<T>>(), std::declval<U>()))) {
        return cpp_to_r(::test_find(r_to_cpp<r_vec<T>>(x_internal), r_to_cpp<U>(y_internal)));
    },
    x, y
  );
  END_CPPALLY
}
// test_valgrind.cpp
void test_valgrind();
extern "C" SEXP _cppallytest_test_valgrind() {
  BEGIN_CPPALLY
  ::test_valgrind();
  return R_NilValue;
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cppallytest_cpp_get_max_threads",               (DL_FUNC) &_cppallytest_cpp_get_max_threads,               0},
    {"_cppallytest_cpp_get_threads",                   (DL_FUNC) &_cppallytest_cpp_get_threads,                   0},
    {"_cppallytest_cpp_set_threads",                   (DL_FUNC) &_cppallytest_cpp_set_threads,                   1},
    {"_cppallytest_cpp_typeof",                        (DL_FUNC) &_cppallytest_cpp_typeof,                        1},
    {"_cppallytest_pmap2_add",                         (DL_FUNC) &_cppallytest_pmap2_add,                         2},
    {"_cppallytest_pmap_add",                          (DL_FUNC) &_cppallytest_pmap_add,                          1},
    {"_cppallytest_reduce_cumulative_sum",             (DL_FUNC) &_cppallytest_reduce_cumulative_sum,             2},
    {"_cppallytest_reduce_gcd",                        (DL_FUNC) &_cppallytest_reduce_gcd,                        1},
    {"_cppallytest_reduce_max",                        (DL_FUNC) &_cppallytest_reduce_max,                        2},
    {"_cppallytest_reduce_sum",                        (DL_FUNC) &_cppallytest_reduce_sum,                        2},
    {"_cppallytest_scalar1",                           (DL_FUNC) &_cppallytest_scalar1,                           1},
    {"_cppallytest_scalar2",                           (DL_FUNC) &_cppallytest_scalar2,                           1},
    {"_cppallytest_scalar3",                           (DL_FUNC) &_cppallytest_scalar3,                           2},
    {"_cppallytest_scalar4",                           (DL_FUNC) &_cppallytest_scalar4,                           2},
    {"_cppallytest_scalar_vec1",                       (DL_FUNC) &_cppallytest_scalar_vec1,                       2},
    {"_cppallytest_scalar_vec2",                       (DL_FUNC) &_cppallytest_scalar_vec2,                       2},
    {"_cppallytest_scalar_vec3",                       (DL_FUNC) &_cppallytest_scalar_vec3,                       4},
    {"_cppallytest_test_arithmetic",                   (DL_FUNC) &_cppallytest_test_arithmetic,                   0},
    {"_cppallytest_test_arithmetic_edge_cases",        (DL_FUNC) &_cppallytest_test_arithmetic_edge_cases,        0},
    {"_cppallytest_test_as_date",                      (DL_FUNC) &_cppallytest_test_as_date,                      1},
    {"_cppallytest_test_as_date2",                     (DL_FUNC) &_cppallytest_test_as_date2,                     1},
    {"_cppallytest_test_as_dbl",                       (DL_FUNC) &_cppallytest_test_as_dbl,                       6},
    {"_cppallytest_test_as_int",                       (DL_FUNC) &_cppallytest_test_as_int,                       6},
    {"_cppallytest_test_as_str",                       (DL_FUNC) &_cppallytest_test_as_str,                       6},
    {"_cppallytest_test_as_sym",                       (DL_FUNC) &_cppallytest_test_as_sym,                       6},
    {"_cppallytest_test_attrs",                        (DL_FUNC) &_cppallytest_test_attrs,                        1},
    {"_cppallytest_test_by_const_lvalue_ref",          (DL_FUNC) &_cppallytest_test_by_const_lvalue_ref,          1},
    {"_cppallytest_test_by_lvalue_ref",                (DL_FUNC) &_cppallytest_test_by_lvalue_ref,                1},
    {"_cppallytest_test_by_rvalue_ref",                (DL_FUNC) &_cppallytest_test_by_rvalue_ref,                1},
    {"_cppallytest_test_by_value",                     (DL_FUNC) &_cppallytest_test_by_value,                     1},
    {"_cppallytest_test_coerce",                       (DL_FUNC) &_cppallytest_test_coerce,                       2},
    {"_cppallytest_test_coerce1",                      (DL_FUNC) &_cppallytest_test_coerce1,                      1},
    {"_cppallytest_test_coerce_dbl_to_int64_overflow", (DL_FUNC) &_cppallytest_test_coerce_dbl_to_int64_overflow, 0},
    {"_cppallytest_test_coerce_dbl_to_int_overflow",   (DL_FUNC) &_cppallytest_test_coerce_dbl_to_int_overflow,   0},
    {"_cppallytest_test_coerce_edge",                  (DL_FUNC) &_cppallytest_test_coerce_edge,                  0},
    {"_cppallytest_test_coerce_int64_min_to_int64",    (DL_FUNC) &_cppallytest_test_coerce_int64_min_to_int64,    0},
    {"_cppallytest_test_coerce_int64_to_int_overflow", (DL_FUNC) &_cppallytest_test_coerce_int64_to_int_overflow, 0},
    {"_cppallytest_test_coerce_int_min_to_int",        (DL_FUNC) &_cppallytest_test_coerce_int_min_to_int,        0},
    {"_cppallytest_test_coerce_neg_inf_to_int",        (DL_FUNC) &_cppallytest_test_coerce_neg_inf_to_int,        0},
    {"_cppallytest_test_coerce_pos_inf_to_int",        (DL_FUNC) &_cppallytest_test_coerce_pos_inf_to_int,        0},
    {"_cppallytest_test_combine2",                     (DL_FUNC) &_cppallytest_test_combine2,                     2},
    {"_cppallytest_test_construct_date",               (DL_FUNC) &_cppallytest_test_construct_date,               1},
    {"_cppallytest_test_copy",                         (DL_FUNC) &_cppallytest_test_copy,                         1},
    {"_cppallytest_test_dates1",                       (DL_FUNC) &_cppallytest_test_dates1,                       1},
    {"_cppallytest_test_dates2",                       (DL_FUNC) &_cppallytest_test_dates2,                       1},
    {"_cppallytest_test_deduced_scalar_type",          (DL_FUNC) &_cppallytest_test_deduced_scalar_type,          1},
    {"_cppallytest_test_deduced_scalar_type2",         (DL_FUNC) &_cppallytest_test_deduced_scalar_type2,         1},
    {"_cppallytest_test_deduced_type",                 (DL_FUNC) &_cppallytest_test_deduced_type,                 1},
    {"_cppallytest_test_deduced_vec_type",             (DL_FUNC) &_cppallytest_test_deduced_vec_type,             1},
    {"_cppallytest_test_df",                           (DL_FUNC) &_cppallytest_test_df,                           1},
    {"_cppallytest_test_factor1",                      (DL_FUNC) &_cppallytest_test_factor1,                      1},
    {"_cppallytest_test_factor2",                      (DL_FUNC) &_cppallytest_test_factor2,                      1},
    {"_cppallytest_test_factor3",                      (DL_FUNC) &_cppallytest_test_factor3,                      1},
    {"_cppallytest_test_find",                         (DL_FUNC) &_cppallytest_test_find,                         2},
    {"_cppallytest_test_group_counts",                 (DL_FUNC) &_cppallytest_test_group_counts,                 2},
    {"_cppallytest_test_group_id",                     (DL_FUNC) &_cppallytest_test_group_id,                     2},
    {"_cppallytest_test_identical",                    (DL_FUNC) &_cppallytest_test_identical,                    2},
    {"_cppallytest_test_identity",                     (DL_FUNC) &_cppallytest_test_identity,                     1},
    {"_cppallytest_test_identity2",                    (DL_FUNC) &_cppallytest_test_identity2,                    1},
    {"_cppallytest_test_lengths",                      (DL_FUNC) &_cppallytest_test_lengths,                      1},
    {"_cppallytest_test_lgl",                          (DL_FUNC) &_cppallytest_test_lgl,                          0},
    {"_cppallytest_test_list_to_scalars",              (DL_FUNC) &_cppallytest_test_list_to_scalars,              1},
    {"_cppallytest_test_match",                        (DL_FUNC) &_cppallytest_test_match,                        2},
    {"_cppallytest_test_mean",                         (DL_FUNC) &_cppallytest_test_mean,                         2},
    {"_cppallytest_test_mix2",                         (DL_FUNC) &_cppallytest_test_mix2,                         7},
    {"_cppallytest_test_multiline_template_add",       (DL_FUNC) &_cppallytest_test_multiline_template_add,       2},
    {"_cppallytest_test_multiline_template_add2",      (DL_FUNC) &_cppallytest_test_multiline_template_add2,      2},
    {"_cppallytest_test_multiple_deduction",           (DL_FUNC) &_cppallytest_test_multiple_deduction,           2},
    {"_cppallytest_test_n_unique",                     (DL_FUNC) &_cppallytest_test_n_unique,                     1},
    {"_cppallytest_test_na_types",                     (DL_FUNC) &_cppallytest_test_na_types,                     0},
    {"_cppallytest_test_names_empty",                  (DL_FUNC) &_cppallytest_test_names_empty,                  0},
    {"_cppallytest_test_names_growing",                (DL_FUNC) &_cppallytest_test_names_growing,                0},
    {"_cppallytest_test_names_inplace_mutation",       (DL_FUNC) &_cppallytest_test_names_inplace_mutation,       0},
    {"_cppallytest_test_names_roundtrip_after_grow",   (DL_FUNC) &_cppallytest_test_names_roundtrip_after_grow,   0},
    {"_cppallytest_test_names_set_attr_invalidation",  (DL_FUNC) &_cppallytest_test_names_set_attr_invalidation,  0},
    {"_cppallytest_test_names_shallow_copy_isolation", (DL_FUNC) &_cppallytest_test_names_shallow_copy_isolation, 0},
    {"_cppallytest_test_names_stale_invalidation",     (DL_FUNC) &_cppallytest_test_names_stale_invalidation,     0},
    {"_cppallytest_test_names_sweep",                  (DL_FUNC) &_cppallytest_test_names_sweep,                  0},
    {"_cppallytest_test_nas",                          (DL_FUNC) &_cppallytest_test_nas,                          1},
    {"_cppallytest_test_null",                         (DL_FUNC) &_cppallytest_test_null,                         0},
    {"_cppallytest_test_order",                        (DL_FUNC) &_cppallytest_test_order,                        2},
    {"_cppallytest_test_overflow",                     (DL_FUNC) &_cppallytest_test_overflow,                     0},
    {"_cppallytest_test_protect_burst_reserve",        (DL_FUNC) &_cppallytest_test_protect_burst_reserve,        0},
    {"_cppallytest_test_protect_chunk_growth",         (DL_FUNC) &_cppallytest_test_protect_chunk_growth,         0},
    {"_cppallytest_test_protect_count_tracking",       (DL_FUNC) &_cppallytest_test_protect_count_tracking,       0},
    {"_cppallytest_test_protect_slot_reuse",           (DL_FUNC) &_cppallytest_test_protect_slot_reuse,           0},
    {"_cppallytest_test_range",                        (DL_FUNC) &_cppallytest_test_range,                        2},
    {"_cppallytest_test_rep",                          (DL_FUNC) &_cppallytest_test_rep,                          2},
    {"_cppallytest_test_rep_each",                     (DL_FUNC) &_cppallytest_test_rep_each,                     2},
    {"_cppallytest_test_rep_len",                      (DL_FUNC) &_cppallytest_test_rep_len,                      2},
    {"_cppallytest_test_replace_at",                   (DL_FUNC) &_cppallytest_test_replace_at,                   3},
    {"_cppallytest_test_rval_identity",                (DL_FUNC) &_cppallytest_test_rval_identity,                1},
    {"_cppallytest_test_scalar",                       (DL_FUNC) &_cppallytest_test_scalar,                       2},
    {"_cppallytest_test_scalar2",                      (DL_FUNC) &_cppallytest_test_scalar2,                      2},
    {"_cppallytest_test_scalar3",                      (DL_FUNC) &_cppallytest_test_scalar3,                      2},
    {"_cppallytest_test_sexp",                         (DL_FUNC) &_cppallytest_test_sexp,                         1},
    {"_cppallytest_test_sexp2",                        (DL_FUNC) &_cppallytest_test_sexp2,                        1},
    {"_cppallytest_test_sexp3",                        (DL_FUNC) &_cppallytest_test_sexp3,                        1},
    {"_cppallytest_test_sexp4",                        (DL_FUNC) &_cppallytest_test_sexp4,                        1},
    {"_cppallytest_test_sort",                         (DL_FUNC) &_cppallytest_test_sort,                         2},
    {"_cppallytest_test_specialisation",               (DL_FUNC) &_cppallytest_test_specialisation,               1},
    {"_cppallytest_test_str1",                         (DL_FUNC) &_cppallytest_test_str1,                         1},
    {"_cppallytest_test_str2",                         (DL_FUNC) &_cppallytest_test_str2,                         1},
    {"_cppallytest_test_str3",                         (DL_FUNC) &_cppallytest_test_str3,                         1},
    {"_cppallytest_test_str4",                         (DL_FUNC) &_cppallytest_test_str4,                         1},
    {"_cppallytest_test_subset",                       (DL_FUNC) &_cppallytest_test_subset,                       3},
    {"_cppallytest_test_sum",                          (DL_FUNC) &_cppallytest_test_sum,                          2},
    {"_cppallytest_test_sym",                          (DL_FUNC) &_cppallytest_test_sym,                          1},
    {"_cppallytest_test_temp_by_const_lvalue_ref",     (DL_FUNC) &_cppallytest_test_temp_by_const_lvalue_ref,     1},
    {"_cppallytest_test_temp_by_lvalue_ref",           (DL_FUNC) &_cppallytest_test_temp_by_lvalue_ref,           1},
    {"_cppallytest_test_temp_by_rvalue_ref",           (DL_FUNC) &_cppallytest_test_temp_by_rvalue_ref,           1},
    {"_cppallytest_test_temp_by_value",                (DL_FUNC) &_cppallytest_test_temp_by_value,                1},
    {"_cppallytest_test_template_null",                (DL_FUNC) &_cppallytest_test_template_null,                1},
    {"_cppallytest_test_to_bool",                      (DL_FUNC) &_cppallytest_test_to_bool,                      0},
    {"_cppallytest_test_to_double",                    (DL_FUNC) &_cppallytest_test_to_double,                    0},
    {"_cppallytest_test_to_int",                       (DL_FUNC) &_cppallytest_test_to_int,                       0},
    {"_cppallytest_test_to_int64",                     (DL_FUNC) &_cppallytest_test_to_int64,                     0},
    {"_cppallytest_test_to_r_dbl",                     (DL_FUNC) &_cppallytest_test_to_r_dbl,                     0},
    {"_cppallytest_test_to_r_int",                     (DL_FUNC) &_cppallytest_test_to_r_int,                     0},
    {"_cppallytest_test_to_r_int64",                   (DL_FUNC) &_cppallytest_test_to_r_int64,                   0},
    {"_cppallytest_test_to_r_lgl",                     (DL_FUNC) &_cppallytest_test_to_r_lgl,                     0},
    {"_cppallytest_test_to_r_size_t",                  (DL_FUNC) &_cppallytest_test_to_r_size_t,                  0},
    {"_cppallytest_test_to_uint",                      (DL_FUNC) &_cppallytest_test_to_uint,                      0},
    {"_cppallytest_test_tz",                           (DL_FUNC) &_cppallytest_test_tz,                           1},
    {"_cppallytest_test_unique",                       (DL_FUNC) &_cppallytest_test_unique,                       1},
    {"_cppallytest_test_valgrind",                     (DL_FUNC) &_cppallytest_test_valgrind,                     0},
    {"_cppallytest_test_var",                          (DL_FUNC) &_cppallytest_test_var,                          2},
    {"_cppallytest_vec_is_na",                         (DL_FUNC) &_cppallytest_vec_is_na,                         1},
    {"_cppallytest_vector1",                           (DL_FUNC) &_cppallytest_vector1,                           1},
    {"_cppallytest_vector2",                           (DL_FUNC) &_cppallytest_vector2,                           1},
    {NULL, NULL, 0}
};
}


void foo(DllInfo* dll);
void bar(DllInfo* dll);

extern "C" attribute_visible void R_init_cppallytest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  foo(dll);
  bar(dll);
  R_forceSymbols(dll, TRUE);
}
