// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>
#include "readme.h"
#include "test.h"
#include "test_nas.h"
#include "test_refs.h"
#include "test_sort.h"
#include "test_stats.h"
#include "test_subset.h"

using namespace cppally;
using internal::cpp_to_r;
using internal::dispatch_template_impl;

// readme.h
extern "C" SEXP _cppallytest_scalar_init(SEXP ptype) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP ptype_internal) -> decltype(cpp_to_r(::scalar_init(std::declval<decltype(as<T>(ptype_internal))&>()))) {
        auto ptype_arg = as<T>(ptype_internal);
        return cpp_to_r(::scalar_init(ptype_arg));
    },
    ptype
  );
  END_CPPALLY
}
// readme.h
r_int64 as_int64(r_int x);
extern "C" SEXP _cppallytest_as_int64(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_int>(x);
  return cpp_to_r(::as_int64(x_arg));
  END_CPPALLY
}
// readme.h
r_size_t as_r_size_t(r_int x);
extern "C" SEXP _cppallytest_as_r_size_t(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_int>(x);
  return cpp_to_r(::as_r_size_t(x_arg));
  END_CPPALLY
}
// readme.h
extern "C" SEXP _cppallytest_cpp_length(SEXP vec) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP vec_internal) -> decltype(cpp_to_r(::cpp_length(std::declval<decltype(as<T>(vec_internal))&>()))) {
        auto vec_arg = as<T>(vec_internal);
        return cpp_to_r(::cpp_length(vec_arg));
    },
    vec
  );
  END_CPPALLY
}
// readme.h
r_dbl add_half(r_dbl x);
extern "C" SEXP _cppallytest_add_half(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_dbl>(x);
  return cpp_to_r(::add_half(x_arg));
  END_CPPALLY
}
// readme.h
r_str symbol_to_string(r_sym x);
extern "C" SEXP _cppallytest_symbol_to_string(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_sym>(x);
  return cpp_to_r(::symbol_to_string(x_arg));
  END_CPPALLY
}
// readme.h
r_factors new_factor(r_vec<r_str> x);
extern "C" SEXP _cppallytest_new_factor(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_str>>(x);
  return cpp_to_r(::new_factor(x_arg));
  END_CPPALLY
}
// readme.h
r_vec<r_int> factor_codes(r_factors x);
extern "C" SEXP _cppallytest_factor_codes(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_factors>(x);
  return cpp_to_r(::factor_codes(x_arg));
  END_CPPALLY
}
// readme.h
r_vec<r_int> cpp_lengths(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_cpp_lengths(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<const r_vec<r_sexp>&>(x);
  return cpp_to_r(::cpp_lengths(x_arg));
  END_CPPALLY
}
// readme.h
r_vec<r_int> cpp_lengths2(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_cpp_lengths2(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<const r_vec<r_sexp>&>(x);
  return cpp_to_r(::cpp_lengths2(x_arg));
  END_CPPALLY
}
// readme.h
r_int double_to_int(r_dbl x);
extern "C" SEXP _cppallytest_double_to_int(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_dbl>(x);
  return cpp_to_r(::double_to_int(x_arg));
  END_CPPALLY
}
// readme.h
r_vec<r_int> to_int_vec(r_vec<r_dbl> x);
extern "C" SEXP _cppallytest_to_int_vec(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_dbl>>(x);
  return cpp_to_r(::to_int_vec(x_arg));
  END_CPPALLY
}
// readme.h
r_vec<r_sexp> coercions();
extern "C" SEXP _cppallytest_coercions() {
  BEGIN_CPPALLY
  return cpp_to_r(::coercions());
  END_CPPALLY
}
// readme.h
int cpp_na_count(r_vec<r_str> x);
extern "C" SEXP _cppallytest_cpp_na_count(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_str>>(x);
  return cpp_to_r(::cpp_na_count(x_arg));
  END_CPPALLY
}
// readme.h
int C_na_count(SEXP x);
extern "C" SEXP _cppallytest_C_na_count(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::C_na_count(x_arg));
  END_CPPALLY
}
// readme.h
int cpp_fast_na_count(r_vec<r_str_view> x);
extern "C" SEXP _cppallytest_cpp_fast_na_count(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_str_view>>(x);
  return cpp_to_r(::cpp_fast_na_count(x_arg));
  END_CPPALLY
}
// readme.h
int cpp_fast_na_count_v2(r_vec<r_str> x);
extern "C" SEXP _cppallytest_cpp_fast_na_count_v2(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_str>>(x);
  return cpp_to_r(::cpp_fast_na_count_v2(x_arg));
  END_CPPALLY
}
// test.cpp
void cpp_set_threads(int n);
extern "C" SEXP _cppallytest_cpp_set_threads(SEXP n) {
  BEGIN_CPPALLY
  auto n_arg = as<int>(n);
  ::cpp_set_threads(n_arg);
  return R_NilValue;
  END_CPPALLY
}
// test.cpp
r_int cpp_get_threads();
extern "C" SEXP _cppallytest_cpp_get_threads() {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_get_threads());
  END_CPPALLY
}
// test.cpp
r_int cpp_get_max_threads();
extern "C" SEXP _cppallytest_cpp_get_max_threads() {
  BEGIN_CPPALLY
  return cpp_to_r(::cpp_get_max_threads());
  END_CPPALLY
}
// test.cpp
r_str cpp_typeof(SEXP x);
extern "C" SEXP _cppallytest_cpp_typeof(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::cpp_typeof(x_arg));
  END_CPPALLY
}
// test.cpp
SEXP test_identity2(SEXP x);
extern "C" SEXP _cppallytest_test_identity2(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::test_identity2(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_str> test_str1(r_str x);
extern "C" SEXP _cppallytest_test_str1(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_str>(x);
  return cpp_to_r(::test_str1(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_str_view> test_str2(r_str_view x);
extern "C" SEXP _cppallytest_test_str2(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_str_view>(x);
  return cpp_to_r(::test_str2(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_as_date(SEXP x);
extern "C" SEXP _cppallytest_test_as_date(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::test_as_date(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_construct_date(SEXP x);
extern "C" SEXP _cppallytest_test_construct_date(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::test_construct_date(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_as_date2(r_vec<r_date> x);
extern "C" SEXP _cppallytest_test_as_date2(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_date>>(x);
  return cpp_to_r(::test_as_date2(x_arg));
  END_CPPALLY
}
// test.cpp
r_sexp test_null();
extern "C" SEXP _cppallytest_test_null() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_null());
  END_CPPALLY
}
// test.cpp
r_sym test_sym(r_sym x);
extern "C" SEXP _cppallytest_test_sym(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_sym>(x);
  return cpp_to_r(::test_sym(x_arg));
  END_CPPALLY
}
// test.cpp
r_sexp test_sexp2(r_sexp x);
extern "C" SEXP _cppallytest_test_sexp2(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_sexp>(x);
  return cpp_to_r(::test_sexp2(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_sexp> test_sexp3(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_test_sexp3(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_sexp>>(x);
  return cpp_to_r(::test_sexp3(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_int> test_coerce1(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_test_coerce1(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<const r_vec<r_sexp>&>(x);
  return cpp_to_r(::test_coerce1(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_date> test_dates1(r_vec<r_date> x);
extern "C" SEXP _cppallytest_test_dates1(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_date>>(x);
  return cpp_to_r(::test_dates1(x_arg));
  END_CPPALLY
}
// test.cpp
r_str test_tz(r_vec<r_psxct> x);
extern "C" SEXP _cppallytest_test_tz(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_psxct>>(x);
  return cpp_to_r(::test_tz(x_arg));
  END_CPPALLY
}
// test.cpp
r_vec<r_int> test_lengths(const r_vec<r_sexp>& x);
extern "C" SEXP _cppallytest_test_lengths(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<const r_vec<r_sexp>&>(x);
  return cpp_to_r(::test_lengths(x_arg));
  END_CPPALLY
}
// test.cpp
r_lgl test_lgl();
extern "C" SEXP _cppallytest_test_lgl() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_lgl());
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_type(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_deduced_type(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiple_deduction(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_multiple_deduction(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<T>(y_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto y_arg = as<T>(y_internal);
        return cpp_to_r(::test_multiple_deduction(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_vec_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_vec_type(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_deduced_vec_type(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_scalar_type(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_scalar_type(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_deduced_scalar_type(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_deduced_scalar_type2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_deduced_scalar_type2(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_deduced_scalar_type2(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_identity(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_identity(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_identity(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_template_null(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_template_null(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_template_null(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_scalar(std::declval<decltype(as<int>(x_internal))&>(), std::declval<decltype(as<T>(y_internal))&>()))) {
        auto x_arg = as<int>(x_internal); auto y_arg = as<T>(y_internal);
        return cpp_to_r(::test_scalar(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_scalar2(std::declval<decltype(as<r_int>(x_internal))&>(), std::declval<decltype(as<T>(y_internal))&>()))) {
        auto x_arg = as<r_int>(x_internal); auto y_arg = as<T>(y_internal);
        return cpp_to_r(::test_scalar2(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_scalar3(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_scalar3(std::declval<decltype(as<r_int>(x_internal))&>(), std::declval<decltype(as<T>(y_internal))&>()))) {
        auto x_arg = as<r_int>(x_internal); auto y_arg = as<T>(y_internal);
        return cpp_to_r(::test_scalar3(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_rval_identity(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_rval_identity(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_rval_identity(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar1(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::scalar1(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::scalar1(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::scalar2(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::scalar2(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_vector1(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::vector1(std::declval<decltype(as<r_vec<T>>(x_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal);
        return cpp_to_r(::vector1(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_vector2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::vector2(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::vector2(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar3(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::scalar3(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<T>(y_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto y_arg = as<T>(y_internal);
        return cpp_to_r(::scalar3(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar4(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::scalar4(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<U>(y_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto y_arg = as<U>(y_internal);
        return cpp_to_r(::scalar4(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_sexp(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_sexp(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_sexp(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_sexp4(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_sexp4(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_sexp4(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec1(SEXP a, SEXP b) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_r(::scalar_vec1(std::declval<decltype(as<r_vec<T>>(a_internal))&>(), std::declval<decltype(as<T>(b_internal))&>()))) {
        auto a_arg = as<r_vec<T>>(a_internal); auto b_arg = as<T>(b_internal);
        return cpp_to_r(::scalar_vec1(a_arg, b_arg));
    },
    a, b
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec2(SEXP a, SEXP b) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_r(::scalar_vec2(std::declval<decltype(as<r_vec<T>>(a_internal))&>(), std::declval<decltype(as<U>(b_internal))&>()))) {
        auto a_arg = as<r_vec<T>>(a_internal); auto b_arg = as<U>(b_internal);
        return cpp_to_r(::scalar_vec2(a_arg, b_arg));
    },
    a, b
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_scalar_vec3(SEXP z, SEXP x, SEXP y, SEXP a) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 4, std::array<int, 4>{0, 0, 1, 1}>(
    []<typename T, typename U>(SEXP z_internal, SEXP x_internal, SEXP y_internal, SEXP a_internal) -> decltype(cpp_to_r(::scalar_vec3(std::declval<decltype(as<r_vec<T>>(z_internal))&>(), std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<U>(y_internal))&>(), std::declval<decltype(as<r_vec<U>>(a_internal))&>()))) {
        auto z_arg = as<r_vec<T>>(z_internal); auto x_arg = as<T>(x_internal); auto y_arg = as<U>(y_internal); auto a_arg = as<r_vec<U>>(a_internal);
        return cpp_to_r(::scalar_vec3(z_arg, x_arg, y_arg, a_arg));
    },
    z, x, y, a
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_mix2(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f, SEXP g) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 7, std::array<int, 7>{0, -1, 0, -1, 0, 0, 1}>(
    []<typename T, typename V>(SEXP a_internal, SEXP b_internal, SEXP c_internal, SEXP d_internal, SEXP e_internal, SEXP f_internal, SEXP g_internal) -> decltype(cpp_to_r(::test_mix2(std::declval<decltype(as<r_vec<T>>(a_internal))&>(), std::declval<decltype(as<double>(b_internal))&>(), std::declval<decltype(as<T>(c_internal))&>(), std::declval<decltype(as<int>(d_internal))&>(), std::declval<decltype(as<T>(e_internal))&>(), std::declval<decltype(as<T>(f_internal))&>(), std::declval<decltype(as<V>(g_internal))&>()))) {
        auto a_arg = as<r_vec<T>>(a_internal); auto b_arg = as<double>(b_internal); auto c_arg = as<T>(c_internal); auto d_arg = as<int>(d_internal); auto e_arg = as<T>(e_internal); auto f_arg = as<T>(f_internal); auto g_arg = as<V>(g_internal);
        return cpp_to_r(::test_mix2(a_arg, b_arg, c_arg, d_arg, e_arg, f_arg, g_arg));
    },
    a, b, c, d, e, f, g
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_str3(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_str3(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_str3(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_str4(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_str4(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_str4(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_specialisation(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_specialisation(std::declval<decltype(as<r_vec<T>>(x_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal);
        return cpp_to_r(::test_specialisation(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_coerce(SEXP x, SEXP ptype) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP ptype_internal) -> decltype(cpp_to_r(::test_coerce(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<U>(ptype_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto ptype_arg = as<U>(ptype_internal);
        return cpp_to_r(::test_coerce(x_arg, ptype_arg));
    },
    x, ptype
  );
  END_CPPALLY
}
// test.h
SEXP test_list_to_scalars(r_vec<r_sexp> x);
extern "C" SEXP _cppallytest_test_list_to_scalars(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_sexp>>(x);
  return cpp_to_r(::test_list_to_scalars(x_arg));
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_combine2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_combine2(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<T>(y_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto y_arg = as<T>(y_internal);
        return cpp_to_r(::test_combine2(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_dates2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_dates2(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_dates2(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_unique(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_unique(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_unique(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_seqs(SEXP size, SEXP from, SEXP by) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{-1, 0, 1}>(
    []<typename U, typename V>(SEXP size_internal, SEXP from_internal, SEXP by_internal) -> decltype(cpp_to_r(::test_seqs(std::declval<decltype(as<r_vec<r_int>>(size_internal))&>(), std::declval<decltype(as<r_vec<U>>(from_internal))&>(), std::declval<decltype(as<r_vec<V>>(by_internal))&>()))) {
        auto size_arg = as<r_vec<r_int>>(size_internal); auto from_arg = as<r_vec<U>>(from_internal); auto by_arg = as<r_vec<V>>(by_internal);
        return cpp_to_r(::test_seqs(size_arg, from_arg, by_arg));
    },
    size, from, by
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_group_id(SEXP x, SEXP order) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_r(::test_group_id(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<bool>(order_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto order_arg = as<bool>(order_internal);
        return cpp_to_r(::test_group_id(x_arg, order_arg));
    },
    x, order
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_group_counts(SEXP x, SEXP order) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_r(::test_group_counts(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<bool>(order_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto order_arg = as<bool>(order_internal);
        return cpp_to_r(::test_group_counts(x_arg, order_arg));
    },
    x, order
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_match(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_match(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<r_vec<T>>(y_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto y_arg = as<r_vec<T>>(y_internal);
        return cpp_to_r(::test_match(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_factor2(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_factor2(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_factor2(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_n_unique(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_n_unique(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_n_unique(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test.h
SEXP test_copy(SEXP x);
extern "C" SEXP _cppallytest_test_copy(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::test_copy(x_arg));
  END_CPPALLY
}
// test.h
bool test_identical(SEXP x, SEXP y);
extern "C" SEXP _cppallytest_test_identical(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  auto y_arg = as<SEXP>(y);
  return cpp_to_r(::test_identical(x_arg, y_arg));
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiline_template_add(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_multiline_template_add(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<U>(y_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto y_arg = as<U>(y_internal);
        return cpp_to_r(::test_multiline_template_add(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test.h
extern "C" SEXP _cppallytest_test_multiline_template_add2(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_multiline_template_add2(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<U>(y_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto y_arg = as<U>(y_internal);
        return cpp_to_r(::test_multiline_template_add2(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test_attrs.cpp
r_vec<r_sexp> test_attrs(SEXP x);
extern "C" SEXP _cppallytest_test_attrs(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<SEXP>(x);
  return cpp_to_r(::test_attrs(x_arg));
  END_CPPALLY
}
// test_attrs.cpp
r_vec<r_sexp> test_df(r_vec<r_sexp> cols);
extern "C" SEXP _cppallytest_test_df(SEXP cols) {
  BEGIN_CPPALLY
  auto cols_arg = as<r_vec<r_sexp>>(cols);
  return cpp_to_r(::test_df(cols_arg));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_sym(SEXP a, r_str b, r_dbl c, r_sym d, r_vec<r_str> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_sym(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  auto a_arg = as<SEXP>(a);
  auto b_arg = as<r_str>(b);
  auto c_arg = as<r_dbl>(c);
  auto d_arg = as<r_sym>(d);
  auto e_arg = as<r_vec<r_str>>(e);
  auto f_arg = as<r_vec<r_dbl>>(f);
  return cpp_to_r(::test_as_sym(a_arg, b_arg, c_arg, d_arg, e_arg, f_arg));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_int(SEXP a, r_str b, r_dbl c, r_sym d, r_vec<r_str> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_int(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  auto a_arg = as<SEXP>(a);
  auto b_arg = as<r_str>(b);
  auto c_arg = as<r_dbl>(c);
  auto d_arg = as<r_sym>(d);
  auto e_arg = as<r_vec<r_str>>(e);
  auto f_arg = as<r_vec<r_dbl>>(f);
  return cpp_to_r(::test_as_int(a_arg, b_arg, c_arg, d_arg, e_arg, f_arg));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_dbl(SEXP a, r_str b, r_int c, r_sym d, r_vec<r_str> e, r_vec<r_int> f);
extern "C" SEXP _cppallytest_test_as_dbl(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  auto a_arg = as<SEXP>(a);
  auto b_arg = as<r_str>(b);
  auto c_arg = as<r_int>(c);
  auto d_arg = as<r_sym>(d);
  auto e_arg = as<r_vec<r_str>>(e);
  auto f_arg = as<r_vec<r_int>>(f);
  return cpp_to_r(::test_as_dbl(a_arg, b_arg, c_arg, d_arg, e_arg, f_arg));
  END_CPPALLY
}
// test_coerce.cpp
SEXP test_as_str(SEXP a, r_int b, r_dbl c, r_sym d, r_vec<r_int> e, r_vec<r_dbl> f);
extern "C" SEXP _cppallytest_test_as_str(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f) {
  BEGIN_CPPALLY
  auto a_arg = as<SEXP>(a);
  auto b_arg = as<r_int>(b);
  auto c_arg = as<r_dbl>(c);
  auto d_arg = as<r_sym>(d);
  auto e_arg = as<r_vec<r_int>>(e);
  auto f_arg = as<r_vec<r_dbl>>(f);
  return cpp_to_r(::test_as_str(a_arg, b_arg, c_arg, d_arg, e_arg, f_arg));
  END_CPPALLY
}
// test_factor.cpp
r_vec<r_sexp> test_factor1(r_factors x);
extern "C" SEXP _cppallytest_test_factor1(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_factors>(x);
  return cpp_to_r(::test_factor1(x_arg));
  END_CPPALLY
}
// test_factor.cpp
r_dbl test_factor3(r_factors x);
extern "C" SEXP _cppallytest_test_factor3(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_factors>(x);
  return cpp_to_r(::test_factor3(x_arg));
  END_CPPALLY
}
// test_names.cpp
r_vec<r_str_view> test_names_inplace_mutation();
extern "C" SEXP _cppallytest_test_names_inplace_mutation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_inplace_mutation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_stale_invalidation();
extern "C" SEXP _cppallytest_test_names_stale_invalidation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_stale_invalidation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_set_attr_invalidation();
extern "C" SEXP _cppallytest_test_names_set_attr_invalidation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_set_attr_invalidation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_growing();
extern "C" SEXP _cppallytest_test_names_growing() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_growing());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_sweep();
extern "C" SEXP _cppallytest_test_names_sweep() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_sweep());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_shallow_copy_isolation();
extern "C" SEXP _cppallytest_test_names_shallow_copy_isolation() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_shallow_copy_isolation());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_empty();
extern "C" SEXP _cppallytest_test_names_empty() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_empty());
  END_CPPALLY
}
// test_names.cpp
r_lgl test_names_roundtrip_after_grow();
extern "C" SEXP _cppallytest_test_names_roundtrip_after_grow() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_names_roundtrip_after_grow());
  END_CPPALLY
}
// test_nas.h
extern "C" SEXP _cppallytest_test_nas(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_nas(std::declval<decltype(as<T const&>(x_internal))&>()))) {
        auto x_arg = as<T const&>(x_internal);
        return cpp_to_r(::test_nas(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test_nas.h
inline r_vec<r_sexp> test_na_types();
extern "C" SEXP _cppallytest_test_na_types() {
  BEGIN_CPPALLY
  return cpp_to_r(::test_na_types());
  END_CPPALLY
}
// test_protect.cpp
double bench_protect_insert_release_cppally(int n);
extern "C" SEXP _cppallytest_bench_protect_insert_release_cppally(SEXP n) {
  BEGIN_CPPALLY
  auto n_arg = as<int>(n);
  return cpp_to_r(::bench_protect_insert_release_cppally(n_arg));
  END_CPPALLY
}
// test_protect.cpp
double bench_protect_copy_cppally(int n);
extern "C" SEXP _cppallytest_bench_protect_copy_cppally(SEXP n) {
  BEGIN_CPPALLY
  auto n_arg = as<int>(n);
  return cpp_to_r(::bench_protect_copy_cppally(n_arg));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_value(r_vec<r_dbl> x);
extern "C" SEXP _cppallytest_test_by_value(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_dbl>>(x);
  return cpp_to_r(::test_by_value(x_arg));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_lvalue_ref(r_vec<r_dbl>& x);
extern "C" SEXP _cppallytest_test_by_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<r_vec<r_dbl>&>(x);
  return cpp_to_r(::test_by_lvalue_ref(x_arg));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_rvalue_ref(r_vec<r_dbl>&& x);
extern "C" SEXP _cppallytest_test_by_rvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::test_by_rvalue_ref(as<r_vec<r_dbl>&&>(x)));
  END_CPPALLY
}
// test_refs.h
SEXP test_by_const_lvalue_ref(const r_vec<r_dbl>& x);
extern "C" SEXP _cppallytest_test_by_const_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  auto x_arg = as<const r_vec<r_dbl>&>(x);
  return cpp_to_r(::test_by_const_lvalue_ref(x_arg));
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_value(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_value(std::declval<decltype(as<T>(x_internal))&>()))) {
        auto x_arg = as<T>(x_internal);
        return cpp_to_r(::test_temp_by_value(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_lvalue_ref(std::declval<decltype(as<T&>(x_internal))&>()))) {
        auto x_arg = as<T&>(x_internal);
        return cpp_to_r(::test_temp_by_lvalue_ref(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_rvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_rvalue_ref(as<T&&>(x_internal)))) {
        
        return cpp_to_r(::test_temp_by_rvalue_ref(as<T&&>(x_internal)));
    },
    x
  );
  END_CPPALLY
}
// test_refs.h
extern "C" SEXP _cppallytest_test_temp_by_const_lvalue_ref(SEXP x) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_r(::test_temp_by_const_lvalue_ref(std::declval<decltype(as<const T&>(x_internal))&>()))) {
        auto x_arg = as<const T&>(x_internal);
        return cpp_to_r(::test_temp_by_const_lvalue_ref(x_arg));
    },
    x
  );
  END_CPPALLY
}
// test_sort.h
extern "C" SEXP _cppallytest_test_order(SEXP x, SEXP preserve_ties) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_r(::test_order(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<bool>(preserve_ties_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto preserve_ties_arg = as<bool>(preserve_ties_internal);
        return cpp_to_r(::test_order(x_arg, preserve_ties_arg));
    },
    x, preserve_ties
  );
  END_CPPALLY
}
// test_sort.h
extern "C" SEXP _cppallytest_test_sort(SEXP x, SEXP preserve_ties) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_r(::test_sort(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<bool>(preserve_ties_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto preserve_ties_arg = as<bool>(preserve_ties_internal);
        return cpp_to_r(::test_sort(x_arg, preserve_ties_arg));
    },
    x, preserve_ties
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_range(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_range(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<bool>(na_rm_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto na_rm_arg = as<bool>(na_rm_internal);
        return cpp_to_r(::test_range(x_arg, na_rm_arg));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_sum(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<bool>(na_rm_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto na_rm_arg = as<bool>(na_rm_internal);
        return cpp_to_r(::test_sum(x_arg, na_rm_arg));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_mean(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_mean(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<bool>(na_rm_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto na_rm_arg = as<bool>(na_rm_internal);
        return cpp_to_r(::test_mean(x_arg, na_rm_arg));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_stats.h
extern "C" SEXP _cppallytest_test_var(SEXP x, SEXP na_rm) {
  BEGIN_CPPALLY
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_r(::test_var(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<bool>(na_rm_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto na_rm_arg = as<bool>(na_rm_internal);
        return cpp_to_r(::test_var(x_arg, na_rm_arg));
    },
    x, na_rm
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_subset(SEXP x, SEXP i, SEXP invert) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, -1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP i_internal, SEXP invert_internal) -> decltype(cpp_to_r(::test_subset(std::declval<decltype(as<T>(x_internal))&>(), std::declval<decltype(as<r_vec<U>>(i_internal))&>(), std::declval<decltype(as<bool>(invert_internal))&>()))) {
        auto x_arg = as<T>(x_internal); auto i_arg = as<r_vec<U>>(i_internal); auto invert_arg = as<bool>(invert_internal);
        return cpp_to_r(::test_subset(x_arg, i_arg, invert_arg));
    },
    x, i, invert
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_fill(SEXP x, SEXP where, SEXP with) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, -1, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP where_internal, SEXP with_internal) -> decltype(cpp_to_r(::test_fill(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<r_vec<r_int>>(where_internal))&>(), std::declval<decltype(as<r_vec<U>>(with_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto where_arg = as<r_vec<r_int>>(where_internal); auto with_arg = as<r_vec<U>>(with_internal);
        return cpp_to_r(::test_fill(x_arg, where_arg, with_arg));
    },
    x, where, with
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_counts(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_counts(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<r_vec<U>>(y_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto y_arg = as<r_vec<U>>(y_internal);
        return cpp_to_r(::test_counts(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_remove(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_remove(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<r_vec<U>>(y_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto y_arg = as<r_vec<U>>(y_internal);
        return cpp_to_r(::test_remove(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_find(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_r(::test_find(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<r_vec<U>>(y_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto y_arg = as<r_vec<U>>(y_internal);
        return cpp_to_r(::test_find(x_arg, y_arg));
    },
    x, y
  );
  END_CPPALLY
}
// test_subset.h
extern "C" SEXP _cppallytest_test_replace(SEXP x, SEXP y, SEXP z) {
  BEGIN_CPPALLY
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal, SEXP z_internal) -> decltype(cpp_to_r(::test_replace(std::declval<decltype(as<r_vec<T>>(x_internal))&>(), std::declval<decltype(as<r_vec<U>>(y_internal))&>(), std::declval<decltype(as<r_vec<U>>(z_internal))&>()))) {
        auto x_arg = as<r_vec<T>>(x_internal); auto y_arg = as<r_vec<U>>(y_internal); auto z_arg = as<r_vec<U>>(z_internal);
        return cpp_to_r(::test_replace(x_arg, y_arg, z_arg));
    },
    x, y, z
  );
  END_CPPALLY
}
// test_valgrind.cpp
void test_valgrind();
extern "C" SEXP _cppallytest_test_valgrind() {
  BEGIN_CPPALLY
  ::test_valgrind();
  return R_NilValue;
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cppallytest_C_na_count",                           (DL_FUNC) &_cppallytest_C_na_count,                           1},
    {"_cppallytest_add_half",                             (DL_FUNC) &_cppallytest_add_half,                             1},
    {"_cppallytest_as_int64",                             (DL_FUNC) &_cppallytest_as_int64,                             1},
    {"_cppallytest_as_r_size_t",                          (DL_FUNC) &_cppallytest_as_r_size_t,                          1},
    {"_cppallytest_bench_protect_copy_cppally",           (DL_FUNC) &_cppallytest_bench_protect_copy_cppally,           1},
    {"_cppallytest_bench_protect_insert_release_cppally", (DL_FUNC) &_cppallytest_bench_protect_insert_release_cppally, 1},
    {"_cppallytest_coercions",                            (DL_FUNC) &_cppallytest_coercions,                            0},
    {"_cppallytest_cpp_fast_na_count",                    (DL_FUNC) &_cppallytest_cpp_fast_na_count,                    1},
    {"_cppallytest_cpp_fast_na_count_v2",                 (DL_FUNC) &_cppallytest_cpp_fast_na_count_v2,                 1},
    {"_cppallytest_cpp_get_max_threads",                  (DL_FUNC) &_cppallytest_cpp_get_max_threads,                  0},
    {"_cppallytest_cpp_get_threads",                      (DL_FUNC) &_cppallytest_cpp_get_threads,                      0},
    {"_cppallytest_cpp_length",                           (DL_FUNC) &_cppallytest_cpp_length,                           1},
    {"_cppallytest_cpp_lengths",                          (DL_FUNC) &_cppallytest_cpp_lengths,                          1},
    {"_cppallytest_cpp_lengths2",                         (DL_FUNC) &_cppallytest_cpp_lengths2,                         1},
    {"_cppallytest_cpp_na_count",                         (DL_FUNC) &_cppallytest_cpp_na_count,                         1},
    {"_cppallytest_cpp_set_threads",                      (DL_FUNC) &_cppallytest_cpp_set_threads,                      1},
    {"_cppallytest_cpp_typeof",                           (DL_FUNC) &_cppallytest_cpp_typeof,                           1},
    {"_cppallytest_double_to_int",                        (DL_FUNC) &_cppallytest_double_to_int,                        1},
    {"_cppallytest_factor_codes",                         (DL_FUNC) &_cppallytest_factor_codes,                         1},
    {"_cppallytest_new_factor",                           (DL_FUNC) &_cppallytest_new_factor,                           1},
    {"_cppallytest_scalar1",                              (DL_FUNC) &_cppallytest_scalar1,                              1},
    {"_cppallytest_scalar2",                              (DL_FUNC) &_cppallytest_scalar2,                              1},
    {"_cppallytest_scalar3",                              (DL_FUNC) &_cppallytest_scalar3,                              2},
    {"_cppallytest_scalar4",                              (DL_FUNC) &_cppallytest_scalar4,                              2},
    {"_cppallytest_scalar_init",                          (DL_FUNC) &_cppallytest_scalar_init,                          1},
    {"_cppallytest_scalar_vec1",                          (DL_FUNC) &_cppallytest_scalar_vec1,                          2},
    {"_cppallytest_scalar_vec2",                          (DL_FUNC) &_cppallytest_scalar_vec2,                          2},
    {"_cppallytest_scalar_vec3",                          (DL_FUNC) &_cppallytest_scalar_vec3,                          4},
    {"_cppallytest_symbol_to_string",                     (DL_FUNC) &_cppallytest_symbol_to_string,                     1},
    {"_cppallytest_test_as_date",                         (DL_FUNC) &_cppallytest_test_as_date,                         1},
    {"_cppallytest_test_as_date2",                        (DL_FUNC) &_cppallytest_test_as_date2,                        1},
    {"_cppallytest_test_as_dbl",                          (DL_FUNC) &_cppallytest_test_as_dbl,                          6},
    {"_cppallytest_test_as_int",                          (DL_FUNC) &_cppallytest_test_as_int,                          6},
    {"_cppallytest_test_as_str",                          (DL_FUNC) &_cppallytest_test_as_str,                          6},
    {"_cppallytest_test_as_sym",                          (DL_FUNC) &_cppallytest_test_as_sym,                          6},
    {"_cppallytest_test_attrs",                           (DL_FUNC) &_cppallytest_test_attrs,                           1},
    {"_cppallytest_test_by_const_lvalue_ref",             (DL_FUNC) &_cppallytest_test_by_const_lvalue_ref,             1},
    {"_cppallytest_test_by_lvalue_ref",                   (DL_FUNC) &_cppallytest_test_by_lvalue_ref,                   1},
    {"_cppallytest_test_by_rvalue_ref",                   (DL_FUNC) &_cppallytest_test_by_rvalue_ref,                   1},
    {"_cppallytest_test_by_value",                        (DL_FUNC) &_cppallytest_test_by_value,                        1},
    {"_cppallytest_test_coerce",                          (DL_FUNC) &_cppallytest_test_coerce,                          2},
    {"_cppallytest_test_coerce1",                         (DL_FUNC) &_cppallytest_test_coerce1,                         1},
    {"_cppallytest_test_combine2",                        (DL_FUNC) &_cppallytest_test_combine2,                        2},
    {"_cppallytest_test_construct_date",                  (DL_FUNC) &_cppallytest_test_construct_date,                  1},
    {"_cppallytest_test_copy",                            (DL_FUNC) &_cppallytest_test_copy,                            1},
    {"_cppallytest_test_counts",                          (DL_FUNC) &_cppallytest_test_counts,                          2},
    {"_cppallytest_test_dates1",                          (DL_FUNC) &_cppallytest_test_dates1,                          1},
    {"_cppallytest_test_dates2",                          (DL_FUNC) &_cppallytest_test_dates2,                          1},
    {"_cppallytest_test_deduced_scalar_type",             (DL_FUNC) &_cppallytest_test_deduced_scalar_type,             1},
    {"_cppallytest_test_deduced_scalar_type2",            (DL_FUNC) &_cppallytest_test_deduced_scalar_type2,            1},
    {"_cppallytest_test_deduced_type",                    (DL_FUNC) &_cppallytest_test_deduced_type,                    1},
    {"_cppallytest_test_deduced_vec_type",                (DL_FUNC) &_cppallytest_test_deduced_vec_type,                1},
    {"_cppallytest_test_df",                              (DL_FUNC) &_cppallytest_test_df,                              1},
    {"_cppallytest_test_factor1",                         (DL_FUNC) &_cppallytest_test_factor1,                         1},
    {"_cppallytest_test_factor2",                         (DL_FUNC) &_cppallytest_test_factor2,                         1},
    {"_cppallytest_test_factor3",                         (DL_FUNC) &_cppallytest_test_factor3,                         1},
    {"_cppallytest_test_fill",                            (DL_FUNC) &_cppallytest_test_fill,                            3},
    {"_cppallytest_test_find",                            (DL_FUNC) &_cppallytest_test_find,                            2},
    {"_cppallytest_test_group_counts",                    (DL_FUNC) &_cppallytest_test_group_counts,                    2},
    {"_cppallytest_test_group_id",                        (DL_FUNC) &_cppallytest_test_group_id,                        2},
    {"_cppallytest_test_identical",                       (DL_FUNC) &_cppallytest_test_identical,                       2},
    {"_cppallytest_test_identity",                        (DL_FUNC) &_cppallytest_test_identity,                        1},
    {"_cppallytest_test_identity2",                       (DL_FUNC) &_cppallytest_test_identity2,                       1},
    {"_cppallytest_test_lengths",                         (DL_FUNC) &_cppallytest_test_lengths,                         1},
    {"_cppallytest_test_lgl",                             (DL_FUNC) &_cppallytest_test_lgl,                             0},
    {"_cppallytest_test_list_to_scalars",                 (DL_FUNC) &_cppallytest_test_list_to_scalars,                 1},
    {"_cppallytest_test_match",                           (DL_FUNC) &_cppallytest_test_match,                           2},
    {"_cppallytest_test_mean",                            (DL_FUNC) &_cppallytest_test_mean,                            2},
    {"_cppallytest_test_mix2",                            (DL_FUNC) &_cppallytest_test_mix2,                            7},
    {"_cppallytest_test_multiline_template_add",          (DL_FUNC) &_cppallytest_test_multiline_template_add,          2},
    {"_cppallytest_test_multiline_template_add2",         (DL_FUNC) &_cppallytest_test_multiline_template_add2,         2},
    {"_cppallytest_test_multiple_deduction",              (DL_FUNC) &_cppallytest_test_multiple_deduction,              2},
    {"_cppallytest_test_n_unique",                        (DL_FUNC) &_cppallytest_test_n_unique,                        1},
    {"_cppallytest_test_na_types",                        (DL_FUNC) &_cppallytest_test_na_types,                        0},
    {"_cppallytest_test_names_empty",                     (DL_FUNC) &_cppallytest_test_names_empty,                     0},
    {"_cppallytest_test_names_growing",                   (DL_FUNC) &_cppallytest_test_names_growing,                   0},
    {"_cppallytest_test_names_inplace_mutation",          (DL_FUNC) &_cppallytest_test_names_inplace_mutation,          0},
    {"_cppallytest_test_names_roundtrip_after_grow",      (DL_FUNC) &_cppallytest_test_names_roundtrip_after_grow,      0},
    {"_cppallytest_test_names_set_attr_invalidation",     (DL_FUNC) &_cppallytest_test_names_set_attr_invalidation,     0},
    {"_cppallytest_test_names_shallow_copy_isolation",    (DL_FUNC) &_cppallytest_test_names_shallow_copy_isolation,    0},
    {"_cppallytest_test_names_stale_invalidation",        (DL_FUNC) &_cppallytest_test_names_stale_invalidation,        0},
    {"_cppallytest_test_names_sweep",                     (DL_FUNC) &_cppallytest_test_names_sweep,                     0},
    {"_cppallytest_test_nas",                             (DL_FUNC) &_cppallytest_test_nas,                             1},
    {"_cppallytest_test_null",                            (DL_FUNC) &_cppallytest_test_null,                            0},
    {"_cppallytest_test_order",                           (DL_FUNC) &_cppallytest_test_order,                           2},
    {"_cppallytest_test_range",                           (DL_FUNC) &_cppallytest_test_range,                           2},
    {"_cppallytest_test_remove",                          (DL_FUNC) &_cppallytest_test_remove,                          2},
    {"_cppallytest_test_replace",                         (DL_FUNC) &_cppallytest_test_replace,                         3},
    {"_cppallytest_test_rval_identity",                   (DL_FUNC) &_cppallytest_test_rval_identity,                   1},
    {"_cppallytest_test_scalar",                          (DL_FUNC) &_cppallytest_test_scalar,                          2},
    {"_cppallytest_test_scalar2",                         (DL_FUNC) &_cppallytest_test_scalar2,                         2},
    {"_cppallytest_test_scalar3",                         (DL_FUNC) &_cppallytest_test_scalar3,                         2},
    {"_cppallytest_test_seqs",                            (DL_FUNC) &_cppallytest_test_seqs,                            3},
    {"_cppallytest_test_sexp",                            (DL_FUNC) &_cppallytest_test_sexp,                            1},
    {"_cppallytest_test_sexp2",                           (DL_FUNC) &_cppallytest_test_sexp2,                           1},
    {"_cppallytest_test_sexp3",                           (DL_FUNC) &_cppallytest_test_sexp3,                           1},
    {"_cppallytest_test_sexp4",                           (DL_FUNC) &_cppallytest_test_sexp4,                           1},
    {"_cppallytest_test_sort",                            (DL_FUNC) &_cppallytest_test_sort,                            2},
    {"_cppallytest_test_specialisation",                  (DL_FUNC) &_cppallytest_test_specialisation,                  1},
    {"_cppallytest_test_str1",                            (DL_FUNC) &_cppallytest_test_str1,                            1},
    {"_cppallytest_test_str2",                            (DL_FUNC) &_cppallytest_test_str2,                            1},
    {"_cppallytest_test_str3",                            (DL_FUNC) &_cppallytest_test_str3,                            1},
    {"_cppallytest_test_str4",                            (DL_FUNC) &_cppallytest_test_str4,                            1},
    {"_cppallytest_test_subset",                          (DL_FUNC) &_cppallytest_test_subset,                          3},
    {"_cppallytest_test_sum",                             (DL_FUNC) &_cppallytest_test_sum,                             2},
    {"_cppallytest_test_sym",                             (DL_FUNC) &_cppallytest_test_sym,                             1},
    {"_cppallytest_test_temp_by_const_lvalue_ref",        (DL_FUNC) &_cppallytest_test_temp_by_const_lvalue_ref,        1},
    {"_cppallytest_test_temp_by_lvalue_ref",              (DL_FUNC) &_cppallytest_test_temp_by_lvalue_ref,              1},
    {"_cppallytest_test_temp_by_rvalue_ref",              (DL_FUNC) &_cppallytest_test_temp_by_rvalue_ref,              1},
    {"_cppallytest_test_temp_by_value",                   (DL_FUNC) &_cppallytest_test_temp_by_value,                   1},
    {"_cppallytest_test_template_null",                   (DL_FUNC) &_cppallytest_test_template_null,                   1},
    {"_cppallytest_test_tz",                              (DL_FUNC) &_cppallytest_test_tz,                              1},
    {"_cppallytest_test_unique",                          (DL_FUNC) &_cppallytest_test_unique,                          1},
    {"_cppallytest_test_valgrind",                        (DL_FUNC) &_cppallytest_test_valgrind,                        0},
    {"_cppallytest_test_var",                             (DL_FUNC) &_cppallytest_test_var,                             2},
    {"_cppallytest_to_int_vec",                           (DL_FUNC) &_cppallytest_to_int_vec,                           1},
    {"_cppallytest_vector1",                              (DL_FUNC) &_cppallytest_vector1,                              1},
    {"_cppallytest_vector2",                              (DL_FUNC) &_cppallytest_vector2,                              1},
    {NULL, NULL, 0}
};
}


void foo(DllInfo* dll);
void bar(DllInfo* dll);

extern "C" attribute_visible void R_init_cppallytest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  foo(dll);
  bar(dll);
  R_forceSymbols(dll, TRUE);
}
