#ifndef CPPALLY_QUANTILE_H
#define CPPALLY_QUANTILE_H

#include <cppally/vector/r_vector.h>
#include <cppally/sort/is_sorted.h>
#include <cppally/sort/sort.h>
#include <cppally/string/string_literal.h>
#include <cppally/named_arg.h>
#include <cstdio>  // For snprintf
#include <algorithm>
#include <limits>

// A C++ implementation of R's `stats::quantile.default`.
// Supports quantile methods of type 6, 7, and 8.
// There are three overloads.
// Overload 1 - Accepts a scalar prob and returns a scalar quantile.
// Overload 2 - Accepts a vector of probs and returns a vector of quantiles.
// Overload 3 - Accepts a vector of probs and a 0-indexed permutation vector that sorts the data (with NAs last), 
// generated by `cppally::order()`. This is useful in the case that you already have the order vector 
// hence can avoid the performance cost of the first 2 overloads, which either partition the data, or 
// calculate the full order permutation (if n probs >= some threshold). In the vast majority of cases, the first two 
// overloads are adequate performance-wise.
// 
// License: MIT
// Author: Nick Christofides

namespace cppally {

namespace internal {

namespace quantile_impl {

struct quantile_position {
    r_size_t j; // 1-indexed
    double gamma; // [0, 1) If gamma > 0 then x[j + 1] exists. If gamma == 0 then the quantile is x[j]
};

// Assumes n_not_na > 0
template <string_literal Method>
inline quantile_position get_quantile_position(r_size_t n_not_na, double p) noexcept {

    // m = a + p(1 - a - b)
    // np_m = np + m
    // j = ⌊np_m⌋
    // gamma = np_m - j

    constexpr std::string_view method = Method.view();
    static_assert(method == "weibull" || method == "linear" || method == "median_unbiased", "Quantile method must be: 'weibull', 'linear' (the default) or 'median_unbiased'");

    // Plotting position constants - see ?stats::quantile
    constexpr double a = method == "weibull" ? 0.0 : (method == "linear" ? 1.0 : 1.0 / 3.0);
    constexpr double b = a;
    constexpr double fuzz = method == "linear" ? 0.0 : 4.0 * std::numeric_limits<double>::epsilon();

    const double np_m = a + p * (n_not_na + 1.0 - a - b); // fractional position of quantile (of sorted data)
    const r_size_t j = std::clamp(static_cast<r_size_t>(np_m * (1.0 + fuzz)), r_size_t(1), n_not_na); // integer position (index)
    double gamma = np_m - j; // fractional part of the quantile position - i.e. how far along the gap between the j-th order statistic and the j+1-th order statistic the quantile is

    if (j == n_not_na || gamma < fuzz){
        gamma = 0.0;
    }
    return {j, gamma};
}

inline double interpolate_quantile(double x_j, double x_j1, double gamma) noexcept {
    
    // If it's a tie, return x[j] to prevent fp error from interpolation
    if (x_j1 == x_j){
        return x_j;
    }
    // Qi(p) = (1 - γ)x[j] + γx[j+1]
    return (1.0 - gamma) * x_j + gamma * x_j1;
}

// Count of NAs assuming x is sorted such that NAs are bundled at the tail end
template <RNumber T>
inline r_size_t sorted_na_count(const r_vec<T>& x){
    const r_size_t n = x.length();
    r_size_t i = n;
    while (i > 0 && is_na(x.get(i - 1))){
        --i;
    }
    return n - i;
}

inline bool is_valid_prob(double p) noexcept {
    return p >= 0.0 && p <= 1.0;
}

inline void check_valid_prob(double p) {
    if (!is_valid_prob(p)) [[unlikely]] {
        abort("probability must be in [0, 1]");
    }
}

inline void check_all_valid_probs(const r_vec<r_dbl>& probs){
    const r_size_t n_probs = probs.length();
    for (r_size_t i = 0; i < n_probs; ++i){
        check_valid_prob(probs.get(i));
    }
}

template <CppNumber T>
inline void move_nas_to_end(T* RESTRICT data, r_size_t n) {
    std::partition(data, data + n, [](T v){ return !is_na(v); });
}
// ----- O(1) quantiles ----
// Assumptions:
// data is sorted or can be sorted by o*
// data has no NAs in first n_not_na elements
// p is in [0, 1]
// 
// Method corresponds to numpy.quantile and can be "weibull", "linear", or "median_unbiased". The R equivalents are type 6, 7, and 8 respectively.
template <string_literal Method, CppNumber T>
inline r_dbl do_quantile(const T* x_data, r_size_t n_not_na, double p, const r_vec<r_int>* o = nullptr){

    if (n_not_na == 0){
        return na<r_dbl>();
    }

    const auto [j, gamma] = get_quantile_position<Method>(n_not_na, p);

    const double x_j = x_data[o ? unwrap(o->get(j - 1)) : j - 1]; // The value of quantile index if data were sorted (j-th order statistic)

    // If gamma is 0 then the j-th order statistic is exactly the quantile
    if (gamma == 0.0){
        return r_dbl(x_j);
    }

    const double x_j1 = x_data[o ? unwrap(o->get(j)) : j];
    return r_dbl(interpolate_quantile(x_j, x_j1, gamma));
}

// Multi-position version of `std::nth_element`, O(n log n_targets).
// Partitions x_data[begin, end) so that each 0-indexed position in targets[0, n_targets) holds its sorted value
// Assumptions:
// targets is sorted, unique and in [begin, end)
template <CppNumber T>
inline void nth_elements(T* x_data, const r_size_t begin, const r_size_t end, const r_size_t* targets, const r_size_t n_targets){

    // If no target positions, no partition needed
    if (n_targets == 0){
        return;
    }

    // Pivot on the last target that is <= the middle of the range (or the first target if none)
    const r_size_t middle = begin + ( (end - begin) / 2 );
    const r_size_t pivot_idx = std::max((std::upper_bound(targets, targets + n_targets, middle) - targets) - 1, r_size_t(0));
    const r_size_t pivot = targets[pivot_idx];

    // Partition data so that x[pivot] such that:
    // x[pivot] == sort(x)[pivot]
    // all elements before it are <= x[pivot]
    // all elements after it are >= x[pivot]
    std::nth_element(x_data + begin, x_data + pivot, x_data + end);

    const r_size_t* left_targets = targets;
    const r_size_t n_left = pivot_idx;
    const r_size_t* right_targets = targets + pivot_idx + 1;
    const r_size_t n_right = n_targets - pivot_idx - 1;

    // targets' values before pivot are in [begin, pivot)
    nth_elements(x_data, begin, pivot, left_targets, n_left);
    // targets' values after pivot are in [pivot + 1, end)
    nth_elements(x_data, pivot + 1, end, right_targets, n_right);
}

// Calculate quantiles of unsorted data for multiple probabilities
// `x_data` is partitioned in-place
// 
// Assumptions: 
// n_not_na > 0
// no NAs in the first n_not_na elements
// probs in [0, 1]
template <string_literal Method, CppNumber T>
inline void do_quantiles(T* x_data, r_size_t n_not_na, const double* probs, const r_size_t n_probs, double* out){

    // targets holds the de-duplicated and sorted quantile position indices necessary for nth_elements()
    std::vector<r_size_t> targets(n_probs);

    for (r_size_t i = 0; i < n_probs; ++i){
        targets[i] = get_quantile_position<Method>(n_not_na, probs[i]).j - 1;
    }
    // Sort and de-duplicate the quantile positions
    // The quantiles will be returned in the user-requested order regardless because the main loop walks along `probs`
    std::sort(targets.begin(), targets.end());
    targets.erase(std::unique(targets.begin(), targets.end()), targets.end());

    // Multi-partition based on unique + sorted quantile position indices
    nth_elements(x_data, r_size_t(0), n_not_na, targets.data(), static_cast<r_size_t>(targets.size()));

    for (r_size_t i = 0; i < n_probs; ++i){
        const auto [j, gamma] = get_quantile_position<Method>(n_not_na, probs[i]); // quantile position i (and associated gamma)
        const double x_j = x_data[j - 1]; // j-th order statistic

        // If gamma is 0 then the j-th order statistic is exactly the quantile
        if (gamma == 0.0){
            out[i] = x_j;
            continue;
        }

        // Since nth_element() guarantees elements to the right of x[j] are >= x[j]
        // x[j+1] is the min of that set such that x[j+1] >= x[j]
        
        // Since the data is partitioned into buckets, we need to restrict the search area of std::min_element
        // The current bucket runs from current target to next target
        const auto next = std::upper_bound(targets.begin(), targets.end(), j - 1);
        const r_size_t end = next == targets.end() ? n_not_na : *next + 1;

        // Find the min element in the target bucket
        const double x_j1 = *std::min_element(x_data + j, x_data + end);
        // Interpolate quantile
        out[i] = interpolate_quantile(x_j, x_j1, gamma);
    }
}

inline r_vec<r_str> quantile_names(const r_vec<r_dbl>& probs){

    r_size_t n_probs = probs.length();
    r_vec<r_str> out(n_probs);

    for (r_size_t i = 0; i < n_probs; ++i){
        r_dbl prob = probs.get(i);
        check_valid_prob(prob);

        char buffer[16];
        // To match R we use 7 significant digits to format the percentages
        std::snprintf(buffer, sizeof(buffer), "%.7g%%", unwrap(prob) * 100.0);
        r_str quantile_name = r_str(static_cast<const char*>(buffer));
        out.set(i, quantile_name);
    }
    return out;
}

} // quantile_impl namespace

}

// Use this overload if you have already generated an order permutation vector using `cppally::order()`
template <string_literal Method = "linear", RNumber T>
inline r_vec<r_dbl> quantile(const r_vec<T>& x, const r_vec<r_dbl>& probs, const r_vec<r_int>& order, bool na_rm = false, bool names = true, bool check_order = true){
    
    r_size_t n = x.length();
    r_size_t n_probs = probs.length();
    internal::quantile_impl::check_all_valid_probs(probs);

    if (order.length() != n) [[unlikely]] {
        abort("`quantile()`: `x.length()` must equal `order.length()`");
    }

    if (check_order){
        bool bad_index = false;
        // Check the order permutation elements are valid
        for (r_size_t i = 0; i < n; ++i){
            int idx = order.get(i);
            bad_index |= static_cast<unsigned>(idx) >= static_cast<unsigned>(n);
        }
        if (bad_index) [[unlikely]] {
            abort("`quantile()`: Invalid permutation index, indices must be in [0, n)");
        }
    }

    // Count NAs but assuming they are at the end of sorted vector
    r_size_t i = n;
    while (i > 0 && is_na(x.get(unwrap(order.get(i - 1))))){
        --i;
    }
    r_size_t n_na = n - i;

    r_size_t n_ok = n - n_na;
    r_vec<r_dbl> out(n_probs, na<r_dbl>());

    if (names){
        out.set_names(internal::quantile_impl::quantile_names(probs));
    }

    if (!na_rm && n_na > 0){
        return out;
    }

    auto* x_data = x.data();

    for (r_size_t i = 0; i < n_probs; ++i){
        r_dbl prob = probs.get(i);
        r_dbl q = internal::quantile_impl::do_quantile<Method>(x_data, n_ok, unwrap(prob), &order);
        out.set(i, q);
    }
    return out;
}

template <string_literal Method = "linear", RNumber T>
inline r_dbl quantile(const r_vec<T>& x, double prob, bool na_rm = false){

    internal::quantile_impl::check_valid_prob(prob);

    const r_size_t n = x.length();

    if (is_sorted(x)){
        // NAs are at the tail end of the vector if they exist
        const r_size_t n_na = internal::quantile_impl::sorted_na_count(x);
        if ((n_na > 0 && !na_rm) || n_na == n){
            return na<r_dbl>();
        }
        return internal::quantile_impl::do_quantile<Method>(x.data(), n - n_na, unwrap(prob));
    }

    if constexpr (RIntegerNumber<T>){
        return quantile<Method>(x, r_vec<r_dbl>( {r_dbl(prob)} ), order(x), na_rm, /*names = */ false, /*check_order = */ false).get(0);
    }

    const r_size_t n_na = x.na_count();

    if (n_na > 0 && !na_rm){
        return na<r_dbl>();
    }

    const auto* x_data = x.data();
    std::vector<unwrap_t<T>> v(x_data, x_data + n);

    if (n_na > 0){
        internal::quantile_impl::move_nas_to_end(v.data(), n);
    }

    const double p = unwrap(prob);
    double q;
    internal::quantile_impl::do_quantiles<Method>(v.data(), n - n_na, &p, 1, &q);
    return r_dbl(q);
}

template <string_literal Method = "linear", RNumber T>
inline r_vec<r_dbl> quantile(const r_vec<T>& x, const r_vec<r_dbl>& probs, bool na_rm = false, bool names = true){

    const r_size_t n = x.length();

    const r_size_t n_probs = probs.length();
    internal::quantile_impl::check_all_valid_probs(probs);
    r_vec<r_dbl> out(n_probs, na<r_dbl>());
    r_vec<r_str> quantile_nms(r_null);

    if (names){
        quantile_nms = internal::quantile_impl::quantile_names(probs);
        out.set_names(quantile_nms);
    }

    if (n_probs == 0){
        return out;
    }

    if (n_probs == 1){
        r_dbl q = quantile<Method>(x, probs.get(0), na_rm);
        out.set(0, q);
        return out;
    }

    // integer-based `order()` is very fast, so lower threshold for that
    constexpr int order_method_threshold = RIntegerType<T> ? 2 : 25;

    if (is_sorted(x)){

        const r_size_t n_na = internal::quantile_impl::sorted_na_count(x);

        if ((n_na > 0 && !na_rm) || n_na == n){
            return out;
        }

        const r_size_t n_ok = n - n_na;

        auto* x_data = x.data();
        for (r_size_t i = 0; i < n_probs; ++i){
            const r_dbl p = probs.get(i);
            out.set(i, internal::quantile_impl::do_quantile<Method>(x_data, n_ok, unwrap(p)));
        }

    } else if (n_probs < order_method_threshold) {

        // Use multi-partitioning via nth_elements()

        const r_size_t n_na = x.na_count();
    
        if ((n_na > 0 && !na_rm) || n_na == n){
            return out;
        }

        const r_size_t n_ok = n - n_na;

        std::vector<unwrap_t<T>> v(x.data(), x.data() + n);

        // Move NAs to the end of the vector
        if (n_na > 0){
            internal::quantile_impl::move_nas_to_end(v.data(), n);
        }

        internal::quantile_impl::do_quantiles<Method>(v.data(), n_ok, probs.data(), n_probs, out.data());
    } else {
        // If number of probs is high, it's faster to compute full order permutation
        // and re-use it for repeated quantile estimation
        r_vec<r_dbl> quantiles = quantile<Method>(x, probs, order(x), na_rm, /*names = */ false, /*check_order = */ false);
        quantiles.set_names(quantile_nms);
        return quantiles;
    }
    return out;
}

}

#endif
