#ifndef CPPALLY_QUANTILE_H
#define CPPALLY_QUANTILE_H

#include <cppally/vector/r_vector.h>
#include <cppally/sort/is_sorted.h>
#include <cppally/sort/sort.h>
#include <cppally/string/string_literal.h>
#include <algorithm>
#include <cmath>
#include <limits>

// A C++ implementation of R's `stats::quantile.default`.
// Supports quantile methods of type 6, 7, and 8.
// There are three overloads.
// Overload 1 - Accepts a scalar prob and returns a scalar quantile.
// Overload 2 - Accepts a vector of probs and returns a vector of quantiles.
// Overload 3 - Accepts a vector of probs and a 0-indexed permutation vector that sorts the data (with NAs last), 
// generated by `cppally::order()`. This is useful in the case that you already have the order vector 
// hence can avoid the performance cost of the first 2 overloads, which either partition the data, or 
// calculate the full order permutation (if n probs >= 25). In the vast majority of cases, the first two 
// overloads are adequate performance-wise.
// 
// License: MIT
// Author: Nick Christofides

namespace cppally {

namespace internal {

// Assumes data has no NAs in first n elements.
// Assumes n > 0
// Assumes p is strictly in [0, 1]
// If o is not nullptr, it overrides sorted. 
//
// ----- O(1) quantiles if data is already sorted or we know order permutation ---- 
// Supply sorted = true if you know the data is already sorted.
// Supply `o`, a permutation ordering that sorts the data.
// Method corresponds to numpy.quantile and can be "weibull", "linear", or "median_unbiased". The R equivalents are type 6, 7, and 8 respectively.
template <string_literal Method, CppNumber T>
inline r_dbl quantile_impl(T* x_data, r_size_t n_not_na, double p, bool sorted, const int* o = nullptr){

    if (n_not_na == 0){
        return na<r_dbl>();
    }

    // m = a + p(1 - a - b)
    // np_m = np + m
    // j = ⌊np_m⌋
    // gamma = np_m - j

    constexpr std::string_view method = Method.view();
    static_assert(method == "weibull" || method == "linear" || method == "median_unbiased", "Method must be one of 'weibull', 'linear' or 'median_unbiased'");

    // Plotting position constants - see ?stats::quantile
    constexpr double a = method == "weibull" ? 0.0 : (method == "linear" ? 1.0 : 1.0 / 3.0);
    constexpr double b = a;
    constexpr double fuzz = method == "linear" ? 0.0 : 4.0 * std::numeric_limits<double>::epsilon();

    const double np_m = a + p * (n_not_na + 1.0 - a - b); // fractional position of quantile (of sorted data)
    const r_size_t j = std::clamp(static_cast<r_size_t>(np_m * (1.0 + fuzz)), r_size_t(1), n_not_na); // integer position (index)
    double gamma = np_m - j; // fractional [0, 1) part of the quantile position - i.e. how far along the gap between the j-th order statistic and the j+1-th order statistic the quantile is

    if constexpr (fuzz > 0.0){
        if (std::abs(gamma) < fuzz){
            gamma = 0.0;
        }
    }

    // nth_element() partitions the data so that x[j] is the j-th order statistic.
    // elements to the left are <= x[j] (but likely unsorted) and elements to the right are >= x[j] (also likely unsorted)

    if (!sorted && !o){
        std::nth_element(x_data, x_data + (j - 1), x_data + n_not_na);
    }
    const double x_j = x_data[o ? o[j - 1] : j - 1]; // The value of quantile index if data were sorted (j-th order statistic)

    // If gamma is 0 then the j-th order statistic is exactly the quantile
    if (gamma <= 0.0 || j == n_not_na){
        return r_dbl(x_j);
    }

    // Since nth_element() guarantees elements to the right of x[j] are >= x[j]
    // x[j+1] is the min of that set such that x[j+1] >= x[j]
    const double x_j1 = o ? x_data[o[j]] : (sorted ? x_data[j] : *std::min_element(x_data + j, x_data + n_not_na));

    // If it's a tie, return x[j]
    if (x_j1 == x_j){
        return r_dbl(x_j);
    }
    // Qi(p) = (1 − γ)x[j] + γx[j+1]
    return r_dbl((1.0 - gamma) * x_j + gamma * x_j1);
}

template <RNumber T>
inline r_size_t sorted_na_count(const r_vec<T>& x){
    const r_size_t n = x.length();
    r_size_t i = n;
    while (i > 0 && is_na(x.get(i - 1))){
        --i;
    }
    return n - i;
}

inline bool is_valid_prob(double p) noexcept {
    return p >= 0.0 && p <= 1.0;
}

inline void check_all_valid_probs(const r_vec<r_dbl>& probs){
    r_size_t n_probs = probs.length();
    for (r_size_t i = 0; i < n_probs; ++i){
        const r_dbl p = probs.get(i);
        if (!internal::is_valid_prob(p)) [[unlikely]] {
            abort("probability must be in [0, 1]");
        }
    }
}

template <CppNumber T>
inline void move_nas_to_end(T* RESTRICT data, r_size_t n) {
    std::partition(data, data + n, [](T v){ return !is_na(v); });
}

}

// Use this overload if you have already generated an order permutation vector using `cppally::order()`
// Time complexity is ~ O(N + n_probs) if check_order = true and O(N Nas + n_probs) 
// otherwise because NAs need to be counted but are assumed to be at the end of the sorted vector
template <string_literal Method = "linear", RNumber T>
inline r_vec<r_dbl> quantile(const r_vec<T>& x, r_vec<r_dbl> probs, const r_vec<r_int>& order, bool na_rm = false, bool check_order = true){
    
    r_size_t n = x.length();

    if (n == 0){
        return r_vec<r_dbl>();
    }

    r_size_t n_probs = probs.length();
    internal::check_all_valid_probs(probs);

    if (order.length() != n) [[unlikely]] {
        abort("`quantile()`: `x.length()` must equal `order.length()`");
    }

    r_size_t n_na = 0;
    int upper = static_cast<int>(n) - 1;

    auto* o_data = order.data();

    if (check_order){
        bool bad_index = false;
        // Check the order permutation elements are valid and count NAs simultaneously 
        for (r_size_t i = 0; i < n; ++i){
            int idx = o_data[i];
            n_na += is_na(x.get(i));
    
            bad_index = bad_index || idx < 0 || idx > upper;
        }
        if (bad_index) [[unlikely]] {
            abort("`quantile()`: Invalid permutation index, indices must be in [0, n)");
        }
    } else {
        // Count NAs but assuming they are at the end of sorted vector
        r_size_t i = n;
        while (i > 0 && is_na(x.get(o_data[i - 1]))){
            --i;
        }
        n_na = n - i;
    }

    // order permutation places NAs at end of vector, so just check the last
    if (!na_rm && n_na > 0){
        return r_vec<r_dbl>(n_probs, na<r_dbl>());
    }

    r_size_t n_ok = n - n_na;
    r_vec<r_dbl> out(n_probs);
    auto* x_data = x.data();

    for (r_size_t i = 0; i < n_probs; ++i){
        r_dbl prob = probs.get(i);
        r_dbl q = internal::quantile_impl<Method>(x_data, n_ok, unwrap(prob), false, o_data);
        out.set(i, q);
    }
    return out;
}

template <string_literal Method = "linear", RNumber T>
inline r_dbl quantile(const r_vec<T>& x, r_dbl prob, bool na_rm = false){

    if (!internal::is_valid_prob(prob)) [[unlikely]] {
        abort("probability must be in [0, 1]");
    }

    const r_size_t n = x.length();

    if (is_sorted(x)){
        // NAs are at the tail end of the vector if they exist
        const r_size_t n_na = internal::sorted_na_count(x);
        if ((n_na > 0 && !na_rm) || n_na == n){
            return na<r_dbl>();
        }
        return internal::quantile_impl<Method>(x.data(), n - n_na, unwrap(prob), true);
    }

    const r_size_t n_na = x.na_count();

    if (n_na > 0 && !na_rm){
        return na<r_dbl>();
    }

    const auto* x_data = x.data();
    std::vector<unwrap_t<T>> v(x_data, x_data + n);

    if (n_na > 0){
        internal::move_nas_to_end(v.data(), n);
    }

    return internal::quantile_impl<Method>(v.data(), n - n_na, unwrap(prob), false);
}

template <string_literal Method = "linear", RNumber T>
inline r_vec<r_dbl> quantile(const r_vec<T>& x, const r_vec<r_dbl>& probs, bool na_rm = false){

    const r_size_t n = x.length();

    if (n == 0){
        return r_vec<r_dbl>();
    }

    const r_size_t n_probs = probs.length();
    internal::check_all_valid_probs(probs);

    if (n_probs == 0){
        return r_vec<r_dbl>();
    }
    if (n_probs == 1){
        return r_vec<r_dbl>(1, quantile<Method>(x, probs.get(0), na_rm));
    }

    if (n_probs >= 25){
        // Method that computes order permutation and re-uses it for fast repeated quantile estimation
        return quantile<Method>(x, probs, order(x), na_rm);
    }

    r_vec<r_dbl> out(n_probs, na<r_dbl>());
    const r_size_t n_na = x.na_count();
    const r_size_t n_ok = n - n_na;

    if ((n_na > 0 && !na_rm) || n_na == n){
        return out;
    }

    bool sorted = is_sorted(x);

    if (sorted){
        auto* x_data = x.data();
        for (r_size_t i = 0; i < n_probs; ++i){
            const r_dbl p = probs.get(i);
            if (!is_na(p)){
                out.set(i, internal::quantile_impl<Method>(x_data, n_ok, unwrap(p), true));
            }
        }
    } else {
        
        // If number of probs is small, it's faster to compute them (via nth_element())

        std::vector<unwrap_t<T>> v(x.data(), x.data() + n);

        // Move NAs to the end of the vector
        if (n_na > 0){
            internal::move_nas_to_end(v.data(), n);
        }

        for (r_size_t i = 0; i < n_probs; ++i){
            const r_dbl p = probs.get(i);
            if (!is_na(p)){
                out.set(i, internal::quantile_impl<Method>(v.data(), n_ok, unwrap(p), false));
            }
        }
    }
    return out;
}

}

#endif
