// Generated by cpp20: do not edit by hand
// clang-format off


#include <cpp20/internal/declarations.hpp>
#include <cpp20/internal/dispatch.hpp>
#include <R_ext/Visibility.h>
#include "test.h"

// test.h
extern "C" SEXP _cpp20_test_deduced_type(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_deduced_type(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_deduced_type(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_multiple_deduction(SEXP x, SEXP y) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_multiple_deduction(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_multiple_deduction(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_deduced_vec_type(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_deduced_vec_type(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_deduced_vec_type(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_deduced_scalar_type(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_deduced_scalar_type(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_deduced_scalar_type(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_identity(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_identity(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_identity(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
SEXP test_identity2(SEXP x);
extern "C" SEXP _cpp20_test_identity2(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<SEXP>(x);
  return cpp20::internal::cpp_to_sexp(test_identity2(cpp20::as<std::remove_cvref_t<SEXP>>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_template_null(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_template_null(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_template_null(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_scalar(SEXP x, SEXP y) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<int>(x);
return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_scalar(cpp20::as<std::remove_cvref_t<int>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_scalar(cpp20::as<std::remove_cvref_t<int>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_scalar2(SEXP x, SEXP y) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_int>(x);
return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_scalar2(cpp20::as<std::remove_cvref_t<r_int>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_scalar2(cpp20::as<std::remove_cvref_t<r_int>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_scalar3(SEXP x, SEXP y) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_int>(x);
return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_scalar3(cpp20::as<std::remove_cvref_t<r_int>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_scalar3(cpp20::as<std::remove_cvref_t<r_int>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_rval_identity(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_rval_identity(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_rval_identity(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar1(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar1(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar1(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar2(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar2(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar2(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_vector1(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(vector1(cpp20::as<std::remove_cvref_t<r_vec<T>>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(vector1(cpp20::as<std::remove_cvref_t<r_vec<T>>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_vector2(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(vector2(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(vector2(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar3(SEXP x, SEXP y) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar3(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar3(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar4(SEXP x, SEXP y) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar4(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<U>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar4(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<U>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_sexp(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_sexp(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_sexp(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_sexp4(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_sexp4(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_sexp4(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar_vec1(SEXP a, SEXP b) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP a_internal, SEXP b_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar_vec1(cpp20::as<std::remove_cvref_t<r_vec<T>>>(a_internal), cpp20::as<std::remove_cvref_t<T>>(b_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar_vec1(cpp20::as<std::remove_cvref_t<r_vec<T>>>(a_internal), cpp20::as<std::remove_cvref_t<T>>(b_internal)));
    },
    a, b
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar_vec2(SEXP a, SEXP b) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP a_internal, SEXP b_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar_vec2(cpp20::as<std::remove_cvref_t<r_vec<T>>>(a_internal), cpp20::as<std::remove_cvref_t<U>>(b_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar_vec2(cpp20::as<std::remove_cvref_t<r_vec<T>>>(a_internal), cpp20::as<std::remove_cvref_t<U>>(b_internal)));
    },
    a, b
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar_vec3(SEXP z, SEXP x, SEXP y, SEXP a) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<2, 4, std::array<int, 4>{0, 0, 1, 1}>(
    []<typename T, typename U>(SEXP z_internal, SEXP x_internal, SEXP y_internal, SEXP a_internal) -> decltype(cpp20::internal::cpp_to_sexp(scalar_vec3(cpp20::as<std::remove_cvref_t<r_vec<T>>>(z_internal), cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<U>>(y_internal), cpp20::as<std::remove_cvref_t<r_vec<U>>>(a_internal)))) {
        return cpp20::internal::cpp_to_sexp(scalar_vec3(cpp20::as<std::remove_cvref_t<r_vec<T>>>(z_internal), cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<U>>(y_internal), cpp20::as<std::remove_cvref_t<r_vec<U>>>(a_internal)));
    },
    z, x, y, a
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_mix2(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f, SEXP g) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<double>(b);
	cpp20::internal::check_r_cpp_mapping<int>(d);
return cpp20::internal::dispatch_template_impl<2, 7, std::array<int, 7>{0, -1, 0, -1, 0, 0, 1}>(
    []<typename T, typename V>(SEXP a_internal, SEXP b_internal, SEXP c_internal, SEXP d_internal, SEXP e_internal, SEXP f_internal, SEXP g_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_mix2(cpp20::as<std::remove_cvref_t<r_vec<T>>>(a_internal), cpp20::as<std::remove_cvref_t<double>>(b_internal), cpp20::as<std::remove_cvref_t<T>>(c_internal), cpp20::as<std::remove_cvref_t<int>>(d_internal), cpp20::as<std::remove_cvref_t<T>>(e_internal), cpp20::as<std::remove_cvref_t<T>>(f_internal), cpp20::as<std::remove_cvref_t<V>>(g_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_mix2(cpp20::as<std::remove_cvref_t<r_vec<T>>>(a_internal), cpp20::as<std::remove_cvref_t<double>>(b_internal), cpp20::as<std::remove_cvref_t<T>>(c_internal), cpp20::as<std::remove_cvref_t<int>>(d_internal), cpp20::as<std::remove_cvref_t<T>>(e_internal), cpp20::as<std::remove_cvref_t<T>>(f_internal), cpp20::as<std::remove_cvref_t<V>>(g_internal)));
    },
    a, b, c, d, e, f, g
  );
  END_CPP20
}
// test.h
inline r_vec<r_str> test_str1(r_str x);
extern "C" SEXP _cpp20_test_str1(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_str>(x);
  return cpp20::internal::cpp_to_sexp(test_str1(cpp20::as<std::remove_cvref_t<r_str>>(x)));
  END_CPP20
}
// test.h
inline r_vec<r_str_view> test_str2(r_str_view x);
extern "C" SEXP _cpp20_test_str2(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_str_view>(x);
  return cpp20::internal::cpp_to_sexp(test_str2(cpp20::as<std::remove_cvref_t<r_str_view>>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_str3(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_str3(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_str3(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_str4(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_str4(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_str4(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_as_sym(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_as_sym(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_as_sym(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_specialisation(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_specialisation(cpp20::as<std::remove_cvref_t<r_vec<T>>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_specialisation(cpp20::as<std::remove_cvref_t<r_vec<T>>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_coerce(SEXP x, SEXP ptype) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP ptype_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_coerce(cpp20::as<std::remove_cvref_t<r_vec<T>>>(x_internal), cpp20::as<std::remove_cvref_t<U>>(ptype_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_coerce(cpp20::as<std::remove_cvref_t<r_vec<T>>>(x_internal), cpp20::as<std::remove_cvref_t<U>>(ptype_internal)));
    },
    x, ptype
  );
  END_CPP20
}
// test.h
r_vec<r_date> test_as_date(SEXP x);
extern "C" SEXP _cpp20_test_as_date(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<SEXP>(x);
  return cpp20::internal::cpp_to_sexp(test_as_date(cpp20::as<std::remove_cvref_t<SEXP>>(x)));
  END_CPP20
}
// test.h
r_vec<r_date> test_construct_date(SEXP x);
extern "C" SEXP _cpp20_test_construct_date(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<SEXP>(x);
  return cpp20::internal::cpp_to_sexp(test_construct_date(cpp20::as<std::remove_cvref_t<SEXP>>(x)));
  END_CPP20
}
// test.h
r_vec<r_date> test_as_date2(r_vec<r_date> x);
extern "C" SEXP _cpp20_test_as_date2(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_vec<r_date>>(x);
  return cpp20::internal::cpp_to_sexp(test_as_date2(cpp20::as<std::remove_cvref_t<r_vec<r_date>>>(x)));
  END_CPP20
}
// test.h
void cpp_set_threads(int n);
extern "C" SEXP _cpp20_cpp_set_threads(SEXP n) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<int>(n);
  cpp_set_threads(cpp20::as<std::remove_cvref_t<int>>(n));
  return R_NilValue;
  END_CPP20
}
// test.h
r_int cpp_get_threads();
extern "C" SEXP _cpp20_cpp_get_threads() {
  BEGIN_CPP20
    return cpp20::internal::cpp_to_sexp(cpp_get_threads());
  END_CPP20
}
// test.h
r_sexp test_null();
extern "C" SEXP _cpp20_test_null() {
  BEGIN_CPP20
    return cpp20::internal::cpp_to_sexp(test_null());
  END_CPP20
}
// test.h
r_sym test_sym(r_sym x);
extern "C" SEXP _cpp20_test_sym(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_sym>(x);
  return cpp20::internal::cpp_to_sexp(test_sym(cpp20::as<std::remove_cvref_t<r_sym>>(x)));
  END_CPP20
}
// test.h
r_sexp test_sexp2(r_sexp x);
extern "C" SEXP _cpp20_test_sexp2(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_sexp>(x);
  return cpp20::internal::cpp_to_sexp(test_sexp2(cpp20::as<std::remove_cvref_t<r_sexp>>(x)));
  END_CPP20
}
// test.h
r_vec<r_sexp> test_sexp3(r_vec<r_sexp> x);
extern "C" SEXP _cpp20_test_sexp3(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_vec<r_sexp>>(x);
  return cpp20::internal::cpp_to_sexp(test_sexp3(cpp20::as<std::remove_cvref_t<r_vec<r_sexp>>>(x)));
  END_CPP20
}
// test.h
SEXP test_list_to_scalars(r_vec<r_sexp> x);
extern "C" SEXP _cpp20_test_list_to_scalars(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_vec<r_sexp>>(x);
  return cpp20::internal::cpp_to_sexp(test_list_to_scalars(cpp20::as<std::remove_cvref_t<r_vec<r_sexp>>>(x)));
  END_CPP20
}
// test.h
r_vec<r_int> test_coerce1(const r_vec<r_sexp>& x);
extern "C" SEXP _cpp20_test_coerce1(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<const r_vec<r_sexp>&>(x);
  return cpp20::internal::cpp_to_sexp(test_coerce1(cpp20::as<std::remove_cvref_t<const r_vec<r_sexp>&>>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_combine2(SEXP x, SEXP y) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_combine2(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_combine2(cpp20::as<std::remove_cvref_t<T>>(x_internal), cpp20::as<std::remove_cvref_t<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
r_vec<r_date> test_dates1(r_vec<r_date> x);
extern "C" SEXP _cpp20_test_dates1(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_vec<r_date>>(x);
  return cpp20::internal::cpp_to_sexp(test_dates1(cpp20::as<std::remove_cvref_t<r_vec<r_date>>>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_dates2(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_dates2(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_dates2(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_classed_vec(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_classed_vec(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_classed_vec(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_unique(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_unique(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_unique(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_seqs(SEXP size, SEXP from, SEXP by) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_vec<r_int>>(size);
return cpp20::internal::dispatch_template_impl<2, 3, std::array<int, 3>{-1, 0, 1}>(
    []<typename U, typename V>(SEXP size_internal, SEXP from_internal, SEXP by_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_seqs(cpp20::as<std::remove_cvref_t<r_vec<r_int>>>(size_internal), cpp20::as<std::remove_cvref_t<r_vec<U>>>(from_internal), cpp20::as<std::remove_cvref_t<r_vec<V>>>(by_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_seqs(cpp20::as<std::remove_cvref_t<r_vec<r_int>>>(size_internal), cpp20::as<std::remove_cvref_t<r_vec<U>>>(from_internal), cpp20::as<std::remove_cvref_t<r_vec<V>>>(by_internal)));
    },
    size, from, by
  );
  END_CPP20
}
// test.h
r_str test_tz(r_vec<r_psxct> x);
extern "C" SEXP _cpp20_test_tz(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_vec<r_psxct>>(x);
  return cpp20::internal::cpp_to_sexp(test_tz(cpp20::as<std::remove_cvref_t<r_vec<r_psxct>>>(x)));
  END_CPP20
}
// test.h
r_vec<r_sexp> test_time_coerce();
extern "C" SEXP _cpp20_test_time_coerce() {
  BEGIN_CPP20
    return cpp20::internal::cpp_to_sexp(test_time_coerce());
  END_CPP20
}
// test.h
r_factors test_factor1(r_factors x);
extern "C" SEXP _cpp20_test_factor1(SEXP x) {
  BEGIN_CPP20
  cpp20::internal::check_r_cpp_mapping<r_factors>(x);
  return cpp20::internal::cpp_to_sexp(test_factor1(cpp20::as<std::remove_cvref_t<r_factors>>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_factor2(SEXP x) {
  BEGIN_CPP20
  return cpp20::internal::dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp20::internal::cpp_to_sexp(test_factor2(cpp20::as<std::remove_cvref_t<T>>(x_internal)))) {
        return cpp20::internal::cpp_to_sexp(test_factor2(cpp20::as<std::remove_cvref_t<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_cpp_get_threads",          (DL_FUNC) &_cpp20_cpp_get_threads,          0},
    {"_cpp20_cpp_set_threads",          (DL_FUNC) &_cpp20_cpp_set_threads,          1},
    {"_cpp20_scalar1",                  (DL_FUNC) &_cpp20_scalar1,                  1},
    {"_cpp20_scalar2",                  (DL_FUNC) &_cpp20_scalar2,                  1},
    {"_cpp20_scalar3",                  (DL_FUNC) &_cpp20_scalar3,                  2},
    {"_cpp20_scalar4",                  (DL_FUNC) &_cpp20_scalar4,                  2},
    {"_cpp20_scalar_vec1",              (DL_FUNC) &_cpp20_scalar_vec1,              2},
    {"_cpp20_scalar_vec2",              (DL_FUNC) &_cpp20_scalar_vec2,              2},
    {"_cpp20_scalar_vec3",              (DL_FUNC) &_cpp20_scalar_vec3,              4},
    {"_cpp20_test_as_date",             (DL_FUNC) &_cpp20_test_as_date,             1},
    {"_cpp20_test_as_date2",            (DL_FUNC) &_cpp20_test_as_date2,            1},
    {"_cpp20_test_as_sym",              (DL_FUNC) &_cpp20_test_as_sym,              1},
    {"_cpp20_test_classed_vec",         (DL_FUNC) &_cpp20_test_classed_vec,         1},
    {"_cpp20_test_coerce",              (DL_FUNC) &_cpp20_test_coerce,              2},
    {"_cpp20_test_coerce1",             (DL_FUNC) &_cpp20_test_coerce1,             1},
    {"_cpp20_test_combine2",            (DL_FUNC) &_cpp20_test_combine2,            2},
    {"_cpp20_test_construct_date",      (DL_FUNC) &_cpp20_test_construct_date,      1},
    {"_cpp20_test_dates1",              (DL_FUNC) &_cpp20_test_dates1,              1},
    {"_cpp20_test_dates2",              (DL_FUNC) &_cpp20_test_dates2,              1},
    {"_cpp20_test_deduced_scalar_type", (DL_FUNC) &_cpp20_test_deduced_scalar_type, 1},
    {"_cpp20_test_deduced_type",        (DL_FUNC) &_cpp20_test_deduced_type,        1},
    {"_cpp20_test_deduced_vec_type",    (DL_FUNC) &_cpp20_test_deduced_vec_type,    1},
    {"_cpp20_test_factor1",             (DL_FUNC) &_cpp20_test_factor1,             1},
    {"_cpp20_test_factor2",             (DL_FUNC) &_cpp20_test_factor2,             1},
    {"_cpp20_test_identity",            (DL_FUNC) &_cpp20_test_identity,            1},
    {"_cpp20_test_identity2",           (DL_FUNC) &_cpp20_test_identity2,           1},
    {"_cpp20_test_list_to_scalars",     (DL_FUNC) &_cpp20_test_list_to_scalars,     1},
    {"_cpp20_test_mix2",                (DL_FUNC) &_cpp20_test_mix2,                7},
    {"_cpp20_test_multiple_deduction",  (DL_FUNC) &_cpp20_test_multiple_deduction,  2},
    {"_cpp20_test_null",                (DL_FUNC) &_cpp20_test_null,                0},
    {"_cpp20_test_rval_identity",       (DL_FUNC) &_cpp20_test_rval_identity,       1},
    {"_cpp20_test_scalar",              (DL_FUNC) &_cpp20_test_scalar,              2},
    {"_cpp20_test_scalar2",             (DL_FUNC) &_cpp20_test_scalar2,             2},
    {"_cpp20_test_scalar3",             (DL_FUNC) &_cpp20_test_scalar3,             2},
    {"_cpp20_test_seqs",                (DL_FUNC) &_cpp20_test_seqs,                3},
    {"_cpp20_test_sexp",                (DL_FUNC) &_cpp20_test_sexp,                1},
    {"_cpp20_test_sexp2",               (DL_FUNC) &_cpp20_test_sexp2,               1},
    {"_cpp20_test_sexp3",               (DL_FUNC) &_cpp20_test_sexp3,               1},
    {"_cpp20_test_sexp4",               (DL_FUNC) &_cpp20_test_sexp4,               1},
    {"_cpp20_test_specialisation",      (DL_FUNC) &_cpp20_test_specialisation,      1},
    {"_cpp20_test_str1",                (DL_FUNC) &_cpp20_test_str1,                1},
    {"_cpp20_test_str2",                (DL_FUNC) &_cpp20_test_str2,                1},
    {"_cpp20_test_str3",                (DL_FUNC) &_cpp20_test_str3,                1},
    {"_cpp20_test_str4",                (DL_FUNC) &_cpp20_test_str4,                1},
    {"_cpp20_test_sym",                 (DL_FUNC) &_cpp20_test_sym,                 1},
    {"_cpp20_test_template_null",       (DL_FUNC) &_cpp20_test_template_null,       1},
    {"_cpp20_test_time_coerce",         (DL_FUNC) &_cpp20_test_time_coerce,         0},
    {"_cpp20_test_tz",                  (DL_FUNC) &_cpp20_test_tz,                  1},
    {"_cpp20_test_unique",              (DL_FUNC) &_cpp20_test_unique,              1},
    {"_cpp20_vector1",                  (DL_FUNC) &_cpp20_vector1,                  1},
    {"_cpp20_vector2",                  (DL_FUNC) &_cpp20_vector2,                  1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp20(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
