// Generated by cpp20: do not edit by hand
// clang-format off


#include <cpp20/r_dispatch.h>
#include <R_ext/Visibility.h>
#include "test.h"
#include "test_nas.h"
#include "test_sort.h"
#include "test_stats.h"
#include "test_subset.h"

using namespace cpp20;
using internal::cpp_to_sexp;
using internal::check_r_cpp_mapping;
using internal::dispatch_template_impl;

// test.cpp
void cpp_set_threads(int n);
extern "C" SEXP _cpp20_cpp_set_threads(SEXP n) {
  BEGIN_CPP20
  check_r_cpp_mapping<int>(n);
  cpp_set_threads(cpp20::as<int>(n));
  return R_NilValue;
  END_CPP20
}
// test.cpp
r_int cpp_get_threads();
extern "C" SEXP _cpp20_cpp_get_threads() {
  BEGIN_CPP20
    return cpp_to_sexp(cpp_get_threads());
  END_CPP20
}
// test.cpp
r_str cpp20_typeof(SEXP x);
extern "C" SEXP _cpp20_cpp20_typeof(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
  return cpp_to_sexp(cpp20_typeof(cpp20::as<SEXP>(x)));
  END_CPP20
}
// test.cpp
SEXP test_identity2(SEXP x);
extern "C" SEXP _cpp20_test_identity2(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
  return cpp_to_sexp(test_identity2(cpp20::as<SEXP>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_str> test_str1(r_str x);
extern "C" SEXP _cpp20_test_str1(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_str>(x);
  return cpp_to_sexp(test_str1(cpp20::as<r_str>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_str_view> test_str2(r_str_view x);
extern "C" SEXP _cpp20_test_str2(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_str_view>(x);
  return cpp_to_sexp(test_str2(cpp20::as<r_str_view>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_date> test_as_date(SEXP x);
extern "C" SEXP _cpp20_test_as_date(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
  return cpp_to_sexp(test_as_date(cpp20::as<SEXP>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_date> test_construct_date(SEXP x);
extern "C" SEXP _cpp20_test_construct_date(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
  return cpp_to_sexp(test_construct_date(cpp20::as<SEXP>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_date> test_as_date2(r_vec<r_date> x);
extern "C" SEXP _cpp20_test_as_date2(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_date>>(x);
  return cpp_to_sexp(test_as_date2(cpp20::as<r_vec<r_date>>(x)));
  END_CPP20
}
// test.cpp
r_sexp test_null();
extern "C" SEXP _cpp20_test_null() {
  BEGIN_CPP20
    return cpp_to_sexp(test_null());
  END_CPP20
}
// test.cpp
r_sym test_sym(r_sym x);
extern "C" SEXP _cpp20_test_sym(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_sym>(x);
  return cpp_to_sexp(test_sym(cpp20::as<r_sym>(x)));
  END_CPP20
}
// test.cpp
r_sexp test_sexp2(r_sexp x);
extern "C" SEXP _cpp20_test_sexp2(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_sexp>(x);
  return cpp_to_sexp(test_sexp2(cpp20::as<r_sexp>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_sexp> test_sexp3(r_vec<r_sexp> x);
extern "C" SEXP _cpp20_test_sexp3(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_sexp>>(x);
  return cpp_to_sexp(test_sexp3(cpp20::as<r_vec<r_sexp>>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_int> test_coerce1(const r_vec<r_sexp>& x);
extern "C" SEXP _cpp20_test_coerce1(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<const r_vec<r_sexp>&>(x);
  return cpp_to_sexp(test_coerce1(cpp20::as<const r_vec<r_sexp>&>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_date> test_dates1(r_vec<r_date> x);
extern "C" SEXP _cpp20_test_dates1(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_date>>(x);
  return cpp_to_sexp(test_dates1(cpp20::as<r_vec<r_date>>(x)));
  END_CPP20
}
// test.cpp
r_str test_tz(r_vec<r_psxct> x);
extern "C" SEXP _cpp20_test_tz(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_psxct>>(x);
  return cpp_to_sexp(test_tz(cpp20::as<r_vec<r_psxct>>(x)));
  END_CPP20
}
// test.cpp
r_vec<r_int> test_lengths(const r_vec<r_sexp>& x);
extern "C" SEXP _cpp20_test_lengths(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<const r_vec<r_sexp>&>(x);
  return cpp_to_sexp(test_lengths(cpp20::as<const r_vec<r_sexp>&>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_deduced_type(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_deduced_type(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_deduced_type(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_multiple_deduction(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_multiple_deduction(cpp20::as<T>(x_internal), cpp20::as<T>(y_internal)))) {
        return cpp_to_sexp(test_multiple_deduction(cpp20::as<T>(x_internal), cpp20::as<T>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_deduced_vec_type(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_deduced_vec_type(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_deduced_vec_type(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_deduced_scalar_type(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_deduced_scalar_type(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_deduced_scalar_type(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_deduced_scalar_type2(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_deduced_scalar_type2(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_deduced_scalar_type2(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_identity(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_identity(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_identity(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_template_null(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_template_null(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_template_null(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_scalar(SEXP x, SEXP y) {
  BEGIN_CPP20
  check_r_cpp_mapping<int>(x);
return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_scalar(cpp20::as<int>(x_internal), cpp20::as<T>(y_internal)))) {
        return cpp_to_sexp(test_scalar(cpp20::as<int>(x_internal), cpp20::as<T>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_scalar2(SEXP x, SEXP y) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_int>(x);
return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_scalar2(cpp20::as<r_int>(x_internal), cpp20::as<T>(y_internal)))) {
        return cpp_to_sexp(test_scalar2(cpp20::as<r_int>(x_internal), cpp20::as<T>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_scalar3(SEXP x, SEXP y) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_int>(x);
return dispatch_template_impl<1, 2, std::array<int, 2>{-1, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_scalar3(cpp20::as<r_int>(x_internal), cpp20::as<T>(y_internal)))) {
        return cpp_to_sexp(test_scalar3(cpp20::as<r_int>(x_internal), cpp20::as<T>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_rval_identity(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_rval_identity(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_rval_identity(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar1(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(scalar1(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(scalar1(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar2(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(scalar2(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(scalar2(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_vector1(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(vector1(cpp20::as<r_vec<T>>(x_internal)))) {
        return cpp_to_sexp(vector1(cpp20::as<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_vector2(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(vector2(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(vector2(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar3(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(scalar3(cpp20::as<T>(x_internal), cpp20::as<T>(y_internal)))) {
        return cpp_to_sexp(scalar3(cpp20::as<T>(x_internal), cpp20::as<T>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar4(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(scalar4(cpp20::as<T>(x_internal), cpp20::as<U>(y_internal)))) {
        return cpp_to_sexp(scalar4(cpp20::as<T>(x_internal), cpp20::as<U>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_sexp(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_sexp(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_sexp(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_sexp4(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_sexp4(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_sexp4(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar_vec1(SEXP a, SEXP b) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_sexp(scalar_vec1(cpp20::as<r_vec<T>>(a_internal), cpp20::as<T>(b_internal)))) {
        return cpp_to_sexp(scalar_vec1(cpp20::as<r_vec<T>>(a_internal), cpp20::as<T>(b_internal)));
    },
    a, b
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar_vec2(SEXP a, SEXP b) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP a_internal, SEXP b_internal) -> decltype(cpp_to_sexp(scalar_vec2(cpp20::as<r_vec<T>>(a_internal), cpp20::as<U>(b_internal)))) {
        return cpp_to_sexp(scalar_vec2(cpp20::as<r_vec<T>>(a_internal), cpp20::as<U>(b_internal)));
    },
    a, b
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_scalar_vec3(SEXP z, SEXP x, SEXP y, SEXP a) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 4, std::array<int, 4>{0, 0, 1, 1}>(
    []<typename T, typename U>(SEXP z_internal, SEXP x_internal, SEXP y_internal, SEXP a_internal) -> decltype(cpp_to_sexp(scalar_vec3(cpp20::as<r_vec<T>>(z_internal), cpp20::as<T>(x_internal), cpp20::as<U>(y_internal), cpp20::as<r_vec<U>>(a_internal)))) {
        return cpp_to_sexp(scalar_vec3(cpp20::as<r_vec<T>>(z_internal), cpp20::as<T>(x_internal), cpp20::as<U>(y_internal), cpp20::as<r_vec<U>>(a_internal)));
    },
    z, x, y, a
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_mix2(SEXP a, SEXP b, SEXP c, SEXP d, SEXP e, SEXP f, SEXP g) {
  BEGIN_CPP20
  check_r_cpp_mapping<double>(b);
	check_r_cpp_mapping<int>(d);
return dispatch_template_impl<2, 7, std::array<int, 7>{0, -1, 0, -1, 0, 0, 1}>(
    []<typename T, typename V>(SEXP a_internal, SEXP b_internal, SEXP c_internal, SEXP d_internal, SEXP e_internal, SEXP f_internal, SEXP g_internal) -> decltype(cpp_to_sexp(test_mix2(cpp20::as<r_vec<T>>(a_internal), cpp20::as<double>(b_internal), cpp20::as<T>(c_internal), cpp20::as<int>(d_internal), cpp20::as<T>(e_internal), cpp20::as<T>(f_internal), cpp20::as<V>(g_internal)))) {
        return cpp_to_sexp(test_mix2(cpp20::as<r_vec<T>>(a_internal), cpp20::as<double>(b_internal), cpp20::as<T>(c_internal), cpp20::as<int>(d_internal), cpp20::as<T>(e_internal), cpp20::as<T>(f_internal), cpp20::as<V>(g_internal)));
    },
    a, b, c, d, e, f, g
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_str3(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_str3(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_str3(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_str4(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_str4(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_str4(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_as_sym(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_as_sym(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_as_sym(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_specialisation(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_specialisation(cpp20::as<r_vec<T>>(x_internal)))) {
        return cpp_to_sexp(test_specialisation(cpp20::as<r_vec<T>>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_coerce(SEXP x, SEXP ptype) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP ptype_internal) -> decltype(cpp_to_sexp(test_coerce(cpp20::as<r_vec<T>>(x_internal), cpp20::as<U>(ptype_internal)))) {
        return cpp_to_sexp(test_coerce(cpp20::as<r_vec<T>>(x_internal), cpp20::as<U>(ptype_internal)));
    },
    x, ptype
  );
  END_CPP20
}
// test.h
SEXP test_list_to_scalars(r_vec<r_sexp> x);
extern "C" SEXP _cpp20_test_list_to_scalars(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_sexp>>(x);
  return cpp_to_sexp(test_list_to_scalars(cpp20::as<r_vec<r_sexp>>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_combine2(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_combine2(cpp20::as<T>(x_internal), cpp20::as<T>(y_internal)))) {
        return cpp_to_sexp(test_combine2(cpp20::as<T>(x_internal), cpp20::as<T>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_dates2(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_dates2(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_dates2(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_unique(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_unique(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_unique(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_seqs(SEXP size, SEXP from, SEXP by) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_int>>(size);
return dispatch_template_impl<2, 3, std::array<int, 3>{-1, 0, 1}>(
    []<typename U, typename V>(SEXP size_internal, SEXP from_internal, SEXP by_internal) -> decltype(cpp_to_sexp(test_seqs(cpp20::as<r_vec<r_int>>(size_internal), cpp20::as<r_vec<U>>(from_internal), cpp20::as<r_vec<V>>(by_internal)))) {
        return cpp_to_sexp(test_seqs(cpp20::as<r_vec<r_int>>(size_internal), cpp20::as<r_vec<U>>(from_internal), cpp20::as<r_vec<V>>(by_internal)));
    },
    size, from, by
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_group_id(SEXP x, SEXP order) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(order);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_sexp(test_group_id(cpp20::as<T>(x_internal), cpp20::as<bool>(order_internal)))) {
        return cpp_to_sexp(test_group_id(cpp20::as<T>(x_internal), cpp20::as<bool>(order_internal)));
    },
    x, order
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_group_counts(SEXP x, SEXP order) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(order);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP order_internal) -> decltype(cpp_to_sexp(test_group_counts(cpp20::as<T>(x_internal), cpp20::as<bool>(order_internal)))) {
        return cpp_to_sexp(test_group_counts(cpp20::as<T>(x_internal), cpp20::as<bool>(order_internal)));
    },
    x, order
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_match(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 2, std::array<int, 2>{0, 0}>(
    []<typename T>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_match(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<T>>(y_internal)))) {
        return cpp_to_sexp(test_match(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<T>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test.h
r_vec<r_sexp> test_factor1(r_factors x);
extern "C" SEXP _cpp20_test_factor1(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_factors>(x);
  return cpp_to_sexp(test_factor1(cpp20::as<r_factors>(x)));
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_factor2(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_factor2(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_factor2(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
extern "C" SEXP _cpp20_test_n_unique(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_n_unique(cpp20::as<T>(x_internal)))) {
        return cpp_to_sexp(test_n_unique(cpp20::as<T>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test.h
SEXP test_copy(SEXP x);
extern "C" SEXP _cpp20_test_copy(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
  return cpp_to_sexp(test_copy(cpp20::as<SEXP>(x)));
  END_CPP20
}
// test.h
bool test_identical(SEXP x, SEXP y);
extern "C" SEXP _cpp20_test_identical(SEXP x, SEXP y) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
	check_r_cpp_mapping<SEXP>(y);
  return cpp_to_sexp(test_identical(cpp20::as<SEXP>(x), cpp20::as<SEXP>(y)));
  END_CPP20
}
// test_attrs.cpp
r_vec<r_sexp> test_attrs(SEXP x);
extern "C" SEXP _cpp20_test_attrs(SEXP x) {
  BEGIN_CPP20
  check_r_cpp_mapping<SEXP>(x);
  return cpp_to_sexp(test_attrs(cpp20::as<SEXP>(x)));
  END_CPP20
}
// test_attrs.cpp
r_vec<r_sexp> test_df(r_vec<r_sexp> cols);
extern "C" SEXP _cpp20_test_df(SEXP cols) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_sexp>>(cols);
  return cpp_to_sexp(test_df(cpp20::as<r_vec<r_sexp>>(cols)));
  END_CPP20
}
// test_nas.h
extern "C" SEXP _cpp20_test_nas(SEXP x) {
  BEGIN_CPP20
  return dispatch_template_impl<1, 1, std::array<int, 1>{0}>(
    []<typename T>(SEXP x_internal) -> decltype(cpp_to_sexp(test_nas(cpp20::as<T const&>(x_internal)))) {
        return cpp_to_sexp(test_nas(cpp20::as<T const&>(x_internal)));
    },
    x
  );
  END_CPP20
}
// test_nas.h
inline r_vec<r_sexp> test_na_types();
extern "C" SEXP _cpp20_test_na_types() {
  BEGIN_CPP20
    return cpp_to_sexp(test_na_types());
  END_CPP20
}
// test_sort.h
extern "C" SEXP _cpp20_test_order(SEXP x, SEXP preserve_ties) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(preserve_ties);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_sexp(test_order(cpp20::as<T>(x_internal), cpp20::as<bool>(preserve_ties_internal)))) {
        return cpp_to_sexp(test_order(cpp20::as<T>(x_internal), cpp20::as<bool>(preserve_ties_internal)));
    },
    x, preserve_ties
  );
  END_CPP20
}
// test_sort.h
extern "C" SEXP _cpp20_test_sort(SEXP x, SEXP preserve_ties) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(preserve_ties);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP preserve_ties_internal) -> decltype(cpp_to_sexp(test_sort(cpp20::as<T>(x_internal), cpp20::as<bool>(preserve_ties_internal)))) {
        return cpp_to_sexp(test_sort(cpp20::as<T>(x_internal), cpp20::as<bool>(preserve_ties_internal)));
    },
    x, preserve_ties
  );
  END_CPP20
}
// test_stats.h
extern "C" SEXP _cpp20_test_range(SEXP x, SEXP na_rm) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(na_rm);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(test_range(cpp20::as<T>(x_internal), cpp20::as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(test_range(cpp20::as<T>(x_internal), cpp20::as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPP20
}
// test_stats.h
extern "C" SEXP _cpp20_test_sum(SEXP x, SEXP na_rm) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(na_rm);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(test_sum(cpp20::as<r_vec<T>>(x_internal), cpp20::as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(test_sum(cpp20::as<r_vec<T>>(x_internal), cpp20::as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPP20
}
// test_stats.h
extern "C" SEXP _cpp20_test_mean(SEXP x, SEXP na_rm) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(na_rm);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(test_mean(cpp20::as<r_vec<T>>(x_internal), cpp20::as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(test_mean(cpp20::as<r_vec<T>>(x_internal), cpp20::as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPP20
}
// test_stats.h
extern "C" SEXP _cpp20_test_var(SEXP x, SEXP na_rm) {
  BEGIN_CPP20
  check_r_cpp_mapping<bool>(na_rm);
return dispatch_template_impl<1, 2, std::array<int, 2>{0, -1}>(
    []<typename T>(SEXP x_internal, SEXP na_rm_internal) -> decltype(cpp_to_sexp(test_var(cpp20::as<r_vec<T>>(x_internal), cpp20::as<bool>(na_rm_internal)))) {
        return cpp_to_sexp(test_var(cpp20::as<r_vec<T>>(x_internal), cpp20::as<bool>(na_rm_internal)));
    },
    x, na_rm
  );
  END_CPP20
}
// test_subset.h
extern "C" SEXP _cpp20_test_subset(SEXP x, SEXP i) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP i_internal) -> decltype(cpp_to_sexp(test_subset(cpp20::as<T>(x_internal), cpp20::as<r_vec<U>>(i_internal)))) {
        return cpp_to_sexp(test_subset(cpp20::as<T>(x_internal), cpp20::as<r_vec<U>>(i_internal)));
    },
    x, i
  );
  END_CPP20
}
// test_subset.h
extern "C" SEXP _cpp20_test_fill(SEXP x, SEXP where, SEXP with) {
  BEGIN_CPP20
  check_r_cpp_mapping<r_vec<r_int>>(where);
return dispatch_template_impl<2, 3, std::array<int, 3>{0, -1, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP where_internal, SEXP with_internal) -> decltype(cpp_to_sexp(test_fill(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<r_int>>(where_internal), cpp20::as<r_vec<U>>(with_internal)))) {
        return cpp_to_sexp(test_fill(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<r_int>>(where_internal), cpp20::as<r_vec<U>>(with_internal)));
    },
    x, where, with
  );
  END_CPP20
}
// test_subset.h
extern "C" SEXP _cpp20_test_counts(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_counts(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal)))) {
        return cpp_to_sexp(test_counts(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test_subset.h
extern "C" SEXP _cpp20_test_remove(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_remove(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal)))) {
        return cpp_to_sexp(test_remove(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test_subset.h
extern "C" SEXP _cpp20_test_find(SEXP x, SEXP y) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 2, std::array<int, 2>{0, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal) -> decltype(cpp_to_sexp(test_find(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal)))) {
        return cpp_to_sexp(test_find(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal)));
    },
    x, y
  );
  END_CPP20
}
// test_subset.h
extern "C" SEXP _cpp20_test_replace(SEXP x, SEXP y, SEXP z) {
  BEGIN_CPP20
  return dispatch_template_impl<2, 3, std::array<int, 3>{0, 1, 1}>(
    []<typename T, typename U>(SEXP x_internal, SEXP y_internal, SEXP z_internal) -> decltype(cpp_to_sexp(test_replace(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal), cpp20::as<r_vec<U>>(z_internal)))) {
        return cpp_to_sexp(test_replace(cpp20::as<r_vec<T>>(x_internal), cpp20::as<r_vec<U>>(y_internal), cpp20::as<r_vec<U>>(z_internal)));
    },
    x, y, z
  );
  END_CPP20
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp20_cpp20_typeof",              (DL_FUNC) &_cpp20_cpp20_typeof,              1},
    {"_cpp20_cpp_get_threads",           (DL_FUNC) &_cpp20_cpp_get_threads,           0},
    {"_cpp20_cpp_set_threads",           (DL_FUNC) &_cpp20_cpp_set_threads,           1},
    {"_cpp20_scalar1",                   (DL_FUNC) &_cpp20_scalar1,                   1},
    {"_cpp20_scalar2",                   (DL_FUNC) &_cpp20_scalar2,                   1},
    {"_cpp20_scalar3",                   (DL_FUNC) &_cpp20_scalar3,                   2},
    {"_cpp20_scalar4",                   (DL_FUNC) &_cpp20_scalar4,                   2},
    {"_cpp20_scalar_vec1",               (DL_FUNC) &_cpp20_scalar_vec1,               2},
    {"_cpp20_scalar_vec2",               (DL_FUNC) &_cpp20_scalar_vec2,               2},
    {"_cpp20_scalar_vec3",               (DL_FUNC) &_cpp20_scalar_vec3,               4},
    {"_cpp20_test_as_date",              (DL_FUNC) &_cpp20_test_as_date,              1},
    {"_cpp20_test_as_date2",             (DL_FUNC) &_cpp20_test_as_date2,             1},
    {"_cpp20_test_as_sym",               (DL_FUNC) &_cpp20_test_as_sym,               1},
    {"_cpp20_test_attrs",                (DL_FUNC) &_cpp20_test_attrs,                1},
    {"_cpp20_test_coerce",               (DL_FUNC) &_cpp20_test_coerce,               2},
    {"_cpp20_test_coerce1",              (DL_FUNC) &_cpp20_test_coerce1,              1},
    {"_cpp20_test_combine2",             (DL_FUNC) &_cpp20_test_combine2,             2},
    {"_cpp20_test_construct_date",       (DL_FUNC) &_cpp20_test_construct_date,       1},
    {"_cpp20_test_copy",                 (DL_FUNC) &_cpp20_test_copy,                 1},
    {"_cpp20_test_counts",               (DL_FUNC) &_cpp20_test_counts,               2},
    {"_cpp20_test_dates1",               (DL_FUNC) &_cpp20_test_dates1,               1},
    {"_cpp20_test_dates2",               (DL_FUNC) &_cpp20_test_dates2,               1},
    {"_cpp20_test_deduced_scalar_type",  (DL_FUNC) &_cpp20_test_deduced_scalar_type,  1},
    {"_cpp20_test_deduced_scalar_type2", (DL_FUNC) &_cpp20_test_deduced_scalar_type2, 1},
    {"_cpp20_test_deduced_type",         (DL_FUNC) &_cpp20_test_deduced_type,         1},
    {"_cpp20_test_deduced_vec_type",     (DL_FUNC) &_cpp20_test_deduced_vec_type,     1},
    {"_cpp20_test_df",                   (DL_FUNC) &_cpp20_test_df,                   1},
    {"_cpp20_test_factor1",              (DL_FUNC) &_cpp20_test_factor1,              1},
    {"_cpp20_test_factor2",              (DL_FUNC) &_cpp20_test_factor2,              1},
    {"_cpp20_test_fill",                 (DL_FUNC) &_cpp20_test_fill,                 3},
    {"_cpp20_test_find",                 (DL_FUNC) &_cpp20_test_find,                 2},
    {"_cpp20_test_group_counts",         (DL_FUNC) &_cpp20_test_group_counts,         2},
    {"_cpp20_test_group_id",             (DL_FUNC) &_cpp20_test_group_id,             2},
    {"_cpp20_test_identical",            (DL_FUNC) &_cpp20_test_identical,            2},
    {"_cpp20_test_identity",             (DL_FUNC) &_cpp20_test_identity,             1},
    {"_cpp20_test_identity2",            (DL_FUNC) &_cpp20_test_identity2,            1},
    {"_cpp20_test_lengths",              (DL_FUNC) &_cpp20_test_lengths,              1},
    {"_cpp20_test_list_to_scalars",      (DL_FUNC) &_cpp20_test_list_to_scalars,      1},
    {"_cpp20_test_match",                (DL_FUNC) &_cpp20_test_match,                2},
    {"_cpp20_test_mean",                 (DL_FUNC) &_cpp20_test_mean,                 2},
    {"_cpp20_test_mix2",                 (DL_FUNC) &_cpp20_test_mix2,                 7},
    {"_cpp20_test_multiple_deduction",   (DL_FUNC) &_cpp20_test_multiple_deduction,   2},
    {"_cpp20_test_n_unique",             (DL_FUNC) &_cpp20_test_n_unique,             1},
    {"_cpp20_test_na_types",             (DL_FUNC) &_cpp20_test_na_types,             0},
    {"_cpp20_test_nas",                  (DL_FUNC) &_cpp20_test_nas,                  1},
    {"_cpp20_test_null",                 (DL_FUNC) &_cpp20_test_null,                 0},
    {"_cpp20_test_order",                (DL_FUNC) &_cpp20_test_order,                2},
    {"_cpp20_test_range",                (DL_FUNC) &_cpp20_test_range,                2},
    {"_cpp20_test_remove",               (DL_FUNC) &_cpp20_test_remove,               2},
    {"_cpp20_test_replace",              (DL_FUNC) &_cpp20_test_replace,              3},
    {"_cpp20_test_rval_identity",        (DL_FUNC) &_cpp20_test_rval_identity,        1},
    {"_cpp20_test_scalar",               (DL_FUNC) &_cpp20_test_scalar,               2},
    {"_cpp20_test_scalar2",              (DL_FUNC) &_cpp20_test_scalar2,              2},
    {"_cpp20_test_scalar3",              (DL_FUNC) &_cpp20_test_scalar3,              2},
    {"_cpp20_test_seqs",                 (DL_FUNC) &_cpp20_test_seqs,                 3},
    {"_cpp20_test_sexp",                 (DL_FUNC) &_cpp20_test_sexp,                 1},
    {"_cpp20_test_sexp2",                (DL_FUNC) &_cpp20_test_sexp2,                1},
    {"_cpp20_test_sexp3",                (DL_FUNC) &_cpp20_test_sexp3,                1},
    {"_cpp20_test_sexp4",                (DL_FUNC) &_cpp20_test_sexp4,                1},
    {"_cpp20_test_sort",                 (DL_FUNC) &_cpp20_test_sort,                 2},
    {"_cpp20_test_specialisation",       (DL_FUNC) &_cpp20_test_specialisation,       1},
    {"_cpp20_test_str1",                 (DL_FUNC) &_cpp20_test_str1,                 1},
    {"_cpp20_test_str2",                 (DL_FUNC) &_cpp20_test_str2,                 1},
    {"_cpp20_test_str3",                 (DL_FUNC) &_cpp20_test_str3,                 1},
    {"_cpp20_test_str4",                 (DL_FUNC) &_cpp20_test_str4,                 1},
    {"_cpp20_test_subset",               (DL_FUNC) &_cpp20_test_subset,               2},
    {"_cpp20_test_sum",                  (DL_FUNC) &_cpp20_test_sum,                  2},
    {"_cpp20_test_sym",                  (DL_FUNC) &_cpp20_test_sym,                  1},
    {"_cpp20_test_template_null",        (DL_FUNC) &_cpp20_test_template_null,        1},
    {"_cpp20_test_tz",                   (DL_FUNC) &_cpp20_test_tz,                   1},
    {"_cpp20_test_unique",               (DL_FUNC) &_cpp20_test_unique,               1},
    {"_cpp20_test_var",                  (DL_FUNC) &_cpp20_test_var,                  2},
    {"_cpp20_vector1",                   (DL_FUNC) &_cpp20_vector1,                   1},
    {"_cpp20_vector2",                   (DL_FUNC) &_cpp20_vector2,                   1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp20(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
