// Generated by cppally: do not edit by hand
// clang-format off


#include <cppally/r_dispatch.h>
#include <cppally.hpp>
#include <R_ext/Visibility.h>


using namespace cppally;
using internal::cpp_to_r;
using internal::dispatch_template_impl;

// code.cpp
r_sexp ok(r_sexp x, r_sexp y);
extern "C" SEXP _cppally_ok(SEXP x, SEXP y) {
  BEGIN_CPPALLY
  return cpp_to_r(::ok(as<r_sexp>(x), as<r_sexp>(y)));
  END_CPPALLY
}
// code.cpp
void foo(r_sexp x);
extern "C" SEXP _cppally_foo(SEXP x) {
  BEGIN_CPPALLY
  ::foo(as<r_sexp>(x));
  return R_NilValue;
  END_CPPALLY
}
// code.cpp
r_sexp bar(r_sexp x);
extern "C" SEXP _cppally_bar(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::bar(as<r_sexp>(x)));
  END_CPPALLY
}
// code.cpp
int foobar(r_sexp x);
extern "C" SEXP _cppally_foobar(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::foobar(as<r_sexp>(x)));
  END_CPPALLY
}
// code.cpp
r_sexp foobarfoo(r_sexp x);
extern "C" SEXP _cppally_foobarfoo(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::foobarfoo(as<r_sexp>(x)));
  END_CPPALLY
}
// code.cpp
r_sexp foobarfoobar(r_sexp x);
extern "C" SEXP _cppally_foobarfoobar(SEXP x) {
  BEGIN_CPPALLY
  return cpp_to_r(::foobarfoobar(as<r_sexp>(x)));
  END_CPPALLY
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cppally_bar",          (DL_FUNC) &_cppally_bar,          1},
    {"_cppally_foo",          (DL_FUNC) &_cppally_foo,          1},
    {"_cppally_foobar",       (DL_FUNC) &_cppally_foobar,       1},
    {"_cppally_foobarfoo",    (DL_FUNC) &_cppally_foobarfoo,    1},
    {"_cppally_foobarfoobar", (DL_FUNC) &_cppally_foobarfoobar, 1},
    {"_cppally_ok",           (DL_FUNC) &_cppally_ok,           2},
    {NULL, NULL, 0}
};
}


extern "C" attribute_visible void R_init_cppally(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
