# Generated by cpp20: do not edit by hand

cpp20_typeof <- function(x) {
  .Call(`_cpp20_cpp20_typeof`, x)
}

test_vec_of_syms <- function(x) {
  .Call(`_cpp20_test_vec_of_syms`, x)
}

test_vec_of_syms2 <- function(x) {
  .Call(`_cpp20_test_vec_of_syms2`, x)
}

test_which <- function(x) {
  .Call(`_cpp20_test_which`, x)
}

test_which_inverted <- function(x) {
  .Call(`_cpp20_test_which_inverted`, x)
}

test_deduced_type <- function(x) {
  .Call(`_cpp20_test_deduced_type`, x)
}

test_multiple_deduction <- function(x, y) {
  .Call(`_cpp20_test_multiple_deduction`, x, y)
}

test_deduced_vec_type <- function(x) {
  .Call(`_cpp20_test_deduced_vec_type`, x)
}

test_deduced_scalar_type <- function(x) {
  .Call(`_cpp20_test_deduced_scalar_type`, x)
}

test_deduced_scalar_type2 <- function(x) {
  .Call(`_cpp20_test_deduced_scalar_type2`, x)
}

test_identity <- function(x) {
  .Call(`_cpp20_test_identity`, x)
}

test_identity2 <- function(x) {
  .Call(`_cpp20_test_identity2`, x)
}

test_template_null <- function(x) {
  .Call(`_cpp20_test_template_null`, x)
}

test_scalar <- function(x, y) {
  .Call(`_cpp20_test_scalar`, x, y)
}

test_scalar2 <- function(x, y) {
  .Call(`_cpp20_test_scalar2`, x, y)
}

test_scalar3 <- function(x, y) {
  .Call(`_cpp20_test_scalar3`, x, y)
}

test_rval_identity <- function(x) {
  .Call(`_cpp20_test_rval_identity`, x)
}

scalar1 <- function(x) {
  .Call(`_cpp20_scalar1`, x)
}

scalar2 <- function(x) {
  .Call(`_cpp20_scalar2`, x)
}

vector1 <- function(x) {
  .Call(`_cpp20_vector1`, x)
}

vector2 <- function(x) {
  .Call(`_cpp20_vector2`, x)
}

scalar3 <- function(x, y) {
  .Call(`_cpp20_scalar3`, x, y)
}

scalar4 <- function(x, y) {
  .Call(`_cpp20_scalar4`, x, y)
}

test_sexp <- function(x) {
  .Call(`_cpp20_test_sexp`, x)
}

test_sexp4 <- function(x) {
  .Call(`_cpp20_test_sexp4`, x)
}

scalar_vec1 <- function(a, b) {
  .Call(`_cpp20_scalar_vec1`, a, b)
}

scalar_vec2 <- function(a, b) {
  .Call(`_cpp20_scalar_vec2`, a, b)
}

scalar_vec3 <- function(z, x, y, a) {
  .Call(`_cpp20_scalar_vec3`, z, x, y, a)
}

test_mix2 <- function(a, b, c, d, e, f, g) {
  .Call(`_cpp20_test_mix2`, a, b, c, d, e, f, g)
}

test_str1 <- function(x) {
  .Call(`_cpp20_test_str1`, x)
}

test_str2 <- function(x) {
  .Call(`_cpp20_test_str2`, x)
}

test_str3 <- function(x) {
  .Call(`_cpp20_test_str3`, x)
}

test_str4 <- function(x) {
  .Call(`_cpp20_test_str4`, x)
}

test_as_sym <- function(x) {
  .Call(`_cpp20_test_as_sym`, x)
}

test_specialisation <- function(x) {
  .Call(`_cpp20_test_specialisation`, x)
}

test_coerce <- function(x, ptype) {
  .Call(`_cpp20_test_coerce`, x, ptype)
}

test_as_date <- function(x) {
  .Call(`_cpp20_test_as_date`, x)
}

test_construct_date <- function(x) {
  .Call(`_cpp20_test_construct_date`, x)
}

test_as_date2 <- function(x) {
  .Call(`_cpp20_test_as_date2`, x)
}

cpp_set_threads <- function(n) {
  invisible(.Call(`_cpp20_cpp_set_threads`, n))
}

cpp_get_threads <- function() {
  .Call(`_cpp20_cpp_get_threads`)
}

test_null <- function() {
  .Call(`_cpp20_test_null`)
}

test_sym <- function(x) {
  .Call(`_cpp20_test_sym`, x)
}

test_sexp2 <- function(x) {
  .Call(`_cpp20_test_sexp2`, x)
}

test_sexp3 <- function(x) {
  .Call(`_cpp20_test_sexp3`, x)
}

test_list_to_scalars <- function(x) {
  .Call(`_cpp20_test_list_to_scalars`, x)
}

test_coerce1 <- function(x) {
  .Call(`_cpp20_test_coerce1`, x)
}

test_combine2 <- function(x, y) {
  .Call(`_cpp20_test_combine2`, x, y)
}

test_dates1 <- function(x) {
  .Call(`_cpp20_test_dates1`, x)
}

test_dates2 <- function(x) {
  .Call(`_cpp20_test_dates2`, x)
}

test_unique <- function(x) {
  .Call(`_cpp20_test_unique`, x)
}

test_seqs <- function(size, from, by) {
  .Call(`_cpp20_test_seqs`, size, from, by)
}

test_tz <- function(x) {
  .Call(`_cpp20_test_tz`, x)
}

test_time_coerce <- function() {
  .Call(`_cpp20_test_time_coerce`)
}

test_group_id <- function(x, order) {
  .Call(`_cpp20_test_group_id`, x, order)
}

test_group_counts <- function(x, order) {
  .Call(`_cpp20_test_group_counts`, x, order)
}

test_lengths <- function(x) {
  .Call(`_cpp20_test_lengths`, x)
}

test_match <- function(x, y) {
  .Call(`_cpp20_test_match`, x, y)
}

test_factor1 <- function(x) {
  .Call(`_cpp20_test_factor1`, x)
}

test_factor2 <- function(x) {
  .Call(`_cpp20_test_factor2`, x)
}

test_n_unique <- function(x) {
  .Call(`_cpp20_test_n_unique`, x)
}

test_identical <- function(x, y) {
  .Call(`_cpp20_test_identical`, x, y)
}

test_copy <- function(x) {
  .Call(`_cpp20_test_copy`, x)
}

test_attrs <- function(x) {
  .Call(`_cpp20_test_attrs`, x)
}

test_nas <- function(x) {
  .Call(`_cpp20_test_nas`, x)
}

test_na_types <- function() {
  .Call(`_cpp20_test_na_types`)
}

test_order <- function(x, preserve_ties) {
  .Call(`_cpp20_test_order`, x, preserve_ties)
}

test_sort <- function(x, preserve_ties) {
  .Call(`_cpp20_test_sort`, x, preserve_ties)
}

test_range <- function(x, na_rm) {
  .Call(`_cpp20_test_range`, x, na_rm)
}

test_sum <- function(x, na_rm) {
  .Call(`_cpp20_test_sum`, x, na_rm)
}

test_mean <- function(x, na_rm) {
  .Call(`_cpp20_test_mean`, x, na_rm)
}

test_var <- function(x, na_rm) {
  .Call(`_cpp20_test_var`, x, na_rm)
}

test_subset <- function(x, i) {
  .Call(`_cpp20_test_subset`, x, i)
}

test_fill <- function(x, where, with) {
  .Call(`_cpp20_test_fill`, x, where, with)
}

test_counts <- function(x, y) {
  .Call(`_cpp20_test_counts`, x, y)
}

test_remove <- function(x, y) {
  .Call(`_cpp20_test_remove`, x, y)
}

test_find <- function(x, y) {
  .Call(`_cpp20_test_find`, x, y)
}

test_replace <- function(x, y, z) {
  .Call(`_cpp20_test_replace`, x, y, z)
}
