# Generated by cpp20: do not edit by hand

test_deduced_type <- function(x) {
  .Call(`_cpp20_test_deduced_type`, x)
}

test_multiple_deduction <- function(x, y) {
  .Call(`_cpp20_test_multiple_deduction`, x, y)
}

test_deduced_vec_type <- function(x) {
  .Call(`_cpp20_test_deduced_vec_type`, x)
}

test_deduced_scalar_type <- function(x) {
  .Call(`_cpp20_test_deduced_scalar_type`, x)
}

test_identity <- function(x) {
  .Call(`_cpp20_test_identity`, x)
}

test_identity2 <- function(x) {
  .Call(`_cpp20_test_identity2`, x)
}

test_template_null <- function(x) {
  .Call(`_cpp20_test_template_null`, x)
}

test_scalar <- function(x, y) {
  .Call(`_cpp20_test_scalar`, x, y)
}

test_scalar2 <- function(x, y) {
  .Call(`_cpp20_test_scalar2`, x, y)
}

test_scalar3 <- function(x, y) {
  .Call(`_cpp20_test_scalar3`, x, y)
}

test_rval_identity <- function(x) {
  .Call(`_cpp20_test_rval_identity`, x)
}

scalar1 <- function(x) {
  .Call(`_cpp20_scalar1`, x)
}

scalar2 <- function(x) {
  .Call(`_cpp20_scalar2`, x)
}

vector1 <- function(x) {
  .Call(`_cpp20_vector1`, x)
}

vector2 <- function(x) {
  .Call(`_cpp20_vector2`, x)
}

scalar3 <- function(x, y) {
  .Call(`_cpp20_scalar3`, x, y)
}

scalar4 <- function(x, y) {
  .Call(`_cpp20_scalar4`, x, y)
}

test_sexp <- function(x) {
  .Call(`_cpp20_test_sexp`, x)
}

test_sexp4 <- function(x) {
  .Call(`_cpp20_test_sexp4`, x)
}

scalar_vec1 <- function(a, b) {
  .Call(`_cpp20_scalar_vec1`, a, b)
}

scalar_vec2 <- function(a, b) {
  .Call(`_cpp20_scalar_vec2`, a, b)
}

scalar_vec3 <- function(z, x, y, a) {
  .Call(`_cpp20_scalar_vec3`, z, x, y, a)
}

test_mix2 <- function(a, b, c, d, e, f, g) {
  .Call(`_cpp20_test_mix2`, a, b, c, d, e, f, g)
}

test_str1 <- function(x) {
  .Call(`_cpp20_test_str1`, x)
}

test_str2 <- function(x) {
  .Call(`_cpp20_test_str2`, x)
}

test_str3 <- function(x) {
  .Call(`_cpp20_test_str3`, x)
}

test_str4 <- function(x) {
  .Call(`_cpp20_test_str4`, x)
}

test_as_sym <- function(x) {
  .Call(`_cpp20_test_as_sym`, x)
}

test_specialisation <- function(x) {
  .Call(`_cpp20_test_specialisation`, x)
}

test_coerce <- function(x, ptype) {
  .Call(`_cpp20_test_coerce`, x, ptype)
}

cpp_set_threads <- function(n) {
  invisible(.Call(`_cpp20_cpp_set_threads`, n))
}

cpp_get_threads <- function() {
  .Call(`_cpp20_cpp_get_threads`)
}

test_null <- function() {
  .Call(`_cpp20_test_null`)
}

test_sym <- function(x) {
  .Call(`_cpp20_test_sym`, x)
}

test_sexp2 <- function(x) {
  .Call(`_cpp20_test_sexp2`, x)
}

test_sexp3 <- function(x) {
  .Call(`_cpp20_test_sexp3`, x)
}

test_list_to_scalars <- function(x) {
  .Call(`_cpp20_test_list_to_scalars`, x)
}

test_coerce1 <- function(x) {
  .Call(`_cpp20_test_coerce1`, x)
}

test_constructions <- function(x) {
  .Call(`_cpp20_test_constructions`, x)
}

test_constructions2 <- function(x) {
  .Call(`_cpp20_test_constructions2`, x)
}

test_constructions3 <- function(x) {
  .Call(`_cpp20_test_constructions3`, x)
}

test_constructions4 <- function(x) {
  .Call(`_cpp20_test_constructions4`, x)
}

test_set_strs <- function(x) {
  .Call(`_cpp20_test_set_strs`, x)
}

test_set_strs2 <- function(x) {
  .Call(`_cpp20_test_set_strs2`, x)
}
